# Generated by Django 2.2.7 on 2019-12-17 14:55

from django.db import migrations, models
import django.db.models.deletion
from src.base import models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('speed_coef', models.FloatField(default=1)),
                ('do_forecast', models.CharField(choices=[('H', 'Hard'), ('L', 'Lite'), ('N', 'None')], default='L', max_length=1)),
                ('period_demand_params', models.CharField(default='{"max_depth": 10, "eta": 0.2, "min_split_loss": 200, "reg_lambda": 2, "silent": 1, "iterations": 20}', max_length=1024)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_type_reversed', to='timetable.WorkType')),
            ],
            options={
                'verbose_name': 'Тип операции',
                'verbose_name_plural': 'Типы операций',
            },
        ),
        migrations.CreateModel(
            name='PeriodDemandChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_from', models.DateTimeField()),
                ('dttm_to', models.DateTimeField()),
                ('multiply_coef', models.FloatField(blank=True, null=True)),
                ('set_value', models.FloatField(blank=True, null=True)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.OperationType')),
            ],
            options={
                'verbose_name': 'Лог изменений спроса',
            },
        ),
        migrations.CreateModel(
            name='PeriodClients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dttm_forecast', models.DateTimeField()),
                ('type', models.CharField(choices=[('L', 'Long'), ('S', 'Short'), ('F', 'Fact')], default='L', max_length=1)),
                ('value', models.FloatField(default=0)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.OperationType')),
            ],
            options={
                'verbose_name': 'Значение операций',
            },
        ),
        migrations.CreateModel(
            name='OperationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('tm_start', models.TimeField()),
                ('tm_end', models.TimeField()),
                ('value', models.FloatField()),
                ('period', models.CharField(choices=[('D', 'Ежедневно'), ('W', 'В неделю'), ('M', 'В месяц')], default='D', max_length=1)),
                ('days_in_period', models_utils.IntegerListField()),
                ('dt_built_to', models.DateField(blank=True, null=True)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_type_reversed', to='forecast.OperationType')),
            ],
            options={
                'verbose_name': 'Шаблон операций',
                'verbose_name_plural': 'Шаблоны операций',
            },
        ),
    ]
