# Generated by Django 2.2.7 on 2019-12-23 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Название операции',
                'verbose_name_plural': 'Названия операций',
            },
        ),
        migrations.RemoveField(
            model_name='operationtype',
            name='name',
        ),
        migrations.AddField(
            model_name='operationtemplate',
            name='code',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='dttm_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='dttm_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operationtype',
            name='operation_type_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forecast.OperationTypeName'),
            preserve_default=False,
        ),
    ]
