# Generated by Django 2.2.7 on 2020-02-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200205_0924'),
        ('forecast', '0006_auto_20200205_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtemplate',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='operationtype',
            unique_together={('work_type', 'operation_type_name')},
        ),
    ]
