# Generated by Django 2.2.7 on 2020-04-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200211_0723'),
        ('timetable', '0007_auto_20200220_0727'),
        ('forecast', '0006_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('R', 'Применён'), ('U', 'Обновлён'), ('N', 'Новый'), ('E', 'Ошибка')], default='N', max_length=1)),
                ('error_message', models.CharField(max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Шаблон нагрузки',
                'verbose_name_plural': 'Шаблоны нагрузки',
            },
        ),
        migrations.RemoveField(
            model_name='operationtype',
            name='speed_coef',
        ),
        migrations.AddField(
            model_name='operationtype',
            name='shop',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_types', to='base.Shop'),
        ),
        migrations.AddField(
            model_name='operationtype',
            name='status',
            field=models.CharField(choices=[('R', 'Применён'), ('U', 'Обновлён')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opeartion_templates', to='forecast.OperationType'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='do_forecast',
            field=models.CharField(choices=[('H', 'Forecast'), ('N', 'None'), ('T', 'Template'), ('F', 'Formula')], default='H', max_length=1),
        ),
        # migrations.AlterField(
        #     model_name='operationtype',
        #     name='work_type',
        #     field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_type', to='timetable.WorkType'),
        # ),
        migrations.CreateModel(
            name='OperationTypeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_forecast', models.CharField(choices=[('H', 'Forecast'), ('N', 'None'), ('T', 'Template'), ('F', 'Formula')], default='H', max_length=1)),
                ('load_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_type_templates', to='forecast.LoadTemplate')),
                ('operation_type_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.OperationTypeName')),
                ('work_type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.WorkTypeName')),
            ],
            options={
                'verbose_name': 'Шаблон типа операции',
                'verbose_name_plural': 'Шаблоны типов операций',
                'unique_together': {('load_template', 'operation_type_name')},
            },
        ),
        migrations.CreateModel(
            name='OperationTypeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=256)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends', to='forecast.OperationTypeTemplate')),
                ('depended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='forecast.OperationTypeTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
