# Generated by Django 2.2.7 on 2020-04-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_auto_20200317_1237'),
        ('forecast', '0007_auto_20200407_0803'),
    ]

    operations = [
    ]
