# Generated by Django 2.2.7 on 2020-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_auto_20200205_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtemplate',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
