# Generated by Django 2.2.7 on 2020-05-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0011_merge_20200506_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtype',
            name='work_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_type', to='timetable.WorkType'),
        ),
    ]
