# Generated by Django 2.2.7 on 2020-07-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0015_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_aggregated',
            field=models.BooleanField(default=False),
        ),
    ]
