# Generated by Django 2.2.7 on 2020-08-13 14:07

from django.db import migrations, models
import django.db.models.deletion


def set_network(apps, schema_editor):
    network = apps.get_model('base', 'Network').objects.first()
    apps.get_model('forecast', 'OperationTypeName').objects.all().update(network=network)
    apps.get_model('forecast', 'OperationTemplate').objects.all().update(network=network)
    apps.get_model('forecast', 'LoadTemplate').objects.all().update(network=network)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20200813_1407'),
        ('forecast', '0015_auto_20200730_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtemplate',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network'),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='work_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_type', to='timetable.WorkType'),
        ),
        migrations.AlterField(
            model_name='operationtypename',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='operationtemplate',
            unique_together={('code', 'network')},
        ),
        migrations.AlterUniqueTogether(
            name='operationtypename',
            unique_together={('code', 'network')},
        ),
        migrations.RunPython(set_network),
    ]
