# Generated by Django 2.2.7 on 2020-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0016_receipt_is_aggregated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='code',
            field=models.UUIDField(unique=True),
        ),
    ]
