# Generated by Django 2.2.7 on 2020-08-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0018_auto_20200823_1414'),
        ('forecast', '0019_merge_20200813_1420'),
    ]

    operations = [
    ]
