# Generated by Django 2.2.7 on 2020-09-02 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0020_merge_20200826_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtemplate',
            name='status',
            field=models.CharField(choices=[('P', 'В процессе'), ('R', 'Готово')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='operationtyperelation',
            name='type',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='operationtypetemplate',
            name='forecast_step',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='operationtypetemplate',
            name='tm_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationtypetemplate',
            name='tm_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
