# Generated by Django 2.2.7 on 2020-09-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0021_auto_20200902_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadtemplate',
            name='status',
        ),
    ]
