# Generated by Django 2.2.7 on 2020-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0023_merge_20200907_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodclients',
            name='dttm_forecast',
            field=models.DateTimeField(),
        ),
        migrations.AlterIndexTogether(
            name='periodclients',
            index_together={('dttm_forecast', 'operation_type')},
        ),
    ]
