# Generated by Django 2.2.7 on 2020-09-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0023_merge_20200907_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='receipt',
            name='event_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='code',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='dttm',
            field=models.DateTimeField(verbose_name='Дата и время события'),
        ),
    ]
