# Generated by Django 2.2.7 on 2020-09-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0024_auto_20200910_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='event_type',
            new_name='data_type',
        ),
    ]
