# Generated by Django 2.2.7 on 2020-09-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0025_auto_20200914_1327'),
        ('forecast', '0024_auto_20200909_1010'),
    ]

    operations = [
    ]
