# Generated by Django 2.2.7 on 2020-09-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0024_auto_20200914_0621'),
        ('forecast', '0026_merge_20200918_0539'),
    ]

    operations = [
    ]
