# Generated by Django 2.2.7 on 2020-11-23 14:17

from django.db import migrations
from django.db.models import OuterRef, Subquery


def remove_period_client_duplicates(apps, schema_editor):
    PeriodClients = apps.get_model('forecast', 'PeriodClients')
    pc_subq = PeriodClients.objects.filter(
        dttm_forecast=OuterRef('dttm_forecast'),
        operation_type_id=OuterRef('operation_type_id'),
        type=OuterRef('type'),
    ).order_by('-id').values_list('id', flat=True)[1:]
    PeriodClients.objects.filter(id__in=Subquery(pc_subq)).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('forecast', '0028_auto_20201008_0850'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='periodclients',
            index_together={('dttm_forecast', 'operation_type', 'type')},
        ),
        migrations.RunPython(remove_period_client_duplicates, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='periodclients',
            unique_together={('dttm_forecast', 'operation_type', 'type')},
        ),
        migrations.AlterIndexTogether(
            name='periodclients',
            index_together=set(),
        ),
    ]
