# Generated by Django 2.2.7 on 2020-11-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0030_merge_20201126_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Шаблон операций', 'verbose_name_plural': 'Шаблоны операций'},
        ),
        migrations.AlterModelOptions(
            name='operationtypename',
            options={'ordering': ['name'], 'verbose_name': 'Название операции', 'verbose_name_plural': 'Названия операций'},
        ),
    ]
