# Generated by Django 2.2.16 on 2020-12-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0033_operationtypetemplate_const_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtyperelation',
            name='formula',
            field=models.CharField(max_length=512),
        ),
    ]
