# Generated by Django 2.2.24 on 2021-09-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0040_auto_20210803_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='code',
            field=models.CharField(max_length=256),
        ),
    ]
