# Generated by Django 3.2.9 on 2021-11-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0043_auto_20210927_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtemplate',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
