# Generated by Django 3.2.9 on 2021-11-19 07:58

from django.db import migrations
import src.base.fields


def compress_info(apps, schema_editor):
    Receipt = apps.get_model('forecast', 'Receipt')
    receipts = Receipt.objects.all()
    step = 100000
    receipts_portion = receipts[:step]
    i = step
    while receipts_portion:
        Receipt.objects.bulk_update(receipts_portion, fields=['info'])
        receipts_portion = receipts[i:i + step]
        i = i + step

class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0044_loadtemplate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='info',
            field=src.base.fields.CompressedTextField(),
        ),
        migrations.RunPython(compress_info, migrations.RunPython.noop),
    ]
