# Generated by Django 3.2.9 on 2021-11-19 07:58

from django.db import migrations
import src.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0044_loadtemplate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='info',
            field=src.base.fields.CompressedTextField(),
        ),
    ]
