# Generated by Django 3.2.9 on 2021-11-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0045_alter_receipt_info'),
    ]
    atomic = False

    operations = []
