# Generated by Django 3.2.9 on 2021-12-06 05:54

import re
from django.db import migrations

def add_load_template_permissions(apps, schema_editor):
    Group = apps.get_model('base', 'Group')
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    pattern = r'админ(истратор)?(?=$|(\sm&m))'
    funcs = [
        ('LoadTemplate', ['GET', 'POST', 'PUT', 'DELETE']),
        ('LoadTemplate_apply', ['POST']),
        ('LoadTemplate_calculate', ['POST']),
        ('LoadTemplate_download', ['GET']),
        ('LoadTemplate_upload', ['POST']),
        ('OperationTypeRelation', ['GET', 'POST', 'PUT', 'DELETE']),
        ('OperationTypeTemplate', ['GET', 'POST', 'PUT', 'DELETE']),
    ]
    for g in Group.objects.all():
        if re.search(pattern, g.name, re.IGNORECASE):
            for func, methods in funcs:
                for method in methods:
                    FunctionGroup.objects.update_or_create(
                        func=func,
                        method=method,
                        group=g,
                        defaults={
                            'access_type': 'A',
                        }
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0046_auto_20211122_0642'),
    ]

    operations = [
        migrations.RunPython(add_load_template_permissions, migrations.RunPython.noop),
    ]
