# Generated by Django 3.2.9 on 2021-12-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0047_auto_20211206_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtypename',
            name='work_type_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_type_name', to='timetable.worktypename'),
        ),
    ]
