# Generated by Django 3.2.9 on 2022-02-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0050_auto_20220202_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perioddemandchangelog',
            name='operation_type',
        ),
        migrations.DeleteModel(
            name='OperationTemplate',
        ),
        migrations.DeleteModel(
            name='PeriodDemandChangeLog',
        ),
    ]
