# Generated by Django 3.2.9 on 2022-02-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0050_auto_20220128_0644'),
        ('forecast', '0051_auto_20220211_1326'),
    ]

    operations = [
    ]
