# Generated by Django 3.2.9 on 2022-09-16 13:22

from django.db import migrations, models

def fill_dt_report(apps, schema_editor):
    PeriodClients = apps.get_model('forecast', 'PeriodClients')
    PeriodClients.objects.update(dt_report=models.ExpressionWrapper((models.F('dttm_forecast')), output_field=models.DateField()))

class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0053_alter_operationtypename_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodclients',
            name='dt_report',
            field=models.DateField(null=True, verbose_name='Дата отчёта (файла с данными)'),
        ),
        migrations.RunPython(fill_dt_report),
        migrations.AlterField(
            model_name='periodclients',
            name='dt_report',
            field=models.DateField(verbose_name='Дата отчёта (файла с данными)'),
        ),
        migrations.AlterField(
            model_name='periodclients',
            name='dttm_forecast',
            field=models.DateTimeField(verbose_name='Дата и время агрегации'),
        ),
    ]
