# Generated by Django 3.2.9 on 2022-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0055_auto_20220919_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtypetemplate',
            name='duplicate_over',
            field=models.CharField(choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day'), ('None', 'Not specified')], default=None, help_text='Period, that time series values need to be duplicated over. Signifies, that values should be treated as constant for this period.', max_length=5, null=True, verbose_name='duplicate over'),
        ),
    ]
