# Generated by Django 3.2.9 on 2022-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0056_operationtypetemplate_duplicate_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtypetemplate',
            name='duplicate_over',
            field=models.CharField(choices=[('None', 'Not specified'), ('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day')], default='None', help_text='Period, that time series values need to be duplicated over. Signifies, that values should be treated as constant for this period.', max_length=5, null=True, verbose_name='duplicate over'),
        ),
    ]
