# Generated by Django 2.2.16 on 2021-04-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        ('base', '0090_merge_20210405_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_celery_beat.CrontabSchedule', verbose_name='Расписание для отправки')),
                ('shops', models.ManyToManyField(blank=True, to='base.Shop', verbose_name='Фильтровать по выбранным отделам')),
            ],
        ),
    ]
