# Generated by Django 2.2.24 on 2021-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210928_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(choices=[('D', 'Day'), ('M', 'Month'), ('Q', 'Quarter'), ('H', 'Half a year'), ('Y', 'Year')], default='D', max_length=2, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_start',
            field=models.CharField(choices=[('T', 'Today'), ('E', 'Yesterday'), ('M', 'End of previous month'), ('CM', 'End of current month'), ('Q', 'End of previous quarter'), ('H', 'End of previous half a year'), ('Y', 'End of previous year')], default='E', max_length=2, verbose_name='Начало периода'),
        ),
    ]
