# Generated by Django 2.2.16 on 2021-10-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20210928_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='filter_recipients_by_shops_in_data',
            field=models.BooleanField(default=False, verbose_name='Фильтровать получателей по магазинам в данных'),
        ),
    ]
