# Generated by Django 2.2.24 on 2021-09-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20210927_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftpfilesystemconnector',
            old_name='base_path',
            new_name='default_base_path',
        ),
    ]
