# Generated by Django 3.2.9 on 2021-11-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20211115_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemImportStrategy',
        ),
    ]
