# Generated by Django 3.2.9 on 2022-02-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_localfilesystemconnector_default_base_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='retry_attempts',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='retry_attempts',
            field=models.TextField(default='{}'),
        ),
    ]
