# Generated by Django 3.2.9 on 2022-11-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_alter_localfilesystemconnector_default_base_path'),
        ('exchange', '0014_auto_20221116_0857'),
    ]

    operations = [
    ]
