# Generated by Django 3.2.9 on 2022-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_alter_importhistdatastrategy_remove_duplicates_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistdatastrategy',
            name='remove_duplicates_columns',
            field=models.JSONField(blank=True, null=True, verbose_name='Columns that act as a key when taking the final discounted price'),
        ),
    ]
