# Generated by Django 3.2.9 on 2022-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_eventemailnotification_system_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemailnotification',
            name='shop_ancestors_level',
            field=models.PositiveIntegerField(default=None, help_text='Leave blank for all', null=True, verbose_name='Ancestor level'),
        ),
        migrations.AddField(
            model_name='eventonlinenotification',
            name='shop_ancestors_level',
            field=models.PositiveIntegerField(default=None, help_text='Leave blank for all', null=True, verbose_name='Ancestor level'),
        ),
    ]
