# Generated by Django 2.2.7 on 2020-12-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventemailnotification',
            name='custom_email_template',
            field=models.TextField(blank=True, help_text='Будет использован только если не выбран "Системный E-mail шаблон"', null=True, verbose_name='Пользовательский E-mail шаблон'),
        ),
        migrations.AlterField(
            model_name='eventemailnotification',
            name='subject',
            field=models.CharField(blank=True, help_text='По умолчанию берется из названия "Системный E-mail шаблон"', max_length=256, null=True, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='eventemailnotification',
            name='system_email_template',
            field=models.CharField(blank=True, choices=[('notifications/email/employee_canceled_vacancy.html', 'Сотрудник отменил вакансию'), ('notifications/email/employee_responded_to_the_vacancy.html', 'Сотрудник откликнулся на вакансию'), ('notifications/email/request_approve.html', 'Подразделение {{ shop.name }} запрашивает подтверждения графика'), ('notifications/email/approve.html', 'График в подразделении {{ shop.name }} подтвержден')], max_length=256, null=True, verbose_name='Системный E-mail шаблон'),
        ),
    ]
