# Generated by Django 2.2.7 on 2020-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemailnotification',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='eventemailnotification',
            name='system_email_template',
            field=models.CharField(blank=True, choices=[('notifications/employee_canceled_vacancy.html', 'Сотрудник отменил вакансию'), ('notifications/employee_responded_to_the_vacancy.html', 'Сотрудник откликнулся на вакансию')], max_length=256, null=True, verbose_name='Системный E-mail шаблон'),
        ),
    ]
