# Generated by Django 2.2.16 on 2021-04-19 08:36

from django.db import migrations, models
import django.db.models.deletion

def copy_crons(apps, schema_editor):
    EventEmailNotification = apps.get_model('notifications', 'EventEmailNotification')
    ReportConfig = apps.get_model('reports', 'ReportConfig')
    for notification in EventEmailNotification.objects.select_related('cron').filter(cron__isnull=False):
        report_config, _ = ReportConfig.objects.get_or_create(
            cron_id=notification.cron_id,
            defaults={
                'name': f'Автоматический конфиг для расписания {notification.cron_id}'
            }
        )
        notification.report_config = report_config
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('notifications', '0002_auto_20210209_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemailnotification',
            name='report_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.ReportConfig', verbose_name='Конфигурация отчета'),
        ),
        migrations.AlterField(
            model_name='eventemailnotification',
            name='system_email_template',
            field=models.CharField(blank=True, choices=[('notifications/email/employee_canceled_vacancy.html', 'Сотрудник отменил вакансию'), ('notifications/email/employee_responded_to_the_vacancy.html', 'Сотрудник откликнулся на вакансию'), ('notifications/email/request_approve.html', 'Подразделение {{ shop.name }} запрашивает подтверждения графика'), ('notifications/email/approve.html', 'График в подразделении {{ shop.name }} подтвержден'), ('notifications/email/employee_not_checked_in.html', 'Сотрудник {{ user.last_name }} {{ user.first_name }} не отметился на {{ type }} в {{ dttm }}.'), ('notifications/email/employee_working_not_according_to_plan.html', 'Сотрудник {{ user.last_name }} {{ user.first_name }} вышел не по плану в {{ dttm }}.')], max_length=256, null=True, verbose_name='Системный E-mail шаблон'),
        ),
        migrations.RunPython(copy_crons),
        migrations.RemoveField(
            model_name='eventemailnotification',
            name='cron',
        ),
    ]
