# Generated by Django 2.2.16 on 2021-04-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210419_0836'),
        ('notifications', '0003_auto_20210421_1310'),
    ]

    operations = [
    ]
