# Generated by Django 3.2.9 on 2021-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20210722_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventemailnotification',
            name='employee_shop_groups',
            field=models.ManyToManyField(blank=True, related_name='_notifications_eventemailnotification_employee_shop_groups_+', to='base.Group', verbose_name='Оповещать пользователей магазина сотрудника, имеющих выбранные группы'),
        ),
        migrations.AddField(
            model_name='eventonlinenotification',
            name='employee_shop_groups',
            field=models.ManyToManyField(blank=True, related_name='_notifications_eventonlinenotification_employee_shop_groups_+', to='base.Group', verbose_name='Оповещать пользователей магазина сотрудника, имеющих выбранные группы'),
        ),
    ]
