# Generated by Django 2.2.7 on 2020-01-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191223_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='workerposition',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
