# Generated by Django 2.2.7 on 2020-01-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191223_1019'),
        ('base', '0002_auto_20191225_1528'),
    ]

    operations = [
    ]
