# Generated by Django 2.2.7 on 2020-02-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200211_0723'),
        ('base', '0006_auto_20200214_1117'),
    ]

    operations = [
    ]
