# Generated by Django 2.2.7 on 2020-03-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200312_0912'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='user',
#            name='tabel_code',
#            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
#        ),
    ]
