# Generated by Django 2.2.7 on 2020-03-23 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200323_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dttm_valid_to',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='tabel_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
