# Generated by Django 2.2.7 on 2020-04-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_merge_20200407_0819'),
        ('base', '0014_merge_20200406_1405'),
    ]

    operations = [
    ]
