# Generated by Django 2.2.7 on 2020-04-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_user_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='params',
        ),
    ]
