# Generated by Django 2.2.7 on 2020-05-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200427_1045'),
        ('base', '0025_auto_20200427_1146'),
    ]

    operations = [
    ]
