# Generated by Django 2.2.7 on 2020-04-30 14:05

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_runsql'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='absenteeism',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='break_triplets',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='cost_weights',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='even_shift_morning_evening',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='exit1day',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='exit42hours',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='fot',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='idle',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='init_params',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='less_norm',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='max_work_hours_7days',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='method_params',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='min_change_time',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='more_norm',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='paired_weekday',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='process_type',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='queue_length',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shift_end',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shift_start',
        ),
    ]
