# Generated by Django 2.2.7 on 2020-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20200512_0956'),
    ]

    operations = [

    ]
