# Generated by Django 2.2.7 on 2020-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20200512_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='exchange_shops',
            field=models.ManyToManyField(related_name='_shop_exchange_shops_+', to='base.Shop'),
        ),
    ]
