# Generated by Django 2.2.7 on 2020-05-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20200513_0839'),
        ('base', '0028_merge_20200511_1239'),
    ]

    operations = [
    ]
