# Generated by Django 2.2.7 on 2020-07-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200713_1135'),
        ('base', '0037_auto_20200629_0902'),
    ]

    operations = [
    ]
