# Generated by Django 2.2.7 on 2020-07-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200629_0902'),
        ('base', '0037_shop_exchange_settings'),
        ('base', '0027_auto_20200512_0956'),
    ]

    operations = [
    ]
