# Generated by Django 2.2.7 on 2020-07-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_merge_20200714_1422'),
        ('base', '0038_auto_20200730_0816'),
    ]

    operations = [
    ]
