# Generated by Django 2.2.7 on 2020-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20200729_1223'),
    ]

    operations = [
        migrations.RenameField(
            'shop',
            'tm_close_list',
            'tm_close_dict',
        ),
        migrations.RenameField(
            'shop',
            'tm_open_list',
            'tm_open_dict',
        ),
    ]
