# Generated by Django 2.2.7 on 2020-08-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20200730_1447'),
        ('base', '0040_auto_20200723_1041'),
    ]

    operations = [
    ]
