# Generated by Django 2.2.7 on 2020-08-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20200731_1423'),
        ('base', '0039_merge_20200730_0839'),
    ]

    operations = [
    ]
