# Generated by Django 2.2.7 on 2020-08-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20200730_0816'),
        ('base', '0045_merge_20200809_1955'),
    ]

    operations = [
    ]
