# Generated by Django 2.2.7 on 2020-09-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20200831_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='workerposition',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
