# Generated by Django 2.2.7 on 2020-09-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20200831_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='load_template_status',
            field=models.CharField(choices=[('P', 'В процессе'), ('R', 'Готово'), ('E', 'Ошибка')], default='R', max_length=1),
        ),
    ]
