# Generated by Django 2.2.7 on 2020-09-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_shop_load_template_status'),
        ('base', '0053_merge_20200904_0932'),
    ]

    operations = [
    ]
