# Generated by Django 2.2.7 on 2020-10-07 13:08

from datetime import timedelta

import django.utils.timezone
from django.db import migrations, models


def add_default_tabel_settings(apps, schema_editor):
    TabelSettings = apps.get_model('base', 'TabelSettings')
    TabelSettings.objects.get_or_create(
        code='default',
        defaults=dict(
            name='Настройки по умолчанию',
            allowed_interval_for_late_arrival=timedelta(minutes=15),
            allowed_interval_for_early_departure=timedelta(seconds=5),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0056_auto_20201003_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('allowed_interval_for_late_arrival',
                 models.DurationField(verbose_name='Допустимый интервал для опоздания')),
                ('allowed_interval_for_early_departure',
                 models.DurationField(verbose_name='Допустимый интервал для раннего ухода')),
                ('network',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network')),
            ],
            options={
                'verbose_name': 'Настройка табеля',
                'verbose_name_plural': 'Настройки табеля',
            },
        ),
        migrations.CreateModel(
            name='ShopTabelSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Shop')),
                ('tabel_settings',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TabelSettings')),
            ],
            options={
                'unique_together': {('shop', 'tabel_settings')},
            },
        ),
        migrations.RunPython(add_default_tabel_settings, migrations.RunPython.noop)
    ]
