# Generated by Django 2.2.7 on 2020-10-08 08:50

from django.db import migrations, models
from etc.scripts.fill_calendar import main
import datetime

def fill_calendar(apps, schema_editor):
    Region = apps.get_model('base', 'Region')
    r = Region.objects.first()
    main(
        (datetime.date.today() - datetime.timedelta(days=365)).strftime('%Y.%m.%d'),
        (datetime.date.today() + datetime.timedelta(days=365)).strftime('%Y.%m.%d'),
        r.id,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20201003_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='network',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productionday',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='region',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workerposition',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(fill_calendar),
    ]
