# Generated by Django 2.2.7 on 2020-10-09 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20201003_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='allowed_interval_for_early_departure',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Допустимый интервал для раннего ухода'),
        ),
        migrations.AddField(
            model_name='network',
            name='allowed_interval_for_late_arrival',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Допустимый интервал для опоздания'),
        ),
    ]
