# Generated by Django 2.2.7 on 2020-10-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20201006_0609'),
        ('base', '0057_auto_20201008_0850'),
    ]

    operations = [
    ]
