# Generated by Django 2.2.7 on 2020-10-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_merge_20201014_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='okpo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
