# Generated by Django 2.2.7 on 2020-10-22 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_network_okpo'),
        ('base', '0060_auto_20201016_1340'),
    ]

    operations = [
    ]
