# Generated by Django 2.2.7 on 2020-11-10 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_merge_20201022_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='allowed_geo_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Разрешенная дистанция до магазина при создании отметок (км)'),
        ),
        migrations.AddField(
            model_name='shop',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Долгота'),
        ),
    ]
