# Generated by Django 2.2.7 on 2020-11-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20201110_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='enable_camera_ticks',
            field=models.BooleanField(default=False, verbose_name='Включить отметки по камере в мобильной версии'),
        ),
    ]
