# Generated by Django 2.2.7 on 2020-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20201123_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='crop_work_hours_by_shop_schedule',
            field=models.BooleanField(default=False, verbose_name='Обрезать рабочие часы по времени работы магазина'),
        ),
    ]
