# Generated by Django 2.2.7 on 2020-12-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_merge_20201129_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='dt_to_function_group',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='function_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='base.Group'),
        ),
    ]
