# Generated by Django 2.2.16 on 2020-12-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20201210_0642'),
        ('base', '0069_auto_20201202_0950'),
    ]

    operations = [
    ]
