# Generated by Django 2.2.7 on 2020-12-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20201228_0929'),
        ('base', '0071_merge_20201209_1450'),
    ]

    operations = [
    ]
