# Generated by Django 2.2.16 on 2021-02-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20210121_1307'),
        ('base', '0076_auto_20210118_1156'),
    ]

    operations = [
    ]
