# Generated by Django 2.2.16 on 2021-02-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20210224_1016'),
        ('base', '0078_auto_20210209_0701'),
    ]

    operations = [
    ]
