# Generated by Django 2.2.16 on 2021-02-19 15:26

from django.db import migrations, models
import django.db.models.deletion


def set_breaks(apps, schema_editor):
    Break = apps.get_model('base', 'Break')
    Network = apps.get_model('base', 'Network')
    for n in Network.objects.all():
        n.breaks = Break.objects.create(
            name=f'По умолчанию для сети {n.name}',
            network=n,
            value='[[0, 360, [30]], [360, 540, [30, 30]], [540, 780, [30, 30, 15]]]',
        )
        n.save()



class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20210209_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='breaks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='base.Break', verbose_name='Перерывы по умолчанию'),
        ),
        migrations.RunPython(set_breaks)
    ]
