# Generated by Django 2.2.16 on 2021-02-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20210209_0701'),
        ('base', '0078_merge_20210204_0632'),
        ('base', '0078_auto_20210224_1016'),
    ]

    operations = [
    ]
