# Generated by Django 2.2.16 on 2021-02-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_network_worker_position_default_values'),
        ('base', '0079_merge_20210224_1113'),
    ]

    operations = [
    ]
