# Generated by Django 2.2.16 on 2021-03-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_merge_20210226_1525'),
        ('base', '0081_auto_20210228_0712'),
    ]

    operations = [
    ]
