# Generated by Django 2.2.16 on 2021-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_merge_20210301_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Город'),
        ),
    ]
