# Generated by Django 2.2.16 on 2021-03-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_merge_20210302_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='consider_remaining_hours_in_prev_months_when_calc_norm_hours',
            field=models.BooleanField(default=False, verbose_name='Учитывать неотработанные часы за предыдущие месяца при расчете нормы часов'),
        ),
    ]
