# Generated by Django 2.2.16 on 2021-03-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_shop_city'),
        ('base', '0084_network_show_worker_day_additional_info'),
    ]

    operations = [
    ]
