# Generated by Django 2.2.16 on 2021-04-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_auto_20210423_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='tabel_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tabel_code',
        ),
    ]
