# Generated by Django 2.2.16 on 2021-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20210507_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkconnect',
            options={'verbose_name': 'Связь сетей', 'verbose_name_plural': 'Связи сетей'},
        ),
        migrations.AddField(
            model_name='network',
            name='ignore_parent_code_when_updating_department_via_api',
            field=models.BooleanField(default=False, help_text='Необходимо включить для случаев, когда оргструктура поддерживается вручную', verbose_name='Не учитывать parent_code при изменении подразделения через api'),
        ),
    ]
