# Generated by Django 2.2.16 on 2021-05-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_auto_20210520_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('local', 'Локально'), ('ldap', 'LDAP')], default='local', max_length=10),
        ),
    ]
