# Generated by Django 2.2.16 on 2021-06-21 11:28

from django.db import migrations, models

def drop_views(apps, schema_editor):
    schema_editor.execute("drop view metabase_financial_stat; drop view plan_and_fact_hours; drop view prod_cal; drop view v_mda_users; drop view prod_cal_work_hours;")

def create_views(apps, schema_editor):
    schema_editor.execute("""\
         create or replace view prod_cal_work_hours as
         SELECT date_trunc('month'::text, pd.dt::timestamp with time zone)::date AS dt,
            employee.user_id,
            u.username,
            e.shop_id,
            s.code AS shop_code,
            sum(
                CASE
                    WHEN pd.type::text = 'W'::text THEN 8
                    WHEN pd.type::text = 'S'::text THEN 7
                    WHEN pd.type::text = 'H'::text THEN 0
                    ELSE 0
                END::double precision * COALESCE(wp.hours_in_a_week::integer, 40)::double precision / 40::double precision * e.norm_work_hours::double precision / 100::double precision) AS norm_hours,
           wtn.name as work_type_name
           FROM base_productionday pd
             JOIN base_employment e ON pd.dt >= e.dt_hired AND pd.dt <= e.dt_fired
             JOIN base_employee employee ON e.employee_id = employee.id
             JOIN base_user u ON employee.user_id = u.id
             JOIN base_shop s ON e.shop_id = s.id
             LEFT JOIN timetable_employmentworktype ewt on e.id = ewt.employment_id AND ewt.id = (
                SELECT min(ewt2.id)
                FROM timetable_employmentworktype ewt2
                inner join timetable_worktype wt2 on ewt2.work_type_id = wt2.id
                WHERE e.id = ewt2.employment_id
             )
             LEFT JOIN timetable_worktype wt on ewt.work_type_id = wt.id and wt.shop_id = e.shop_id and wt.dttm_deleted is null
             LEFT JOIN timetable_worktypename wtn on wt.work_type_name_id = wtn.id
             LEFT JOIN base_workerposition wp ON e.position_id = wp.id
          GROUP BY (date_trunc('month'::text, pd.dt::timestamp with time zone)::date), employee.user_id, u.username, e.shop_id, s.code, wtn.name;""")
    schema_editor.execute("""\
        create or replace view v_mda_users as
        SELECT DISTINCT u.id,
                    u.username,
                    u.last_name,
                    u.first_name,
                    u.middle_name,
                    u.email,
                    e.dt_hired,
                    e.dt_fired,
                    e.dttm_deleted IS NULL AND e.dt_hired <= CURRENT_TIMESTAMP::date AND
                    (e.dt_fired IS NULL OR e.dt_fired >= CURRENT_TIMESTAMP::date) AS active,
                    CASE
                        WHEN s.level = 0 THEN 'COMPANY'::text
                        WHEN s.level = 1 THEN 'DIVISION'::text
                        WHEN s.level = 2 THEN 'REGION'::text
                        WHEN s.level = 3 THEN 'SHOP'::text
                        ELSE NULL::text
                        END                                                       AS level,
                    CASE
                        WHEN (
                                (e.dttm_deleted IS NULL AND e.dt_hired <= CURRENT_TIMESTAMP::date AND
                                 (e.dt_fired IS NULL OR e.dt_fired >= CURRENT_TIMESTAMP::date)) and e.id = (
                                select e2.id
                                from base_employment e2
                                         JOIN base_employee employee2 ON e2.employee_id = employee2.id
                                         JOIN base_user u2 ON employee2.user_id = u2.id
                                         JOIN base_shop s2 ON e2.shop_id = s2.id
                                         LEFT JOIN base_workerposition wp2 ON e2.position_id = wp2.id
                                         LEFT JOIN base_group fg2 ON e2.function_group_id = fg2.id
                                         LEFT JOIN base_group g2 ON wp2.group_id = g2.id
                                WHERE s2.id = s.id
                                  and (g2.code::text = 'director'::text OR fg2.code::text = 'director'::text)
                                  and (e2.dttm_deleted IS NULL AND e2.dt_hired <= CURRENT_TIMESTAMP::date AND
                                       (e2.dt_fired IS NULL OR e2.dt_fired >= CURRENT_TIMESTAMP::date))
                                ORDER BY EXISTS(
                                             SELECT wd2.id
                                             FROM timetable_workerday wd2
                                             WHERE wd2.employee_id = employee2.id
                                               AND wd2.dt = now()::date
                                               AND wd2.type in ('M', 'S', 'V')
                                               AND wd2.is_fact is False
                                               AND wd2.is_approved is True
                                         ),
                                         e2.is_visible DESC,
                                         e2.norm_work_hours DESC,
                                         EXISTS(
                                             SELECT ds.id
                                             FROM base_shop ds
                                             WHERE ds.director_id = employee2.user_id
                                         ) DESC,
                                         e2.dt_hired DESC
                                LIMIT 1
                            )
                            ) THEN 'DIR'::text
                        WHEN (
                                not (e.dttm_deleted IS NULL AND e.dt_hired <= CURRENT_TIMESTAMP::date AND
                                     (e.dt_fired IS NULL OR e.dt_fired >= CURRENT_TIMESTAMP::date)) and
                                (g.code::text = 'director'::text OR fg.code::text = 'director'::text)
                            ) THEN 'DIR'::text
                        ELSE 'MANAGER'::text
                        END                                                       AS role,
                    s.name                                                        AS shop_name,
                    s.code                                                        AS shop_code,
                    wp.name                                                       AS position_name,
                    wp.code                                                       AS position_code,
                    g.name                                                        AS position_group_name,
                    g.code                                                        AS position_group_code,
                    fg.name                                                       AS func_group_name,
                    fg.code                                                       AS func_group_code,
                    u.dttm_modified                                               AS user_last_modified,
                    e.dttm_modified                                               AS employment_last_modified,
                    wp.dttm_modified                                              AS position_last_modified,
                    GREATEST(u.dttm_modified, e.dttm_modified, wp.dttm_modified)  AS last_modified,
                    e.code
    FROM base_employment e
             JOIN base_employee employee ON e.employee_id = employee.id
             JOIN base_user u ON employee.user_id = u.id
             JOIN base_shop s ON e.shop_id = s.id
             LEFT JOIN base_workerposition wp ON e.position_id = wp.id
             LEFT JOIN base_group fg ON e.function_group_id = fg.id
             LEFT JOIN base_group g ON wp.group_id = g.id
             LEFT JOIN timetable_workerday wdpa
                       ON employee.id = wdpa.employee_id AND wdpa.dt = now()::date AND wdpa.is_fact = false AND
                          wdpa.is_approved = true
    WHERE True
      AND e.dttm_deleted IS NULL
      AND (s.dttm_deleted IS NULL OR s.dttm_deleted >= (CURRENT_TIMESTAMP - '60 days'::interval))
      AND (s.dt_closed IS NULL OR s.dt_closed >= (CURRENT_TIMESTAMP - '60 days'::interval))
      AND ((e.dt_fired > '2020-10-01'::date AND e.dt_hired < e.dt_fired) OR e.dt_fired is null)
      AND e.dt_hired <= CURRENT_TIMESTAMP::date
      AND (NOT g.code = 'director' OR wp.group_id IS NULL OR g.code = 'director' AND (wdpa.type IS NULL OR (wdpa.type::text <> ALL (ARRAY ['M'::text]))))
      AND s.level = 3
    ;""")

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0105_auto_20210528_0914'),
        ('timetable', '0071_auto_20210517_2043'),
    ]

    operations = [
        migrations.RunPython(drop_views, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='functiongroup',
            name='func',
            field=models.CharField(choices=[('AutoSettings_create_timetable', 'AutoSettings_create_timetable'), ('AutoSettings_set_timetable', 'AutoSettings_set_timetable'), ('AutoSettings_delete_timetable', 'AutoSettings_delete_timetable'), ('AuthUserView', 'AuthUserView'), ('Break', 'Break'), ('Employment', 'Employment'), ('Employee', 'Employee'), ('Employment_auto_timetable', 'Employment_auto_timetable'), ('Employment_timetable', 'Employment_timetable'), ('EmploymentWorkType', 'EmploymentWorkType'), ('ExchangeSettings', 'ExchangeSettings'), ('FunctionGroupView', 'FunctionGroupView'), ('FunctionGroupView_functions', 'FunctionGroupView_functions'), ('LoadTemplate', 'LoadTemplate'), ('LoadTemplate_apply', 'LoadTemplate_apply'), ('LoadTemplate_calculate', 'LoadTemplate_calculate'), ('LoadTemplate_download', 'LoadTemplate_download'), ('LoadTemplate_upload', 'LoadTemplate_upload'), ('Network', 'Network'), ('Notification', 'Notification'), ('OperationTemplate', 'OperationTemplate'), ('OperationTypeName', 'OperationTypeName'), ('OperationType', 'OperationType'), ('OperationTypeRelation', 'OperationTypeRelation'), ('OperationTypeTemplate', 'OperationTypeTemplate'), ('PeriodClients', 'PeriodClients'), ('PeriodClients_indicators', 'PeriodClients_indicators'), ('PeriodClients_put', 'PeriodClients_put'), ('PeriodClients_delete', 'PeriodClients_delete'), ('PeriodClients_upload', 'PeriodClients_upload'), ('PeriodClients_download', 'PeriodClients_download'), ('Receipt', 'Receipt'), ('Group', 'Group'), ('Shop', 'Shop'), ('Shop_stat', 'Shop_stat'), ('Shop_tree', 'Shop_tree'), ('Shop_outsource_tree', 'Shop_outsource_tree'), ('Subscribe', 'Subscribe'), ('TickPoint', 'TickPoint'), ('Timesheet', 'Timesheet'), ('Timesheet_stats', 'Timesheet_stats'), ('User', 'User'), ('User_change_password', 'User_change_password'), ('User_delete_biometrics', 'User_delete_biometrics'), ('WorkerConstraint', 'WorkerConstraint'), ('WorkerDay', 'WorkerDay'), ('WorkerDay_approve', 'WorkerDay_approve'), ('WorkerDay_daily_stat', 'WorkerDay_daily_stat'), ('WorkerDay_worker_stat', 'WorkerDay_worker_stat'), ('WorkerDay_vacancy', 'WorkerDay_vacancy'), ('WorkerDay_change_list', 'WorkerDay_change_list'), ('WorkerDay_copy_approved', 'WorkerDay_copy_approved'), ('WorkerDay_copy_range', 'WorkerDay_copy_range'), ('WorkerDay_duplicate', 'WorkerDay_duplicate'), ('WorkerDay_delete_worker_days', 'WorkerDay_delete_worker_days'), ('WorkerDay_exchange', 'WorkerDay_exchange'), ('WorkerDay_exchange_approved', 'WorkerDay_exchange_approved'), ('WorkerDay_confirm_vacancy', 'WorkerDay_confirm_vacancy'), ('WorkerDay_confirm_vacancy_to_worker', 'WorkerDay_confirm_vacancy_to_worker'), ('WorkerDay_reconfirm_vacancy_to_worker', 'WorkerDay_reconfirm_vacancy_to_worker'), ('WorkerDay_upload', 'WorkerDay_upload'), ('WorkerDay_upload_fact', 'WorkerDay_upload_fact'), ('WorkerDay_download_timetable', 'WorkerDay_download_timetable'), ('WorkerDay_download_tabel', 'WorkerDay_download_tabel'), ('WorkerDay_editable_vacancy', 'WorkerDay_editable_vacancy'), ('WorkerDay_approve_vacancy', 'WorkerDay_approve_vacancy'), ('WorkerDay_change_range', 'WorkerDay_change_range'), ('WorkerDay_request_approve', 'WorkerDay_request_approve'), ('WorkerDay_block', 'WorkerDay_block'), ('WorkerDay_unblock', 'WorkerDay_unblock'), ('WorkerPosition', 'WorkerPosition'), ('WorkTypeName', 'WorkTypeName'), ('WorkType', 'WorkType'), ('WorkType_efficiency', 'WorkType_efficiency'), ('ShopMonthStat', 'ShopMonthStat'), ('ShopMonthStat_status', 'ShopMonthStat_status'), ('ShopSettings', 'ShopSettings'), ('ShopSchedule', 'ShopSchedule'), ('VacancyBlackList', 'VacancyBlackList'), ('Task', 'Task'), ('signout', 'signout'), ('password_edit', 'password_edit'), ('get_worker_day_approves', 'get_worker_day_approves'), ('create_worker_day_approve', 'create_worker_day_approve'), ('delete_worker_day_approve', 'delete_worker_day_approve'), ('get_cashboxes', 'get_cashboxes'), ('get_cashboxes_info', 'get_cashboxes_info'), ('create_cashbox', 'create_cashbox'), ('update_cashbox', 'update_cashbox'), ('delete_cashbox', 'delete_cashbox'), ('get_types', 'get_types'), ('create_work_type', 'create_work_type'), ('edit_work_type', 'edit_work_type'), ('delete_work_type', 'delete_work_type'), ('get_notifications', 'get_notifications'), ('get_notifications2', 'get_notifications2'), ('set_notifications_read', 'set_notifications_read'), ('get_worker_day', 'get_worker_day'), ('delete_worker_day', 'delete_worker_day'), ('request_worker_day', 'request_worker_day'), ('set_worker_day', 'set_worker_day'), ('handle_worker_day_request', 'handle_worker_day_request'), ('get_worker_day_logs', 'get_worker_day_logs'), ('get_cashier_info', 'get_cashier_info'), ('change_cashier_info', 'change_cashier_info'), ('create_cashier', 'create_cashier'), ('get_cashiers_info', 'get_cashiers_info'), ('select_cashiers', 'select_cashiers'), ('get_not_working_cashiers_list', 'get_not_working_cashiers_list'), ('get_cashiers_list', 'get_cashiers_list'), ('change_cashier_status', 'change_cashier_status'), ('set_selected_cashiers', 'set_selected_cashiers'), ('delete_cashier', 'delete_cashier'), ('set_timetable', 'set_timetable'), ('create_timetable', 'create_timetable'), ('delete_timetable', 'delete_timetable'), ('get_cashier_timetable', 'get_cashier_timetable'), ('get_cashiers_timetable', 'get_cashiers_timetable'), ('dublicate_cashier_table', 'dublicate_cashier_table'), ('get_slots', 'get_slots'), ('get_all_slots', 'get_all_slots'), ('get_workers', 'get_workers'), ('get_outsource_workers', 'get_outsource_workers'), ('get_user_urv', 'get_user_urv'), ('upload_urv', 'upload_urv'), ('get_forecast', 'get_forecast'), ('upload_demand', 'upload_demand'), ('upload_timetable', 'upload_timetable'), ('notify_workers_about_vacancy', 'notify_workers_about_vacancy'), ('do_notify_action', 'do_notify_action'), ('get_workers_to_exchange', 'get_workers_to_exchange'), ('exchange_workers_day', 'exchange_workers_day'), ('set_demand', 'set_demand'), ('set_pred_bills', 'set_pred_bills'), ('get_operation_templates', 'get_operation_templates'), ('create_operation_template', 'create_operation_template'), ('update_operation_template', 'update_operation_template'), ('delete_operation_template', 'delete_operation_template'), ('show_vacancy', 'show_vacancy'), ('cancel_vacancy', 'cancel_vacancy'), ('confirm_vacancy', 'confirm_vacancy'), ('get_demand_xlsx', 'get_demand_xlsx'), ('get_department_stats_xlsx', 'get_department_stats_xlsx'), ('get_timetable_xlsx', 'get_timetable_xlsx'), ('get_urv_xlsx', 'get_urv_xlsx'), ('get_tabel', 'get_tabel'), ('get_department', 'get_department'), ('add_department', 'add_department'), ('edit_department', 'edit_department'), ('get_department_list', 'get_department_list'), ('get_department_stats', 'get_department_stats'), ('get_parameters', 'get_parameters'), ('set_parameters', 'set_parameters'), ('get_demand_change_logs', 'get_demand_change_logs'), ('get_table', 'get_table'), ('get_status', 'get_status'), ('get_change_request', 'get_change_request'), ('get_month_stat', 'get_month_stat'), ('get_indicators', 'get_indicators'), ('get_worker_position_list', 'get_worker_position_list'), ('set_worker_restrictions', 'set_worker_restrictions'), ('create_predbills_request', 'create_predbills_request')], max_length=128),
        ),
        migrations.AlterField(
            model_name='employment',
            name='norm_work_hours',
            field=models.FloatField(default=100),
        ),
        migrations.RunPython(create_views, migrations.RunPython.noop),
    ]
