# Generated by Django 2.2.16 on 2021-06-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0110_auto_20210607_2056'),
        ('base', '0106_auto_20210621_1128'),
    ]

    operations = [
    ]
