# Generated by Django 2.2.16 on 2021-07-06 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0074_merge_20210604_1116'),
        ('base', '0112_auto_20210629_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='exchange_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='timetable.ExchangeSettings', verbose_name='Default exchange settings'),
        ),
        migrations.AlterField(
            model_name='network',
            name='accounting_period_length',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Month'), (3, 'Quarter'), (6, 'Half a year'), (12, 'Year')], default=1, verbose_name='Accounting period length'),
        ),
        migrations.AlterField(
            model_name='network',
            name='allow_workers_confirm_outsource_vacancy',
            field=models.BooleanField(default=False, verbose_name='Allow workers confirm outsource vacancy'),
        ),
        migrations.AlterField(
            model_name='network',
            name='allowed_geo_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Allowed geo distance (km)'),
        ),
        migrations.AlterField(
            model_name='network',
            name='allowed_interval_for_early_departure',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Allowed interval for early departure'),
        ),
        migrations.AlterField(
            model_name='network',
            name='allowed_interval_for_late_arrival',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Allowed interval for late_arrival'),
        ),
        migrations.AlterField(
            model_name='network',
            name='breaks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='base.Break', verbose_name='Default breaks'),
        ),
        migrations.AlterField(
            model_name='network',
            name='clean_wdays_on_employment_dt_change',
            field=models.BooleanField(default=False, verbose_name='Clean worker days on employment date change'),
        ),
        migrations.AlterField(
            model_name='network',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='network',
            name='consider_remaining_hours_in_prev_months_when_calc_norm_hours',
            field=models.BooleanField(default=False, verbose_name='Consider remaining hours in previous months when calculating norm hours'),
        ),
        migrations.AlterField(
            model_name='network',
            name='convert_tabel_to',
            field=models.CharField(blank=True, choices=[('xlsx', 'xlsx'), ('pdf', 'PDF')], default='xlsx', max_length=64, null=True, verbose_name='Convert tabel to'),
        ),
        migrations.AlterField(
            model_name='network',
            name='copy_plan_to_fact_crossing',
            field=models.BooleanField(default=False, verbose_name='Copy plan to fact crossing'),
        ),
        migrations.AlterField(
            model_name='network',
            name='create_employment_on_set_or_update_director_code',
            field=models.BooleanField(default=False, verbose_name='Create employment on set or update director code'),
        ),
        migrations.AlterField(
            model_name='network',
            name='crop_work_hours_by_shop_schedule',
            field=models.BooleanField(default=False, verbose_name='Crop work hours by shop schedule'),
        ),
        migrations.AlterField(
            model_name='network',
            name='descrease_employment_dt_fired_in_api',
            field=models.BooleanField(default=False, help_text='Relevant for data received via the api', verbose_name='Descrease employment date fired in api'),
        ),
        migrations.AlterField(
            model_name='network',
            name='download_tabel_template',
            field=models.CharField(choices=[('mts', 'MTSTabelGenerator'), ('t13_custom', 'CustomT13TabelGenerator'), ('aigul', 'AigulTabelGenerator')], default='mts', max_length=64, verbose_name='Download tabel template'),
        ),
        migrations.AlterField(
            model_name='network',
            name='enable_camera_ticks',
            field=models.BooleanField(default=False, verbose_name='Enable camera ticks'),
        ),
        migrations.AlterField(
            model_name='network',
            name='ignore_parent_code_when_updating_department_via_api',
            field=models.BooleanField(default=False, help_text='It must be enabled for cases when the organizational structure is maintained manually', verbose_name='Ignore parent code when updating department via api'),
        ),
        migrations.AlterField(
            model_name='network',
            name='load_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='networks', to='forecast.LoadTemplate', verbose_name='Default load template'),
        ),
        migrations.AlterField(
            model_name='network',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/%Y/%m', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='network',
            name='need_symbol_for_vacancy',
            field=models.BooleanField(default=False, verbose_name='Need symbol for vacancy'),
        ),
        migrations.AlterField(
            model_name='network',
            name='okpo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='OKPO code'),
        ),
        migrations.AlterField(
            model_name='network',
            name='only_fact_hours_that_in_approved_plan',
            field=models.BooleanField(default=False, verbose_name='Count only fact hours that in approved plan'),
        ),
        migrations.AlterField(
            model_name='network',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Primary color'),
        ),
        migrations.AlterField(
            model_name='network',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Secondary color'),
        ),
        migrations.AlterField(
            model_name='network',
            name='settings_values',
            field=models.TextField(default='{}', verbose_name='Settings values'),
        ),
        migrations.AlterField(
            model_name='network',
            name='show_user_biometrics_block',
            field=models.BooleanField(default=False, verbose_name='Show user biometrics block'),
        ),
        migrations.AlterField(
            model_name='network',
            name='show_worker_day_additional_info',
            field=models.BooleanField(default=False, help_text='Displaying information about who last edited a worker day and when, when hovering over the corner', verbose_name='Show worker day additional info'),
        ),
        migrations.AlterField(
            model_name='network',
            name='show_worker_day_tasks',
            field=models.BooleanField(default=False, verbose_name='Show worker day tasks'),
        ),
        migrations.AlterField(
            model_name='network',
            name='timetable_format',
            field=models.CharField(choices=[('cell_format', 'Cells'), ('row_format', 'Rows')], default='cell_format', max_length=64, verbose_name='Timetable format'),
        ),
        migrations.AlterField(
            model_name='network',
            name='worker_position_default_values',
            field=models.TextField(default='{}', verbose_name='Worker position default values'),
        ),
    ]
