# Generated by Django 2.2.16 on 2021-07-12 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_auto_20210629_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='fines_settings',
            field=models.TextField(default='{}', verbose_name='Fines settings'),
        ),
    ]
