# Generated by Django 2.2.16 on 2021-07-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0113_auto_20210706_0939'),
        ('base', '0113_auto_20210712_0853'),
    ]

    operations = [
    ]
