# Generated by Django 2.2.16 on 2021-08-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0117_auto_20210803_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='max_plan_diff_in_seconds',
            field=models.PositiveIntegerField(default=18000, verbose_name='Max difference between the start or end time to "pull" to the planned work day'),
        ),
        migrations.AddField(
            model_name='network',
            name='max_work_shift_seconds',
            field=models.PositiveIntegerField(default=57600, verbose_name='Maximum shift length (in seconds)'),
        ),
        migrations.AddField(
            model_name='network',
            name='skip_leaving_tick',
            field=models.BooleanField(default=False, verbose_name='Skip the creation of a departure mark if more than the Maximum shift length has passed since the opening of the previous shift'),
        ),
    ]
