# Generated by Django 2.2.16 on 2021-08-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0117_auto_20210803_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='max_plan_diff_in_seconds',
            field=models.PositiveIntegerField(default=18000, verbose_name='Макс. разность между временем начала или окончания для "притягивания" к плановому рабочему дню'),
        ),
        migrations.AddField(
            model_name='network',
            name='max_work_shift_seconds',
            field=models.PositiveIntegerField(default=86400, verbose_name='Максимальная длина смены (в секундах)'),
        ),
        migrations.AddField(
            model_name='network',
            name='skip_leaving_tick',
            field=models.BooleanField(default=False, verbose_name='Пропускать создание отметки об уходе, если с момент открытия предыдущей смены прошло более Максимальной длины смены'),
        ),
    ]
