# Generated by Django 2.2.16 on 2021-08-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0117_auto_20210819_0925'),
        ('base', '0117_auto_20210818_0735'),
        ('base', '0117_auto_20210823_1411'),
    ]

    operations = [
    ]
