# Generated by Django 2.2.16 on 2021-09-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_network_shop_default_values'),
        ('base', '0117_auto_20210817_2207'),
    ]

    operations = [
    ]
