# Generated by Django 2.2.16 on 2021-09-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0120_network_add_users_from_excel'),
        ('base', '0120_merge_20210908_1158'),
    ]

    operations = [
    ]
