# Generated by Django 2.2.16 on 2021-09-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0122_auto_20210921_0538'),
        ('base', '0123_merge_20210922_2047'),
    ]

    operations = [
    ]
