# Generated by Django 2.2.16 on 2021-10-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0123_merge_20210927_1136'),
        ('base', '0123_merge_20211001_0837'),
    ]

    operations = [
    ]
