# Generated by Django 2.2.16 on 2021-08-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0117_auto_20210817_2207'),
        ('base', '0123_auto_20210821_1823'),
    ]

    operations = [
    ]
