# Generated by Django 2.2.24 on 2021-09-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_merge_20210924_1316'),
        ('base', '0124_auto_20210927_0952'),
    ]

    operations = [
    ]
