# Generated by Django 2.2.16 on 2021-08-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0119_network_shop_default_values'),
        ('base', '0125_auto_20210822_1242'),
    ]

    operations = [
    ]
