# Generated by Django 2.2.16 on 2021-09-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0121_merge_20210908_1315'),
        ('base', '0127_auto_20210903_1153'),
    ]

    operations = [
    ]
