# Generated by Django 2.2.24 on 2021-10-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0123_merge_20211001_0837'),
        ('base', '0135_auto_20210930_1556'),
    ]

    operations = [
    ]
