# Generated by Django 2.2.16 on 2021-10-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_merge_20211008_1333'),
        ('base', '0137_merge_20211006_0939'),
    ]

    operations = [
    ]
