# Generated by Django 2.2.24 on 2021-10-19 10:49

from django.db import migrations


def add_permissions(apps, schema_editor):
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    Group = apps.get_model('base', 'Group')

    func_groups = (
        ('Reports_pivot_tabel', ['GET']),
    )
    groups = Group.objects.all()
    for group in groups:
        for func, methods in func_groups:
            for m in methods:
                FunctionGroup.objects.get_or_create(
                    group=group,
                    method=m,
                    func=func,
                    defaults=dict(
                        access_type='all',
                    )
                )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0139_auto_20211014_0611'),
    ]

    operations = [
        migrations.RunPython(add_permissions, migrations.RunPython.noop)
    ]
