# Generated by Django 2.2.24 on 2021-10-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0140_auto_20211019_1049'),
        ('base', '0140_auto_20211015_0911'),
    ]

    operations = [
    ]
