# Generated by Django 3.2.9 on 2021-11-22 04:37

import re
from django.db import migrations

def add_load_template_perms(apps, schema_editor):
    Group = apps.get_model('base', 'Group')
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    for group in Group.objects.all():
        if group and re.search(r'(.*)?админ(.*)?', group.name, re.IGNORECASE) and\
            not re.search(r'(.*)?аутсорс(.*)?', group.name, re.IGNORECASE):
            FunctionGroup.objects.get_or_create(
                group=group,
                func='Shop_load_template',
                method='POST',
                defaults=dict(
                    access_type='A',
                ),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0146_auto_20211117_1414'),
    ]

    operations = [
        migrations.RunPython(add_load_template_perms, migrations.RunPython.noop),
    ]
