# Generated by Django 3.2.9 on 2021-11-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0147_auto_20211118_0502'),
        ('base', '0147_group_allowed_tabs'),
    ]

    operations = [
    ]
