# Generated by Django 3.2.9 on 2021-11-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0148_network_api_timesheet_lines_group_by'),
        ('base', '0149_auto_20211124_2047'),
    ]

    operations = [
    ]
