# Generated by Django 3.2.9 on 2021-11-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0147_auto_20211122_0544'),
        ('base', '0149_merge_20211119_0939'),
    ]

    operations = [
    ]
