# Generated by Django 3.2.9 on 2021-11-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0152_network_trust_tick_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='show_cost_for_inner_vacancies',
            field=models.BooleanField(default=False, verbose_name='Отображать поле "стоимость работ" для внутренних вакансий'),
        ),
    ]
