# Generated by Django 3.2.9 on 2021-12-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0157_auto_20211203_0608'),
        ('base', '0157_network_rebuild_timetable_min_delta'),
    ]

    operations = [
    ]
