# Generated by Django 3.2.9 on 2021-12-07 07:00

from django.db import migrations

def add_permission(apps, schema_editor):
    Group = apps.get_model('base', 'Group')
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    for g in Group.objects.all():
        FunctionGroup.objects.update_or_create(
            group=g,
            func='Shop_internal_tree',
            method='GET',
            defaults={
                'access_type': 'A',
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0158_merge_20211203_1245'),
    ]

    operations = [
        migrations.RunPython(add_permission, migrations.RunPython.noop),
    ]
