# Generated by Django 3.2.9 on 2021-12-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0153_auto_20211216_1423'),
        ('base', '0162_alter_functiongroup_func'),
    ]

    operations = [
    ]
