# Generated by Django 3.2.9 on 2022-02-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0166_merge_20220127_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='analytics_type',
            field=models.CharField(choices=[('metabase', 'Метабейз'), ('custom_iframe', 'Кастомный iframe (из json настройки analytics_iframe)'), ('power_bi_embed', 'Power BI через получение embed токена')], default='metabase', max_length=32, verbose_name='Вид аналитики'),
        ),
    ]
