# Generated by Django 3.2.9 on 2022-02-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0170_auto_20220222_1145'),
        ('base', '0170_sawhsettingsmapping_employees'),
    ]

    operations = [
    ]
