# Generated by Django 3.2.9 on 2022-03-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0172_alter_functiongroup_func'),
        ('base', '0173_auto_20220304_1236'),
    ]

    operations = [
    ]
