# Generated by Django 3.2.9 on 2022-04-19 10:18

from django.db import migrations


def migrate_pobeda_sawh_settings(apps, schema_editor):
    Network = apps.get_model('base', 'Network')
    SAWHSettings = apps.get_model('base', 'SAWHSettings')
    SAWHSettingsMapping = apps.get_model('base', 'SAWHSettingsMapping')
    AllowedSawhSetting = apps.get_model('base', 'AllowedSawhSetting')
    WorkerPosition = apps.get_model('base', 'WorkerPosition')
    Employment = apps.get_model('base', 'Employment')
    pobeda_network = Network.objects.filter(name='Победа').first()

    if pobeda_network:
        movings = (
            ('Победа ДМ', 'Победа ДМ 2022'),
            ('Победа ПУ ПП УФ', 'Победа ПУ, ПП, УФ 2022'),
        )
        for move_from, move_to in movings:
            move_from_obj = SAWHSettings.objects.filter(name=move_from, network=pobeda_network).first()
            move_to_obj = SAWHSettings.objects.filter(name=move_to, network=pobeda_network).first()
            if move_from_obj and move_to_obj:
                SAWHSettingsMapping.objects.filter(
                    sawh_settings=move_from_obj,
                ).update(
                    work_hours_by_months=move_from_obj.work_hours_by_months,
                    sawh_settings=move_to_obj,
                )

        to_remove = (
            'Победа ЗДМ',
            'Победа ДМ',
            'Победа ПУ ПП УФ',
        )
        SAWHSettings.objects.filter(name__in=to_remove, network=pobeda_network).delete()

        renamings = (
            ('Победа ДМ 2022', 'ДМ', 'dm'),
            ('Победа ПУ, ПП, УФ 2022', 'ПУ ПП УФ', 'pu_pp_uf'),
            ('Победа ЗДМ 2022 1', 'ЗДМ 1', 'zdm_1'),
            ('Победа ЗДМ 2022 2', 'ЗДМ 2', 'zdm_2'),
        )

        for rename_from, rename_to, code in renamings:
            rename_from_obj = SAWHSettings.objects.filter(
                name=rename_from,
                network=pobeda_network,
            ).first()
            if rename_from_obj:
                SAWHSettingsMapping.objects.filter(
                    sawh_settings=rename_from_obj,
                    year=2022,
                ).update(
                    work_hours_by_months=rename_from_obj.work_hours_by_months,
                )
                rename_from_obj.name = rename_to
                rename_from_obj.code = code
                rename_from_obj.work_hours_by_months = None
                rename_from_obj.save()

        allowed = (
            ('Заместитель директора магазина', ('zdm_1', 'zdm_2'))
        )
        for position_name, *sawh_settings_codes in allowed:
            for position in WorkerPosition.objects.filter(name=position_name, network=pobeda_network):
                AllowedSawhSetting.objects.bulk_create(AllowedSawhSetting(
                    position=position,
                    sawh_settings=sawh_settings
                ) for sawh_settings in SAWHSettings.objects.filter(code__in=sawh_settings_codes))

        move_from_employee_to_employment = (
            'zdm_1',
            'zdm_2',
        )
        for sawh_settings_code in move_from_employee_to_employment:
            sawh_setting = SAWHSettings.objects.filter(code=sawh_settings_code, network=pobeda_network).first()
            if sawh_setting:
                Employment.objects.filter(
                    employee_id__in=SAWHSettingsMapping.objects.filter(
                        sawh_settings=sawh_setting).values_list('employees__id', flat=True)
                ).update(
                    sawh_settings=sawh_setting,
                )
                SAWHSettingsMapping.employees.through.objects.filter(
                    sawhsettingsmapping__sawh_settings=sawh_setting).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0173_auto_20220418_2301'),
    ]

    operations = [
        migrations.RunPython(migrate_pobeda_sawh_settings, migrations.RunPython.noop),
    ]
