# Generated by Django 3.2.9 on 2022-04-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0173_auto_20220418_2301'),
        ('base', '0174_merge_20220330_1321'),
    ]

    operations = [
    ]
