# Generated by Django 3.2.9 on 2022-04-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0174_auto_20220419_1018'),
        ('base', '0175_merge_20220419_0019'),
    ]

    operations = [
    ]
