# Generated by Django 3.2.9 on 2022-08-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0170_network_show_checkbox_for_inspection_version'),
        ('base', '0177_merge_20220421_2257'),
    ]

    operations = [
    ]
