# Generated by Django 3.2.9 on 2022-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0180_auto_20220916_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='use_internal_exchange',
            field=models.BooleanField(default=True, verbose_name='Use internal exchange'),
        ),
    ]
