# Generated by Django 3.2.9 on 2022-10-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0181_auto_20220926_1207'),
        ('base', '0181_network_use_internal_exchange'),
    ]

    operations = [
    ]
