# Generated by Django 3.2.9 on 2022-10-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0182_merge_20221006_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='use_internal_exchange',
            field=models.BooleanField(default=True, help_text='Regulates the action on the vacancy due to the exchange or natural', verbose_name='Use internal exchange'),
        ),
    ]
