# Generated by Django 3.2.9 on 2022-11-09 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0186_network_show_closed_shops_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='allowed_interval_for_late_departure',
            field=models.DurationField(default=datetime.timedelta(seconds=900), verbose_name='Allowed interval for late departure'),
        ),
    ]
