# Generated by Django 3.2.9 on 2023-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0191_merge_20221221_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='show_restrict_editing_shifts_button',
            field=models.BooleanField(default=False, verbose_name='Show restrict editing shifts button'),
        ),
    ]
