# Generated by Django 4.1.7 on 2023-03-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0194_alter_network_forbid_edit_work_days_came_through_integration_and_more'),
        ('base', '0194_auto_20230222_0827'),
    ]

    operations = [
    ]
