# Generated by Django 2.2.7 on 2019-12-23 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_fill_worktypename'),
    ]

    operations = [
        migrations.RunSQL(
            'update timetable_worktype as o set work_type_name_id =  n.id from timetable_worktypename n where o.name=n.name'),
    ]
