# Generated by Django 2.2.7 on 2020-02-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20200205_0751'),
    ]

    operations = [

        migrations.RunSQL("update timetable_worktypename set code=null where code=''"),
        migrations.AlterField(
            model_name='worktypename',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
