# Generated by Django 2.2.7 on 2020-02-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200110_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktypename',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worktypename',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
