# Generated by Django 2.2.7 on 2020-03-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20200206_0648'),
    ]

    operations = [
       migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='worker_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_day_details', to='timetable.WorkerDay'),
        ),
    ]
