# Generated by Django 2.2.7 on 2020-03-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_workerday_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='parent_worker_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='timetable.WorkerDay'),
        ),
    ]
