# Generated by Django 2.2.7 on 2020-04-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20200402_0851'),
        ('timetable', '0012_auto_20200330_1059'),
    ]

    operations = [
    ]
