# Generated by Django 2.2.7 on 2020-04-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20200409_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_day_details', related_query_name='worker_day_details', to='base.Event'),
        ),
    ]
