# Generated by Django 2.2.7 on 2020-05-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_auto_20200430_1405'),
        ('timetable', '0020_auto_20200429_0942'),
    ]

    operations = [
    ]
