# Generated by Django 2.2.7 on 2020-06-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0025_auto_20200529_0735'),
        ('timetable', '0025_auto_20200513_1801'),
    ]

    operations = [
    ]
