# Generated by Django 2.2.7 on 2020-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_merge_20200608_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangesettings',
            name='exclude_positions',
            field=models.ManyToManyField(blank=True, to='base.WorkerPosition'),
        ),
    ]
