# Generated by Django 2.2.7 on 2020-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0026_merge_20200608_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='dt',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='workerday',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
