# Generated by Django 2.2.7 on 2020-07-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_auto_20200629_0902'),
        ('timetable', '0027_auto_20200709_0858'),
    ]

    operations = [
    ]
