# Generated by Django 2.2.7 on 2020-07-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0027_auto_20200629_0902'),
        ('timetable', '0027_auto_20200702_1318'),
    ]

    operations = [
    ]
