# Generated by Django 2.2.7 on 2020-08-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0028_merge_20200714_1344'),
        ('timetable', '0028_merge_20200714_1147'),
    ]

    operations = [
    ]
