# Generated by Django 2.2.7 on 2020-09-14 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0032_auto_20200904_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='dt',
            field=models.DateField(),
        ),
        migrations.AlterIndexTogether(
            name='workerday',
            index_together={('dt', 'worker')},
        ),
    ]
