# Generated by Django 2.2.7 on 2020-09-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0033_shopmonthstat_is_approved'),
        ('timetable', '0033_auto_20200914_0621'),
    ]

    operations = [
    ]
