# Generated by Django 2.2.7 on 2020-10-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0034_merge_20200925_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='parent_worker_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='timetable.WorkerDay'),
        ),
    ]
