# Generated by Django 2.2.7 on 2020-10-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0035_auto_20201003_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecords',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employmentworktype',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exchangesettings',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopmonthstat',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userweekdayslot',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workerconstraint',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workerday',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worktype',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='worktypename',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
