# Generated by Django 2.2.7 on 2020-11-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_merge_20201022_0137'),
        ('timetable', '0037_shopmonthstat_predict_needs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDayPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CU', 'Создание/Редактирование'), ('D', 'Удаление'), ('A', 'Подтверждение')], max_length=2, verbose_name='Действие')),
                ('graph_type', models.CharField(choices=[('P', 'План'), ('F', 'Факт')], max_length=1, verbose_name='Тип графика')),
                ('wd_type', models.CharField(choices=[('H', 'Выходной'), ('W', 'Рабочий день'), ('V', 'Отпуск'), ('S', 'Больничный лист'), ('Q', 'Квалификация'), ('A', 'Неявка до выяснения обстоятельств'), ('M', 'Б/л по беременноси и родам'), ('T', 'Командировка'), ('O', 'Другое'), ('D', 'Удален'), ('E', 'Пусто'), ('HW', 'Работа в выходной день'), ('RA', 'Прогул на основании акта'), ('EV', 'Доп. отпуск'), ('TV', 'Учебный отпуск'), ('SV', 'Отпуск за свой счёт'), ('ST', 'Отпуск за свой счёт по уважительной причине'), ('G', 'Гос. обязанности'), ('HS', 'Спец. выходной'), ('MC', 'Отпуск по уходу за ребёнком до 3-х лет'), ('C', 'Выходные дни по уходу')], max_length=2, verbose_name='Тип дня')),
            ],
            options={
                'verbose_name': 'Разрешение для рабочего дня',
                'verbose_name_plural': 'Разрешения для рабочего дня',
                'ordering': ('action', 'graph_type', 'wd_type'),
                'unique_together': {('action', 'graph_type', 'wd_type')},
            },
        ),
        migrations.CreateModel(
            name='GroupWorkerDayPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('limit_days_in_past', models.PositiveSmallIntegerField(blank=True, help_text='Если null - нет ограничений, если n - можно выполнять действие только n последних дней', null=True, verbose_name='Ограничение на дни в прошлом')),
                ('limit_days_in_future', models.PositiveSmallIntegerField(blank=True, help_text='Если null - нет ограничений, если n - можно выполнять действие только n будущих дней', null=True, verbose_name='Ограничение на дни в будущем')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Group', verbose_name='Группа доступа')),
                ('worker_day_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.WorkerDayPermission', verbose_name='Разрешение для рабочего дня')),
            ],
            options={
                'verbose_name': 'Разрешение группы для рабочего дня',
                'verbose_name_plural': 'Разрешения группы для рабочего дня',
                'unique_together': {('group', 'worker_day_permission')},
            },
        ),
    ]
