# Generated by Django 2.2.7 on 2020-12-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0043_auto_20201201_2000'),
        ('timetable', '0042_auto_20201207_2248'),
    ]

    operations = [
    ]
