# Generated by Django 2.2.7 on 2021-01-20 09:47

from django.db import migrations


def add_timetable_plan_and_fact_hours(apps, schema_editor):
    pass


def drop_timetable_plan_and_fact_hours(apps, schema_editor):
    schema_editor.execute("drop view if exists timetable_plan_and_fact_hours;")


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0044_merge_20201209_1450'),
    ]

    operations = [
        migrations.RunPython(add_timetable_plan_and_fact_hours, drop_timetable_plan_and_fact_hours)
    ]
