# Generated by Django 2.2.16 on 2021-02-27 19:18

from django.db import migrations, models


def fill_dt(apps, schema_editor):
    AttendanceRecords = apps.get_model('timetable', 'AttendanceRecords')
    AttendanceRecords.objects.all().update(
        dt=models.Subquery(
            AttendanceRecords.objects.filter(
                id=models.OuterRef('id')
            ).values('dttm__date')[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0049_auto_20210225_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecords',
            name='dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(fill_dt, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendancerecords',
            name='dt',
            field=models.DateField(),
        ),
    ]
