# Generated by Django 2.2.16 on 2021-02-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0049_prodcal'),
        ('timetable', '0049_auto_20210225_1223'),
    ]

    operations = [
    ]
