# Generated by Django 2.2.16 on 2021-03-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0054_auto_20210318_0512'),
        ('timetable', '0054_auto_20210316_1316'),
    ]

    operations = [
    ]
