# Generated by Django 2.2.16 on 2021-03-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0054_auto_20210316_1316'),
        ('timetable', '0055_auto_20210315_1825'),
    ]

    operations = [
    ]
