# Generated by Django 2.2.16 on 2021-03-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0051_merge_20210302_0940'),
        ('timetable', '0056_merge_20210323_1206'),
    ]

    operations = [
    ]
