# Generated by Django 2.2.16 on 2021-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0054_workerday_is_protected'),
        ('timetable', '0057_merge_20210324_0942'),
        ('timetable', '0055_merge_20210322_0639'),
    ]

    operations = [
    ]
