# Generated by Django 2.2.16 on 2021-04-30 12:22

import django.db.models.deletion
from django.db import migrations, models


def add_outsource_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0065_attendancerecords_employee'),
    ]

    operations = [
        migrations.RunPython(add_outsource_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='worktype',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_types', to='base.Shop'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_types', to='timetable.WorkTypeName'),
        ),
    ]
