# Generated by Django 2.2.16 on 2021-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_auto_20210430_1143'),
        ('timetable', '0065_attendancerecords_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='outsources',
            field=models.ManyToManyField(help_text='Аутсорс компании, которые могут откликнуться на данную вакансию', to='base.Network'),
        ),
    ]
