# Generated by Django 2.2.16 on 2021-05-13 09:20

from django.db import migrations


def update_plan_and_fact_hours(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0068_merge_20210505_0623'),
    ]

    operations = [
        migrations.RunPython(update_plan_and_fact_hours, migrations.RunPython.noop),
    ]
