# Generated by Django 2.2.16 on 2021-05-26 21:30

from django.db import migrations


def add_WorkerDay_generate_upload_example_perms(apps, schema_editor):
    groups = ['admin', 'director', 'urs', 'worker', 'controller']
    Group = apps.get_model('base', 'Group')
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    for group_code in groups:
        group = Group.objects.filter(code=group_code).first()
        if group:
            FunctionGroup.objects.get_or_create(
                group=group,
                func='WorkerDay_generate_upload_example',
                method='GET',
                defaults=dict(
                    access_type='A',
                )
            )


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0071_auto_20210517_2043'),
    ]

    operations = [
        migrations.RunPython(add_WorkerDay_generate_upload_example_perms, migrations.RunPython.noop),
    ]
