# Generated by Django 2.2.16 on 2021-05-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0072_attendancerecords_terminal'),
        ('timetable', '0072_auto_20210526_2130'),
    ]

    operations = [
    ]
