# Generated by Django 2.2.16 on 2021-06-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0073_merge_20210531_1255'),
        ('timetable', '0072_timesheet'),
    ]

    operations = [
    ]
