# Generated by Django 2.2.16 on 2021-08-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0076_workerday_closest_plan_approved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerday',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='workerday',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, type__in=['W', 'Q', 'T']), fields=('dt', 'employee', 'is_fact', 'is_approved'), name='unique_dt_employee_is_fact_is_approved_if_not_workday'),
        ),
    ]
