# Generated by Django 2.2.16 on 2021-08-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0079_auto_20210811_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerday',
            name='outsources',
        ),
    ]
