# Generated by Django 2.2.16 on 2021-08-21 18:23

from django.db import migrations


def add_get_worker_day_type_perms(apps, schema_editor):
    Group = apps.get_model('base', 'Group')
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    FunctionGroup.objects.bulk_create(
        FunctionGroup(
            group=g,
            func='WorkerDayType',
            method='GET',
            access_type='A',
        ) for g in Group.objects.all()
    )


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0083_auto_20210819_2215'),
    ]

    operations = [
        migrations.RunPython(add_get_worker_day_type_perms, migrations.RunPython.noop),
    ]
