# Generated by Django 2.2.16 on 2021-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0125_auto_20210822_1242'),
        ('timetable', '0084_auto_20210821_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdaytype',
            name='is_reduce_norm',
            field=models.BooleanField(default=False, verbose_name='Снижает ли норму часов (отпуска, больничные и тд)'),
        ),
        migrations.AlterField(
            model_name='workerdaytype',
            name='is_work_hours',
            field=models.BooleanField(default=False, help_text='Если False, то не учитывается в сумме рабочих часов в статистике и не идет в белый табель', verbose_name='Считать ли в сумму рабочих часов'),
        ),
        migrations.AlterField(
            model_name='workerdaytype',
            name='show_stat_in_days',
            field=models.BooleanField(default=False, verbose_name='Отображать в статистике по сотрудникам количество дней отдельно для этого типа'),
        ),
        migrations.AlterField(
            model_name='workerdaytype',
            name='show_stat_in_hours',
            field=models.BooleanField(default=False, verbose_name='Отображать в статистике по сотрудникам сумму часов отдельно для этого типа'),
        ),
    ]
