# Generated by Django 2.2.16 on 2021-10-18 05:10

from django.db import migrations

def replace_view_plan_and_fact_hours(apps, schema_editor):
    schema_editor.execute("""
        DROP VIEW IF EXISTS timetable_plan_and_fact_hours CASCADE;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0091_auto_20210930_1556'),
        ('base', '0140_auto_20211015_0911'),
    ]

    operations = [
        migrations.RunPython(replace_view_plan_and_fact_hours, migrations.RunPython.noop)
    ]
