# Generated by Django 2.2.16 on 2021-10-20 12:16

from django.db import migrations

def fix_vacancy(apps, schema_editor):
    WorkerDay = apps.get_model('timetable', 'WorkerDay')
    WorkerDay.objects.filter(
        type__is_work_hours=False,
    ).update(
        is_vacancy=False,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0092_auto_20211018_0510'),
    ]

    operations = [
        migrations.RunPython(fix_vacancy, migrations.RunPython.noop),
    ]
