# Generated by Django 2.2.24 on 2021-10-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0095_merge_20211020_0037'),
        ('timetable', '0093_auto_20211020_1216'),
    ]

    operations = [
    ]
