# Generated by Django 2.2.24 on 2021-10-21 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0143_auto_20211021_2126'),
        ('timetable', '0096_merge_20211020_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktypename',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Используется при формировании табеля для получения должности по типу работ, если включена настройка"Получать должность по типу работ при формировании фактического табеля"', null=True, on_delete=django.db.models.deletion.PROTECT, to='base.WorkerPosition', verbose_name='С какой должностью соотносится тип работ'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='timesheet_type',
            field=models.CharField(choices=[('F', 'Fact'), ('M', 'Main'), ('A', 'Additional')], max_length=32, verbose_name='Тип табеля'),
        ),
    ]
