# Generated by Django 2.2.16 on 2021-11-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0094_auto_20211101_1555'),
        ('timetable', '0101_merge_20211029_1404'),
    ]

    operations = [
    ]
