# Generated by Django 2.2.16 on 2021-11-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0095_auto_20211109_0547'),
        ('timetable', '0103_auto_20211101_2214'),
    ]

    operations = [
    ]
