# Generated by Django 2.2.16 on 2021-11-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0104_merge_20211109_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaytype',
            name='allowed_additional_types',
            field=models.ManyToManyField(blank=True, help_text='Например, если необходимо разрешить создание рабочих дней в отпуск, то для типа дня "Отпуск" нужно добавить в это поле тип дня "Рабочий день', related_name='allowed_as_additional_for', to='timetable.WorkerDayType', verbose_name='Типы дней, которые можно добавлять одновременно с текущим типом дня (только для нерабочих типов дней)'),
        ),
        migrations.AddField(
            model_name='workerdaytype',
            name='has_details',
            field=models.BooleanField(default=False, verbose_name='Есть детали рабочего дня'),
        ),
    ]
