# Generated by Django 3.2.9 on 2021-12-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0108_auto_20211126_0857'),
        ('timetable', '0108_auto_20211201_1312'),
    ]

    operations = [
    ]
