# Generated by Django 3.2.9 on 2021-12-01 05:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0108_auto_20211126_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость работ за час'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='preliminary_cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Предварительная стоимость работ за час'),
        ),
    ]
