# Generated by Django 3.2.9 on 2022-02-03 13:19

from django.db import migrations


def delete_worker_day_details_for_non_workday_types(apps, schema_editor):
    WorkerDayCashboxDetails = apps.get_model('timetable', 'WorkerDayCashboxDetails')
    WorkerDayCashboxDetails.objects.exclude(
        worker_day__type='W',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0111_auto_20211216_0539'),
    ]

    operations = [
        migrations.RunPython(delete_worker_day_details_for_non_workday_types, migrations.RunPython.noop),
    ]
