# Generated by Django 3.2.9 on 2022-03-30 12:51

from django.db import migrations, models
import django.db.models.deletion
import src.common.mixins.bulk_update_or_create


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0172_alter_functiongroup_func'),
        ('timetable', '0117_auto_20220321_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaytype',
            name='subtract_breaks',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('dt_max_hours', models.DurationField(blank=True, null=True)),
                ('restriction_type', models.PositiveSmallIntegerField(choices=[(1, 'Максимальное количество часов на одну дату у сотрудника')], default=1)),
                ('is_vacancy', models.NullBooleanField(default=None, verbose_name='None -- для любой смены (осн. или доп.), True -- только для доп. смен, False -- только для осн. смен')),
                ('employment_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.workerposition')),
                ('work_type_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.worktypename')),
                ('work_type_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.workerposition')),
                ('worker_day_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.workerdaytype')),
            ],
            options={
                'verbose_name': 'Ограничение',
                'verbose_name_plural': 'Ограничения',
            },
            bases=(src.common.mixins.bulk_update_or_create.BatchUpdateOrCreateModelMixin, models.Model),
        ),
    ]
