# Generated by Django 3.2.9 on 2022-03-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0118_auto_20220330_1251'),
        ('timetable', '0118_merge_0117_auto_20220225_1018_0117_auto_20220321_0923'),
    ]

    operations = [
    ]
