# Generated by Django 3.2.9 on 2022-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0125_manual_view_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmonthstat',
            options={'verbose_name': 'Статистика по магазину за месяц', 'verbose_name_plural': 'Статистики по мгазинам за месяц'},
        ),
        migrations.AlterField(
            model_name='workerdaytype',
            name='code',
            field=models.CharField(help_text='Первичный ключ', max_length=64, primary_key=True, serialize=False, verbose_name='Код'),
        ),
    ]
