# Generated by Django 3.2.9 on 2022-11-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0126_auto_20221116_0857'),
        ('timetable', '0126_auto_20221118_1206'),
    ]

    operations = [
    ]
