# Generated by Django 3.2.9 on 2022-12-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0127_merge_0126_auto_20221116_0857_0126_auto_20221118_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkerdaypermission',
            name='allow_approve_first',
            field=models.BooleanField(default=True, help_text="Orteka-specific. Turn off to forbid approving days that don't have parent_worker_day.", verbose_name='Allow approve first'),
        ),
    ]
