# Generated by Django 3.2.9 on 2022-12-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0129_merge_0128_auto_20221205_0833_0128_auto_20221205_1331'),
        ('timetable', '0129_merge_0128_auto_20221205_0833_0128_auto_20221206_2216'),
    ]

    operations = [
    ]
