# Generated by Django 4.1.7 on 2023-09-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0133_workerday_dt_not_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktypename',
            name='availability_on_external_exchange',
            field=models.BooleanField(default=True, help_text='Администратор торговой сети может выбрать какие должности будут отображаться на внешней бирже смен для внешних подрядчиков.', verbose_name='Доступность на внешней бирже'),
        ),
    ]
