# Generated by Django 2.2.7 on 2020-02-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200129_0820'),
        ('base', '0005_auto_20200123_1409'),
    ]

    operations = [
    ]
