# Generated by Django 2.2.7 on 2020-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20200408_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('vacancy', 'Вакансия'), ('timetable', 'Изменения в расписании')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='type',
            field=models.CharField(choices=[('vacancy', 'Вакансия'), ('timetable', 'Изменения в расписании')], max_length=20),
        ),
    ]
