# Generated by Django 2.2.7 on 2020-04-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200407_0803'),
        ('base', '0022_user_lang'),
    ]

    operations = [
    ]
