# Generated by Django 2.2.7 on 2020-04-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20200427_1146'),
        ('base', '0023_auto_20200428_1454'),
    ]

    operations = [
    ]
