# Generated by Django 2.2.7 on 2020-05-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20200430_1405'),
        ('base', '0026_merge_20200506_1043'),
    ]

    operations = [
    ]
