# Generated by Django 2.2.7 on 2020-06-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20200514_0900'),
        ('base', '0030_auto_20200529_0735'),
    ]

    operations = [
    ]
