# Generated by Django 2.2.7 on 2020-06-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20200609_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerposition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Group'),
        ),
    ]
