# Generated by Django 2.2.7 on 2020-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_workerposition_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='network',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
