# Generated by Django 2.2.7 on 2020-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20200722_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='settings_values',
            field=models.TextField(default='{}'),
        ),
    ]
