# Generated by Django 2.2.7 on 2020-07-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_migrate_tm_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='tm_shop_closes',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='tm_shop_opens',
        ),
    ]
