# Generated by Django 2.2.7 on 2020-07-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20200730_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tm_close_dict',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tm_open_dict',
            field=models.TextField(default='{}'),
        ),
    ]
