# Generated by Django 2.2.7 on 2020-08-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_merge_20200809_1955'),
        ('base', '0045_auto_20200731_1423'),
    ]

    operations = [
    ]
