# Generated by Django 2.2.7 on 2020-08-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_merge_20200804_1043'),
        ('base', '0046_merge_20200811_0933'),
    ]

    operations = [
    ]
