# Generated by Django 2.2.7 on 2020-08-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20200813_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='network',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
