# Generated by Django 2.2.7 on 2020-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_merge_20200813_1105'),
        ('base', '0047_auto_20200813_1407'),
    ]

    operations = [
    ]
