# Generated by Django 2.2.7 on 2020-08-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20200814_0820'),
        ('base', '0048_merge_20200813_1420'),
        ('base', '0047_auto_20200823_1414'),
    ]

    operations = [
    ]
