# Generated by Django 2.2.7 on 2020-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20200904_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='area',
            field=models.FloatField(default=0),
        ),
    ]
