# Generated by Django 2.2.7 on 2020-09-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20200904_0910'),
        ('base', '0051_auto_20200904_0753'),
    ]

    operations = [
    ]
