# Generated by Django 2.2.7 on 2020-10-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20201012_0620'),
        ('base', '0057_auto_20201009_1057'),
    ]

    operations = [
    ]
