# Generated by Django 2.2.7 on 2020-10-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20200924_0609'),
        ('base', '0060_auto_20201016_1340'),
    ]

    operations = [
    ]
