# Generated by Django 2.2.7 on 2020-11-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_merge_20201020_0815'),
        ('base', '0064_network_enable_camera_ticks'),
    ]

    operations = [
    ]
