# Generated by Django 2.2.7 on 2020-11-29 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20201127_1315'),
        ('base', '0066_auto_20201128_1726'),
    ]

    operations = [
    ]
