# Generated by Django 2.2.16 on 2020-12-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_merge_20201123_1344'),
        ('base', '0068_merge_20201129_0259'),
    ]

    operations = [
    ]
