# Generated by Django 2.2.7 on 2020-12-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20201221_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerposition',
            name='hours_in_a_week',
            field=models.PositiveSmallIntegerField(default=40, verbose_name='Часов в рабочей неделе'),
        ),
    ]
