# Generated by Django 2.2.7 on 2020-12-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20201209_1209'),
        ('base', '0069_auto_20201202_0950'),
    ]

    operations = [
    ]
