# Generated by Django 2.2.16 on 2020-12-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_workerposition_hours_in_a_week'),
        ('base', '0071_merge_20201216_0753'),
    ]

    operations = [
    ]
