# Generated by Django 2.2.16 on 2020-12-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_merge_20201225_0817'),
        ('base', '0074_auto_20201230_0935'),
    ]

    operations = [
    ]
