# Generated by Django 2.2.16 on 2021-02-24 10:16

import datetime

from django.db import migrations

from etc.scripts.fill_calendar import main


def fill_calendar(apps, schema_editor):
    Region = apps.get_model('base', 'Region')
    r = Region.objects.first()
    main(
        (datetime.date.today() - datetime.timedelta(days=365)).strftime('%Y.%m.%d'),
        (datetime.date.today() + datetime.timedelta(days=365)).strftime('%Y.%m.%d'),
        r.id,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0077_auto_20210121_1307'),
    ]

    operations = [
        migrations.RunPython(fill_calendar, migrations.RunPython.noop),
    ]
