# Generated by Django 2.2.16 on 2021-02-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20210209_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='worker_position_default_values',
            field=models.TextField(default='{}', verbose_name='Параметры должностей по умолчанию'),
        ),
    ]
