# Generated by Django 2.2.16 on 2021-02-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_network_breaks'),
        ('base', '0080_merge_20210225_1227'),
    ]

    operations = [
    ]
