# Generated by Django 2.2.16 on 2021-02-26 04:38

from django.db import migrations


def init_sawh_settings(apps, schema_editor):
    SAWHSettings = apps.get_model('base', 'SAWHSettings')
    Network = apps.get_model('base', 'Network')
    for network in Network.objects.all():
        SAWHSettings.objects.get_or_create(
            network=network,
            code='even_distribution',
            name='Равномерное распределение часов по месяцам',
            defaults=dict(
                work_hours_by_months={f'm{month_num}': 1 for month_num in range(1, 12 + 1)}
            )
        )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0081_auto_20210226_0438'),
    ]

    operations = [
        migrations.RunPython(init_sawh_settings, migrations.RunPython.noop),
    ]
