# Generated by Django 2.2.16 on 2021-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_merge_20210301_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='has_perm_to_change_protected_wdays',
            field=models.BooleanField(default=False, verbose_name='Может изменять/подтверждать "защищенные" рабочие дни'),
        ),
    ]
