# Generated by Django 2.2.16 on 2021-03-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_merge_20210301_1620'),
        ('base', '0082_auto_20210226_0438'),
    ]

    operations = [
    ]
