# Generated by Django 2.2.16 on 2021-03-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20210316_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='show_worker_day_additional_info',
            field=models.BooleanField(default=False, help_text='Отображение при наведении на уголок информации о том, кто и когда последний раз редактировал рабочий день', verbose_name='Отображать доп. информацию в подтвержденных факте и плане'),
        ),
    ]
