# Generated by Django 2.2.16 on 2021-03-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_network_consider_remaining_hours_in_prev_months_when_calc_norm_hours'),
        ('base', '0084_network_show_worker_day_additional_info'),
    ]

    operations = [
    ]
