# Generated by Django 2.2.16 on 2021-03-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_group_has_perm_to_change_protected_wdays'),
        ('base', '0085_merge_20210318_1901'),
        ('base', '0085_merge_20210324_0942'),
    ]

    operations = [
    ]
