# Generated by Django 2.2.16 on 2021-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20210330_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerposition',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=9999, verbose_name='Индекс должности для сортировки'),
        ),
    ]
