# Generated by Django 2.2.16 on 2021-04-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_auto_20210331_0713'),
        ('base', '0089_workerposition_ordering'),
    ]

    operations = [
    ]
