# Generated by Django 2.2.16 on 2021-04-21 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0037_auto_20210331_0713'),
        ('timetable', '0060_auto_20210412_0803'),
        ('base', '0090_merge_20210405_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('tabel_code', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'unique_together': {('tabel_code', 'user')},
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='base.Employee'),
        ),
    ]
