# Generated by Django 2.2.16 on 2021-04-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_auto_20210421_1431'),
        ('timetable', '0062_fill_employee_and_update_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='network',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='user',
        ),
        migrations.AlterField(
            model_name='employment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='base.Employee'),
        ),
    ]
