# Generated by Django 2.2.16 on 2021-04-23 12:12

from django.db import migrations

def add_employee_permissions(apps, schema_editor):
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    Group = apps.get_model('base', 'Group')
    methods = ['GET', 'PUT', 'POST', 'DELETE']
    group = Group.objects.filter(name='Администратор').first()
    if group:
        for m in methods:
            FunctionGroup.objects.get_or_create(
                group=group,
                method=m,
                func='Employee',
                access_type='all',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_auto_20210421_1559'),
    ]

    operations = [
        migrations.RunPython(add_employee_permissions, migrations.RunPython.noop)
    ]
