# Generated by Django 2.2.16 on 2021-04-30 11:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20210426_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('dttm_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsourcing_connections', to='base.Network')),
                ('outsourcing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsourcing_clients', to='base.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='network',
            name='outsourcings',
            field=models.ManyToManyField(related_name='clients', through='base.NetworkConnect', to='base.Network'),
        ),
    ]
