# Generated by Django 2.2.16 on 2021-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20210514_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='create_employment_on_set_or_update_director_code',
            field=models.BooleanField(default=False, verbose_name='Создавать скрытое трудоустройство при проставлении/изменении director_code в подразделении'),
        ),
    ]
