# Generated by Django 2.2.16 on 2021-05-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_network_create_employment_on_set_or_update_director_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='copy_plan_to_fact_crossing',
            field=models.BooleanField(default=False, verbose_name='Копировать план в факт без перезаписи факта'),
        ),
    ]
