# Generated by Django 2.2.16 on 2021-05-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_network_copy_plan_to_fact_crossing'),
        ('base', '0105_auto_20210528_0914'),
    ]

    operations = [
    ]
