# Generated by Django 2.2.16 on 2021-06-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_auto_20210531_1204'),
        ('base', '0106_merge_20210531_1255'),
    ]

    operations = [
    ]
