# Generated by Django 2.2.16 on 2021-07-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_merge_20210714_1203'),
        ('base', '0114_auto_20210714_1557'),
    ]

    operations = [
    ]
