# Generated by Django 2.2.16 on 2021-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0115_merge_20210715_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ldap_login',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
