# Generated by Django 2.2.24 on 2021-10-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0122_auto_20210921_0939'),
        ('base', '0122_auto_20210922_1959'),
    ]

    operations = [
    ]
