# Generated by Django 2.2.16 on 2021-09-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0122_auto_20210922_1959'),
        ('base', '0122_auto_20210921_0538'),
    ]

    operations = [
    ]
