# Generated by Django 2.2.16 on 2021-09-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0128_merge_20210909_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='consider_department_in_att_records',
        ),
    ]
