# Generated by Django 2.2.16 on 2021-09-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0130_auto_20210913_1413'),
        ('base', '0122_auto_20210921_0939'),
    ]

    operations = [
    ]
