# Generated by Django 2.2.24 on 2021-09-28 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0132_auto_20210921_2013'),
        ('base', '0124_merge_20210924_1316'),
    ]

    operations = [
    ]
