# Generated by Django 2.2.24 on 2021-09-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0125_merge_20210928_1332'),
        ('base', '0133_merge_20210928_0753'),
    ]

    operations = [
    ]
