# Generated by Django 2.2.16 on 2021-10-14 06:11

import pandas as pd
from django.db import migrations


def create_function_groups(apps, schema_editor):
    df = pd.read_excel('etc/scripts/new_functions_2021_10.xlsx').fillna('')
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    Group = apps.get_model('base', 'Group')
    group_names = list(df.columns[1:])
    groups = {
        name: Group.objects.filter(name__contains=name).order_by('id').first()
        for name in group_names
    }
    for _, row in df.iterrows():
        func = row[df.columns[0]]
        for name in group_names:
            group = groups.get(name)
            method = row[name]
            if group and method:
                FunctionGroup.objects.get_or_create(
                    group=group,
                    method=method,
                    func=func,
                    defaults=dict(
                        access_type='all',
                    )
                )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0138_merge_20211008_1343'),
    ]

    operations = [
        migrations.RunPython(create_function_groups, migrations.RunPython.noop)
    ]
