# Generated by Django 2.2.24 on 2021-10-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0141_merge_20211019_1108'),
        ('base', '0139_auto_20211013_2310'),
    ]

    operations = [
    ]
