# Generated by Django 2.2.24 on 2021-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0143_auto_20211021_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='round_work_hours_alg',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Округление до получаса')], null=True, verbose_name='Алгоритм округления рабочих часов'),
        ),
    ]
