# Generated by Django 3.2.9 on 2021-11-19 05:02

import re
from django.db import migrations
from django.db.migrations.operations.special import RunPython
import src.apps.base.fields


def create_default_allowed_tabs(apps, schema_editor):
    Group = apps.get_model('base', 'Group')
    allowed_tabs = [
        (r'(.*)?(админ)|(урс)(.*)?', r'(.*)?аутсорс(.*)?', 'load_forecast'),
        (r'.*', None, 'schedule'),
        (r'.*', r'(.*)?сотрудник(.*)?', 'employees'),
        (r'.*', r'(.*)?сотрудник(.*)?', 'shift_exchange'),
        (r'.*', r'(.*)?(директор)|(сотрудник)|(аутсорс)(.*)?', 'analytics'),
        (r'(.*)?(админ)|(урс)(.*)?', r'(.*)?аутсорс(.*)?', 'settings'),
    ]
    for g in Group.objects.all():
        g.allowed_tabs = [
            tab
            for pattern, exclude_pattern, tab in allowed_tabs
            if re.search(pattern, g.name, re.IGNORECASE) and\
            not (re.search(exclude_pattern, g.name, re.IGNORECASE) if exclude_pattern else None)
        ]
        if re.search(r'(.*)?супервайзер(.*)?', g.name, re.IGNORECASE) and not 'analytics' in g.allowed_tabs:
            g.allowed_tabs.append('analytics')
        g.save()
    
class Migration(migrations.Migration):

    dependencies = [
        ('base', '0146_auto_20211117_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allowed_tabs',
            field=src.apps.base.fields.MultipleChoiceField(choices=[('load_forecast', 'Прогноз потребностей'), ('schedule', 'Расписание'), ('employees', 'Сотрудники'), ('shift_exchange', 'Биржа смен'), ('analytics', 'Аналитика'), ('settings', 'Настройки')], default='[]'),
        ),
        migrations.RunPython(create_default_allowed_tabs, RunPython.noop)
    ]
