# Generated by Django 3.2.9 on 2021-11-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0147_auto_20211122_0437'),
        ('base', '0147_auto_20211122_0544'),
        ('base', '0147_auto_20211118_0502'),
    ]

    operations = [
    ]
