# Generated by Django 3.2.9 on 2021-11-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0147_auto_20211118_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='api_timesheet_lines_group_by',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Сотруднику'), (2, 'Сотруднику и должности'), (3, 'Сотруднику, должности и подразделению выхода')], default=3, verbose_name='Группировать данные табеля в tevian методе /rest_api/timesheet/lines/ по'),
        ),
    ]
