# Generated by Django 3.2.9 on 2021-11-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0148_merge_0147_auto_20211118_0502_0147_group_allowed_tabs'),
        ('base', '0148_network_api_timesheet_lines_group_by'),
    ]

    operations = [
    ]
