# Generated by Django 3.2.9 on 2021-11-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0148_merge_0147_auto_20211122_0437_0147_auto_20211122_0544'),
        ('base', '0150_merge_20211122_0442'),
        ('base', '0150_merge_20211122_0624'),
    ]

    operations = [
    ]
