# Generated by Django 3.2.9 on 2021-11-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0151_auto_20211125_1226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shiftschedule',
            unique_together={('employee', 'network'), ('code', 'network')},
        ),
        migrations.RemoveField(
            model_name='shiftschedule',
            name='year',
        ),
    ]
