# Generated by Django 3.2.9 on 2021-11-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0151_auto_20211125_1226'),
        ('base', '0153_network_show_cost_for_inner_vacancies'),
    ]

    operations = [
    ]
