# Generated by Django 3.2.9 on 2021-11-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0154_auto_20211129_0653'),
        ('base', '0154_merge_20211128_2133'),
    ]

    operations = [
    ]
