# Generated by Django 3.2.9 on 2021-11-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0152_auto_20211129_1613'),
        ('base', '0155_merge_20211129_0940'),
    ]

    operations = [
    ]
