# Generated by Django 3.2.9 on 2021-12-03 08:07

from django.db import migrations, models
from django.conf import settings

def set_rebuild_timetable_min_delta(apps, schema_editor):
    Network = apps.get_model('base', 'Network')
    if getattr(settings, 'REBUILD_TIMETABLE_MIN_DELTA', False):
        Network.objects.update(rebuild_timetable_min_delta=getattr(settings, 'REBUILD_TIMETABLE_MIN_DELTA'))

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0156_merge_20211130_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='rebuild_timetable_min_delta',
            field=models.IntegerField(default=2, verbose_name='Минимальное время для составления графика'),
        ),
        migrations.RunPython(set_rebuild_timetable_min_delta, migrations.RunPython.noop),
    ]
