# Generated by Django 3.2.9 on 2021-12-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0164_auto_20211223_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='download_tabel_template',
            field=models.CharField(choices=[('mts', 'MTSTimesheetGenerator'), ('t13_custom', 'CustomT13TimesheetGenerator'), ('default', 'DefaultTimesheetGenerator'), ('lines', 'TimesheetLinesGenerator')], default='default', max_length=64, verbose_name='Download tabel template'),
        ),
    ]
