# Generated by Django 3.2.9 on 2022-01-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0165_alter_network_download_tabel_template'),
        ('base', '0165_network_analytics_type'),
    ]

    operations = [
    ]
