# Generated by Django 3.2.9 on 2022-02-25 10:18

from django.db import migrations, models
import django.db.models.deletion

def set_network_for_empty_values(apps, schema_editor):
    Network = apps.get_model('base', 'Network')
    network = Network.objects.order_by('id').first()
    models_to_update = [
        'break', 'contentblock', 'group', 'region', 'workerposition',
        'sawhsettings', 'shiftschedule', 'shop', 'shopsettings', 
    ]

    for model in models_to_update:
        model = apps.get_model('base', model)
        model.objects.filter(network_id__isnull=True).update(network=network)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0169_auto_20220214_1146'),
    ]

    operations = [
        migrations.RunPython(set_network_for_empty_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='break',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='group',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='region',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='sawhsettings',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='shiftschedule',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
        migrations.AlterField(
            model_name='workerposition',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
    ]
