# Generated by Django 3.2.9 on 2022-02-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0170_auto_20220225_1018'),
        ('base', '0171_merge_20220222_1219'),
    ]

    operations = [
    ]
