# Generated by Django 3.2.9 on 2022-04-21 09:48

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Subquery, OuterRef


def fill_positions_sawh_settings(apps, schema_editor):
    SAWHSettingsMapping = apps.get_model('base', 'SAWHSettingsMapping')
    WorkerPosition = apps.get_model('base', 'WorkerPosition')
    WorkerPosition.objects.filter(
        sawh_settings__isnull=True,
    ).update(
        sawh_settings_id=Subquery(SAWHSettingsMapping.objects.filter(
            positions__id=OuterRef('id'),
            sawh_settings__network_id=OuterRef('network_id'),
        ).values_list('sawh_settings_id')[:1])
    )


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0174_auto_20220419_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerposition',
            name='sawh_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='positions', to='base.sawhsettings', verbose_name='Настройка нормы'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='sawh_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='employments', to='base.sawhsettings', verbose_name='Настройка нормы'),
        ),
        migrations.RunPython(fill_positions_sawh_settings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sawhsettingsmapping',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='sawhsettingsmapping',
            name='exclude_positions',
        ),
        migrations.RemoveField(
            model_name='sawhsettingsmapping',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='sawhsettingsmapping',
            name='shops',
        ),
        migrations.AlterModelOptions(
            name='sawhsettingsmapping',
            options={'ordering': ['-year'], 'verbose_name': 'Настройки суммированного учета рабочего времени', 'verbose_name_plural': 'Настройки суммированного учета рабочего времени'},
        ),
        migrations.RemoveField(
            model_name='sawhsettingsmapping',
            name='priority',
        ),
    ]
