# Generated by Django 3.2.9 on 2022-04-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0175_auto_20220421_0948'),
        ('base', '0176_merge_20220419_1123'),
    ]

    operations = [
    ]
