# Generated by Django 3.2.9 on 2022-08-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0178_merge_20220825_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sawhsettingsmapping',
            name='sawh_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='base.sawhsettings', verbose_name='Настройки СУРВ'),
        ),
    ]
