# Generated by Django 3.2.9 on 2022-10-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0183_alter_network_use_internal_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='biometry_in_tick_report',
            field=models.BooleanField(default=False, verbose_name='Include biometry (photos) in tick report'),
        ),
    ]
