# Generated by Django 3.2.9 on 2022-10-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0184_network_biometry_in_tick_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='is_visible_other_shops',
            field=models.BooleanField(default=True, verbose_name='Display in the chart of other shops'),
        ),
        migrations.AddField(
            model_name='network',
            name='display_chart_in_other_stores',
            field=models.BooleanField(default=False, verbose_name='Ability to disconnect to an account in the charts of other stores'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Display in the chart of my shop'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='sawh_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='base.sawhsettings', verbose_name='Sawh settings'),
        ),
    ]
