# Generated by Django 3.2.9 on 2022-12-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0189_alter_functiongroup_func'),
        ('base', '0190_alter_functiongroup_func'),
    ]

    operations = [
    ]
