# Generated by Django 3.2.9 on 2023-01-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0189_auto_20221223_1655'),
        ('base', '0191_merge_20221221_1703'),
    ]

    operations = [
    ]
