# Generated by Django 3.2.9 on 2023-01-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0192_merge_20230112_1544'),
        ('base', '0192_network_show_restrict_editing_shifts_button'),
    ]

    operations = [
    ]
