# Generated by Django 4.1.7 on 2023-08-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0196_network_night_time_end_network_night_time_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkconnect',
            name='allow_assign_employements_from_outsource',
        ),
        migrations.RemoveField(
            model_name='networkconnect',
            name='allow_choose_shop_from_client_for_employement',
        ),
    ]
