# Generated by Django 4.1.7 on 2023-09-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0197_remove_networkconnect_allow_assign_employements_from_outsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='set_dt_not_actual_for_vacancy_on_transfers',
            field=models.BooleanField(default=True, verbose_name='Clear days in the schedule (internal exchange + additional shifts) when transferring employees'),
        ),
    ]
