# Generated by Django 2.0.5 on 2018-05-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_fixed_days',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='is_fixed_hours',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db.WorkerPosition'),
        ),
    ]
