# Generated by Django 2.0.5 on 2018-05-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180504_0825'),
    ]

    operations = [
    ]
