# Generated by Django 2.0.5 on 2018-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180504_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='do_forecast',
            field=models.CharField(choices=[('H', 'Hard'), ('L', 'Lite'), ('N', 'None')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='cashboxtype',
            name='prior_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='cashboxtype',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
    ]
