# Generated by Django 2.0.5 on 2018-05-04 09:12

from django.db import migrations, models
from django.db.models import Q
from src.db.models import CashboxType as NewCashboxType


def update_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    CashboxType = apps.get_model('db', 'CashboxType')

    # update do_forecast
    query = Q(name='Линия') | Q(name='Возврат') |\
        Q(name='Информация') | Q(name='Доставка')
    CashboxType.objects\
        .filter(query)\
        .update(do_forecast=NewCashboxType.FORECAST_HARD)

    # update probs
    probs = {
        '003': {
            'Линия': 3,
            'Возврат': 0.5,
            'Доставка': 1,
            'Информация': 0.2,
            'Главная касса': 5,
            'СЦ': 1,
            'ОРКК': 3.5,
            'Сверка': 10,
        },
        '004':  {
            'Линия': 3,
            'Возврат': 0.5,
            'Доставка': 1,
            'Информация': 0.2,
            'Главная касса': 3,
        }
    }

    for super_shop_code, super_shop_probs in probs.items():
        for key, value in super_shop_probs.items():
            CashboxType.objects\
                .filter(
                    shop__super_shop__code=super_shop_code,
                    name=key,
                )\
                .update(probability=value)

    # update weights
    prior_weights = {
        '003': {
            'Линия': 1.5,
            'Возврат': 15,
            'Доставка': 10,
            'Информация': 30,
            'Главная касса': 0,
            'СЦ': 0,
            'ОРКК': 0,
            'Сверка': 0,
        },
        '004': {
            'Линия': 1.5,
            'Возврат': 15,
            'Доставка': 10,
            'Информация': 30,
            'Главная касса': 2000,
        }
    }

    for super_shop_code, super_shop_prior_weights in prior_weights.items():
        for key, value in super_shop_prior_weights.items():
            CashboxType.objects\
                .filter(
                    shop__super_shop__code=super_shop_code,
                    name=key,
                )\
                .update(prior_weight=value)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180504_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='do_forecast',
            field=models.CharField(choices=[('H', 'Hard'), ('L', 'Lite'), ('N', 'None')], default='L', max_length=1),
        ),
        migrations.AddField(
            model_name='cashboxtype',
            name='prior_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='cashboxtype',
            name='probability',
            field=models.FloatField(default=1.0),
        ),
        migrations.RunPython(update_data)
    ]
