# Generated by Django 2.0.5 on 2018-05-04 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180504_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='supershop',
            name='tm_end',
            field=models.TimeField(blank=True, default=datetime.time(23, 59, 59), null=True),
        ),
        migrations.AddField(
            model_name='supershop',
            name='tm_start',
            field=models.TimeField(blank=True, default=datetime.time(7, 0), null=True),
        ),
    ]
