# Generated by Django 2.0.5 on 2018-11-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20181123_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecords',
            name='super_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='db.SuperShop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useridentifier',
            name='identifier',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
