# Generated by Django 2.0.5 on 2018-11-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20181123_0901'),
        ('db', '0003_fill_production_days_months_2019'),
    ]

    operations = [
    ]
