# Generated by Django 2.0.5 on 2018-05-04 10:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_shop_forecast_step_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tm_start', models.TimeField(blank=True, default=datetime.time(7, 0), null=True)),
                ('tm_end', models.TimeField(blank=True, default=datetime.time(23, 59, 59), null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('cashbox_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.CashboxType')),
            ],
        ),
    ]
