# Generated by Django 2.0.5 on 2018-12-03 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_merge_20181123_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='parent_worker_day',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='db.WorkerDay'),
        ),
    ]
