# Generated by Django 2.0.5 on 2018-05-07 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20180504_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Shop'),
        ),
    ]
