# Generated by Django 2.0.5 on 2018-12-04 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20181203_0506'),
        ('db', '0008_auto_20181203_1412'),
    ]

    operations = [
    ]
