# Generated by Django 2.0.5 on 2018-05-07 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20180507_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='db.Shop'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='cashbox_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.CashboxType'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='tm_end',
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AlterField(
            model_name='slot',
            name='tm_start',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
