# Generated by Django 2.0.5 on 2018-12-21 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_merge_20181204_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='even_shift_morning_evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='exit1day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='exit42hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='fot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='idle',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='less_norm',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='min_change_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='more_norm',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='shift_start',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='shift_end',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='paired_weekday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='process_type',
            field=models.CharField(choices=[('P', 'production calendar'), ('N', 'norm per year')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='shop',
            name='restricted_end_times',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AddField(
            model_name='shop',
            name='restricted_start_times',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AddField(
            model_name='shop',
            name='tm_shop_closes',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='shop',
            name='tm_shop_opens',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
