# Generated by Django 2.0 on 2018-05-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20180507_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Shop'),
        ),
    ]
