# Generated by Django 2.0.5 on 2019-01-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20181221_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shift_end',
            field=models.SmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='shop',
            name='shift_start',
            field=models.SmallIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='shop',
            name='min_change_time',
            field=models.IntegerField(default=12),
        ),
    ]
