# Generated by Django 2.0.5 on 2019-01-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20190111_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Москва', max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='supershop',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='supershop',
            name='type',
            field=models.CharField(choices=[('H', 'hypermarket'), ('C', 'common supershop')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='supershop',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Region'),
        ),
    ]
