# Generated by Django 2.0 on 2018-05-09 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20180508_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeekdaySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Slot')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='worker',
            field=models.ManyToManyField(through='db.UserWeekdaySlot', to=settings.AUTH_USER_MODEL),
        ),
    ]
