# Generated by Django 2.0.5 on 2019-01-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20190123_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('speed_coef', models.FloatField(default=1)),
                ('do_forecast', models.CharField(choices=[('H', 'Hard'), ('L', 'Lite'), ('N', 'None')], default='L', max_length=1)),
                ('period_demand_params', models.CharField(default='{"max_depth": 10, "eta": 0.2, "min_split_loss": 200, "reg_lambda": 2, "silent": 1, "iterations": 20}', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('dttm_last_update_queue', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('probability', models.FloatField(default=1.0)),
                ('prior_weight', models.FloatField(default=1.0)),
                ('period_queue_params', models.CharField(default='{"max_depth": 10, "eta": 0.2, "min_split_loss": 1, "reg_lambda": 0.1, "silent": 1, "iterations": 20}', max_length=1024)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Shop')),
            ],
            options={
                'verbose_name': 'Тип работ',
                'verbose_name_plural': 'Типы работ',
            },
        ),
        migrations.RemoveField(
            model_name='cashboxtype',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='emptyoutcomevisitors',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='incomevisitors',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='periodclients',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='perioddemandchangelog',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='periodproducts',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='periodqueues',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='purchasesoutcomevisitors',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='waittimeinfo',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='workerday',
            name='cashbox_types',
        ),
        migrations.RemoveField(
            model_name='workerday',
            name='is_manual_tuning',
        ),
        migrations.RemoveField(
            model_name='workerday',
            name='tm_break_start',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='cashbox_type',
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='tm_break_start',
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
        ),
        migrations.AddField(
            model_name='operationtype',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
        ),
        migrations.AddField(
            model_name='emptyoutcomevisitors',
            name='work_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomevisitors',
            name='work_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodclients',
            name='operation_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.OperationType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perioddemandchangelog',
            name='operation_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.OperationType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodproducts',
            name='operation_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.OperationType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodqueues',
            name='operation_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.OperationType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasesoutcomevisitors',
            name='work_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
        ),
        migrations.AddField(
            model_name='waittimeinfo',
            name='work_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workercashboxinfo',
            name='work_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workercashboxinfo',
            unique_together={('worker', 'work_type')},
        ),
        migrations.RemoveField(
            model_name='workercashboxinfo',
            name='cashbox_type',
        ),
        migrations.AddField(
            model_name='workerday',
            name='work_types',
            field=models.ManyToManyField(through='db.WorkerDayCashboxDetails', to='db.WorkType'),
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.WorkType'),
        ),

        migrations.DeleteModel(
            name='CashboxType',
        ),
    ]
