# Generated by Django 2.0.5 on 2019-01-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20190130_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtype',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_type_reversed', to='db.WorkType'),
        ),
    ]
