# Generated by Django 2.0 on 2018-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20180509_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='task_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
