# Generated by Django 2.0.5 on 2019-02-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20190130_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='absenteeism',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='max_workers_amount',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='min_workers_amount',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
