# Generated by Django 2.0.5 on 2019-02-06 14:14

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20190206_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=float(Decimal('0.00')), max_digits=10),
        ),
    ]
