# Generated by Django 2.0 on 2018-05-12 05:21

from django.db import migrations, models
import src.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_timetable_task_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', src.db.models.WorkerManager()),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='man_presence',
            field=models.FloatField(default=0),
        ),
    ]
