# Generated by Django 2.0.5 on 2019-01-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20190130_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.WorkerPosition'),
        ),
    ]
