# Generated by Django 2.0.5 on 2019-02-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20190206_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leveltype',
            name='shop',
        ),
        migrations.DeleteModel(
            name='OfficialHolidays',
        ),
        migrations.DeleteModel(
            name='LevelType',
        ),
    ]
