# Generated by Django 2.0.5 on 2019-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20190206_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='min_workers_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
