# Generated by Django 2.0 on 2018-05-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20180512_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='break_triplets',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AddField(
            model_name='shop',
            name='cost_weights',
            field=models.CharField(default='{}', max_length=4096),
        ),
        migrations.AddField(
            model_name='shop',
            name='method_params',
            field=models.CharField(default='[]', max_length=4096),
        ),
    ]
