# Generated by Django 2.0 on 2018-05-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20180512_0521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'verbose_name': 'Касса', 'verbose_name_plural': 'Кассы'},
        ),
        migrations.AlterModelOptions(
            name='cashboxtype',
            options={'verbose_name': 'Тип кассы', 'verbose_name_plural': 'Типы касс'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name': 'Слот', 'verbose_name_plural': 'Слоты'},
        ),
        migrations.AlterModelOptions(
            name='supershop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='workerposition',
            options={'verbose_name': 'Должность сотрудника', 'verbose_name_plural': 'Должности сотрудников'},
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='extra_info',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='workerdaychangelog',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
