# Generated by Django 2.0.5 on 2019-02-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='idle',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='lack',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='workers_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fot_revenue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
