# Generated by Django 2.0.5 on 2019-01-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='max_workers_amount',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='worktype',
            name='min_workers_amount',
            field=models.IntegerField(default=10),
        ),
    ]
