# Generated by Django 2.0 on 2018-05-20 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20180519_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='cashbox_types',
            field=models.ManyToManyField(through='db.WorkerDayCashboxDetails', to='db.CashboxType'),
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='cashbox_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='db.CashboxType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='on_cashbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Cashbox'),
        ),
    ]
