# Generated by Django 2.0.5 on 2019-02-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20190207_1247'),
        ('db', '0016_auto_20190206_1457'),
    ]

    operations = [
    ]
