# Generated by Django 2.0.5 on 2019-01-31 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20190131_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='dttm_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='dttm_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
