# Generated by Django 2.0.5 on 2019-02-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20190214_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functiongroup',
            options={'verbose_name': 'Доступ к функция'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа пользователей', 'verbose_name_plural': 'Группы пользователей'},
        ),
        migrations.AddField(
            model_name='user',
            name='function_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Group'),
        ),
        migrations.AlterField(
            model_name='functiongroup',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allowed_functions', to='db.Group'),
        ),
    ]
