# Generated by Django 2.0.5 on 2019-02-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20190214_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
    ]
