# Generated by Django 2.0 on 2018-05-24 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_add_cashboxtypes_20180520_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('type', models.CharField(choices=[('W', 'workday'), ('H', 'holiday'), ('S', 'short workday')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_dt', models.DateField()),
                ('total_days', models.SmallIntegerField()),
                ('norm_work_days', models.SmallIntegerField()),
                ('norm_work_hours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerMonthStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.SmallIntegerField()),
                ('work_hours', models.FloatField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.ProductionMonth')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
