# Generated by Django 2.0 on 2018-05-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_user_tabel_code'),
        ('db', '0018_add_cashboxtypes_20180520_0459'),
    ]

    operations = [
    ]
