# Generated by aa on 2018-05-20 04:59

from django.db import migrations, models
import json


def load_algo_info(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Shop = apps.get_model('db', 'Shop')

    full_info = {
        'cost_weights': json.dumps({
            '5d': 10 ** 4,
            'hard': 0,
            'soft': 0,
            'too_much_days': 22,
            'bills': 2,
            '40hours': 0,
            'days': 2 * 10 ** 2,
            '15rest': 0,  # 10**4,
            '5days': 0,
            'hard_constraints': 0,
            'soft_constraints': 0,
            'overwork_fact_days': 3 * 10 ** 6,
            'solitary_days': 5 * 10 ** 3,
            'holidays': 10 ** 5,  # 3*10**5,# 2*10**6,
            'zero_cashiers': 2,
            'slots': 5 * 10 ** 7,
            'man_presence': 0,
        }),
        'method_params': json.dumps([
            {
                'steps': 0,
                'select_best': 64, # Certalty picking the best initialization # Further params doesn't matter at all
                'changes': 15,
                'variety': 8,
                'days_change_prob': 0.1,
                'periods_change_prob': 0.55,
                'add_day_prob': 0.33,
                'del_day_prob': 0.33
            },
            {
                'steps': 2500,
                'select_best': 8,
                'changes': 15,
                'variety': 8,
                'days_change_prob': 0.1,
                'periods_change_prob': 0.55,
                'add_day_prob': 0.33,
                'del_day_prob': 0.33
            },
        ]),
    }

    small_info = {
        'cost_weights': json.dumps({
            'bills': 100,
            '40hours': 0,
            'days': 3 * 10 ** 4,
            '15rest': 0,  # 10**4,
            '5days': 0,
            'hard_constraints': 0,
            'soft_constraints': 0,
            'overwork_fact_days': 3 * 10 ** 3,
            'solitary_days': 5 * 10 ** 3,
            'holidays': 10 ** 2,  # 3*10**5,# 2*10**6,
            'zero_cashiers': 5,
            'slots': 0,
            'man_presence': 0,
            'critical_slots': 2 * 10 ** 5
        }),
        'method_params': json.dumps([
            {
                'steps': 0,
                'select_best': 256,  # Certalty picking the best initialization # Further params doesn't matter at all
                'changes': 5,
                'variety': 8,
                'days_change_prob': 0.15,
                'periods_change_prob': 0.85,
                'add_day_prob': 0.33,
                'del_day_prob': 0.33,
            },
            {
                'steps': 1000,
                'select_best': 16,
                'changes': 5,
                'variety': 16,
                'days_change_prob': 0.15,
                'periods_change_prob': 0.85,
                'add_day_prob': 0.33,
                'del_day_prob': 0.33,
            }
        ]),
    }

    for shop in Shop.objects.all():
        if shop.full_interface:
            vals = full_info
        else:
            vals = small_info
        Shop.objects.filter(id=shop.id).update(**vals)




class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_merge_20180523_0525'),
    ]

    operations = [
        migrations.RunPython(load_algo_info)
    ]