# Generated by Django 2.0.5 on 2019-02-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_remove_user_group'),
        ('db', '0017_merge_20190214_0744'),
    ]

    operations = [
    ]
