# Generated by Django 2.0 on 2018-05-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_fill_2018_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCashbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Cashbox')),
            ],
        ),
        migrations.CreateModel(
            name='CameraCashboxStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm', models.DateTimeField()),
                ('queue', models.FloatField()),
                ('CameraCashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.CameraCashbox')),
            ],
        ),
    ]
