# Generated by Django 2.0.5 on 2019-02-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20190227_1817'),
        ('db', '0021_auto_20190218_1137'),
    ]

    operations = [
    ]
