# Generated by Django 2.0 on 2018-05-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_cameracashbox_cameracashboxstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameracashboxstat',
            old_name='CameraCashbox',
            new_name='camera_cashbox',
        ),
    ]
