# Generated by Django 2.0.5 on 2019-03-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_auto_20190218_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='full_interface',
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
