# Generated by Django 2.0.5 on 2019-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_merge_20190228_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_fixed_days',
        ),
        migrations.AddField(
            model_name='user',
            name='min_time_btw_shifts',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='norm_work_hours',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_hours_length_max',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_hours_length_min',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
