# Generated by Django 2.0 on 2018-05-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_auto_20180524_1823'),
        ('db', '0020_load_info_to_models_20180523_0627'),
    ]

    operations = [
    ]
