# Generated by Django 2.0 on 2018-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_merge_20180525_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='man_presence',
        ),
        migrations.AddField(
            model_name='shop',
            name='init_params',
            field=models.CharField(default='{"n_working_days_optimal": 20}', max_length=2048),
        ),
    ]
