# Generated by Django 2.0.5 on 2019-02-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20190228_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='week_availability',
            field=models.SmallIntegerField(default=7),
        ),
    ]
