# Generated by Django 2.0.5 on 2019-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_user_week_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweekdayslot',
            name='is_suitable',
            field=models.BooleanField(default=True),
        ),
    ]
