# Generated by Django 2.0.5 on 2018-06-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20180528_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='dttm_last_update_queue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
