# Generated by Django 2.0 on 2018-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_auto_20180528_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionmonth',
            options={'ordering': ('dt_first',)},
        ),
        migrations.RenameField(
            model_name='productionmonth',
            old_name='first_dt',
            new_name='dt_first',
        ),
        migrations.AddField(
            model_name='productionday',
            name='is_celebration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
