# Generated by Django 2.0 on 2018-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_auto_20180607_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionday',
            name='dt',
            field=models.DateField(unique=True),
        ),
    ]
