# Generated by Django 2.0.5 on 2019-03-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_auto_20190301_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='work_type',
        ),
    ]
