# Generated by Django 2.0 on 2018-06-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_auto_20180607_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='cashbox_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.CashboxType'),
        ),
    ]
