# Generated by Django 2.0.5 on 2018-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20180615_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='dttm_last_update_queue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
