# Generated by Django 2.0 on 2018-06-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20180615_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='dttm_last_update_queue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='on_education',
            field=models.BooleanField(default=False),
        ),
    ]
