# Generated by Django 2.0.5 on 2018-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20180615_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='workercashboxinfo',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
