# Generated by Django 2.0.5 on 2018-06-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20180615_0428'),
        ('db', '0025_cashboxtype_dttm_last_update_queue'),
    ]

    operations = [
    ]
