# Generated by Django 2.0.5 on 2019-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_remove_user_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='full_interface',
        ),
    ]
