# Generated by Django 2.0.5 on 2018-06-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_auto_20180624_1042'),
        ('db', '0025_cashboxtype_dttm_last_update_queue'),
    ]

    operations = [
    ]
