# Generated by Django 2.0.5 on 2019-03-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_remove_shop_full_interface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtype',
            options={'verbose_name': 'Тип операции', 'verbose_name_plural': 'Типы операций'},
        ),
    ]
