# Generated by Django 2.0.5 on 2018-06-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_merge_20180618_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='on_education',
            field=models.BooleanField(default=False),
        ),
    ]
