# Generated by Django 2.0.5 on 2018-06-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_auto_20180624_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
    ]
