# Generated by Django 2.0.5 on 2018-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_workerdaycashboxdetails_is_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='tm_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
