# Generated by Django 2.0.5 on 2019-03-25 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20190322_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='forecast_step_minutes',
            field=models.TimeField(default=datetime.time(0, 30)),
        ),
        migrations.AlterUniqueTogether(
            name='periodclients',
            unique_together={('operation_type', 'type', 'dttm_forecast')},
        ),
        migrations.AlterUniqueTogether(
            name='periodproducts',
            unique_together={('operation_type', 'type', 'dttm_forecast')},
        ),
        migrations.AlterUniqueTogether(
            name='periodqueues',
            unique_together={('operation_type', 'type', 'dttm_forecast')},
        ),
    ]
