# Generated by Django 2.0.5 on 2018-07-09 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20180625_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workercashboxinfo',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
