# Generated by Django 2.0.5 on 2019-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20190418_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='queue_length',
            field=models.FloatField(default=3.0),
        ),
    ]
