# Generated by Django 2.0.5 on 2019-06-18 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0030_auto_20190618_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='to_workerday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.WorkerDayCashboxDetails'),
        ),
    ]
