# Generated by Django 2.0.5 on 2018-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_cashbox_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='priority',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
