# Generated by Django 2.0.5 on 2019-06-20 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_auto_20190618_1316'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='dttm_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 6, 20, 13, 31, 40, 302439)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='dttm_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='status',
            field=models.CharField(choices=[('W', 'work period'), ('B', 'rest / break'), ('S', 'study period'), ('V', 'vacancy'), ('Z', 'work in trading floor')], default='W', max_length=1),
        ),
    ]
