# Generated by Django 2.0.5 on 2018-07-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_auto_20180710_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='priority',
            field=models.PositiveIntegerField(),
        ),
    ]
