# Generated by Django 2.0.5 on 2018-07-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_auto_20180710_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbox',
            name='priority',
        ),
        migrations.AddField(
            model_name='cashboxtype',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
