# Generated by Django 2.0.5 on 2019-07-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_shop_queue_length'),
        ('db', '0033_auto_20190621_1612'),
    ]

    operations = [
    ]
