# Generated by Django 2.0.5 on 2018-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_auto_20180710_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='tm_break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='tm_break_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
