# Generated by Django 2.0.5 on 2019-06-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_auto_20190621_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automatic_check_lack', models.FloatField(default=-1)),
                ('automatic_create_vacancy', models.BooleanField(default=False)),
                ('automatic_worker_select_timegap', models.DurationField(default=None)),
                ('automatic_worker_select_lack_diff', models.FloatField(default=-1)),
            ],
        ),
    ]
