# Generated by Django 2.0.5 on 2018-07-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_auto_20180710_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='status',
            field=models.CharField(choices=[('W', 'work period'), ('B', 'rest / break'), ('S', 'study period')], default='W', max_length=1),
        ),
    ]
