# Generated by Django 2.0.5 on 2019-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_exchangesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesettings',
            name='automatic_worker_min_add_value',
            field=models.FloatField(default=0.1),
        ),
    ]
