# Generated by Django 2.0.5 on 2018-07-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_workerdaycashboxdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbox',
            name='is_busy',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='is_break',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='on_education',
        ),
    ]
