# Generated by Django 2.0.5 on 2018-07-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_workerdaycashboxdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='perioddemand',
            name='lack_of_cashiers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
