# Generated by Django 2.0.5 on 2018-07-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_auto_20180723_1728'),
        ('db', '0035_perioddemand_lack_of_cashiers'),
    ]

    operations = [
    ]
