# Generated by Django 2.0.5 on 2019-07-02 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_exchangesettings_automatic_worker_min_add_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesettings',
            name='automatic_check_lack_timegap',
            field=models.DurationField(default=datetime.timedelta(7)),
        ),
    ]
