# Generated by Django 2.0.5 on 2019-07-16 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_auto_20190712_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangesettings',
            name='automatic_worker_select_lack_diff',
        ),
        migrations.AddField(
            model_name='exchangesettings',
            name='automatic_worker_select_overflow_min',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='exchangesettings',
            name='automatic_worker_select_timegap',
            field=models.DurationField(default=datetime.timedelta(1)),
        ),
    ]
