# Generated by Django 2.0.5 on 2018-07-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_merge_20180724_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='is_main_type',
            field=models.BooleanField(default=False),
        ),
    ]
