# Generated by Django 2.0.5 on 2019-07-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_auto_20190716_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangesettings',
            old_name='automatic_delete_vacancy_oveflow_max',
            new_name='automatic_delete_vacancy_oveflow_min',
        ),
    ]
