# Generated by Django 2.0.5 on 2019-07-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_merge_20190710_0541'),
        ('db', '0036_exchangesettings_automatic_check_lack_timegap'),
    ]

    operations = [
    ]
