# Generated by Django 2.0.5 on 2018-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_cashboxtype_is_main_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perioddemand',
            name='lack_of_cashiers',
            field=models.IntegerField(default=0),
        ),
    ]
