# Generated by Django 2.0.5 on 2019-07-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_auto_20190719_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangesettings',
            name='automatic_delete_vacancy_oveflow_min',
        ),
        migrations.AddField(
            model_name='exchangesettings',
            name='automatic_delete_vacancy_lack_max',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='exchangesettings',
            name='automatic_create_vacancy_lack_min',
            field=models.FloatField(default=0.5),
        ),
    ]
