# Generated by Django 2.0.5 on 2018-07-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_auto_20180730_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ready_for_overworkings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
