# Generated by Django 2.0.5 on 2018-08-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_auto_20180731_0930'),
        ('db', '0039_shop_count_lack'),
    ]

    operations = [
    ]
