# Generated by Django 2.0.5 on 2019-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_auto_20190723_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='max_work_hours_7days',
            field=models.SmallIntegerField(default=48),
        ),
    ]
