# Generated by Django 2.2.4 on 2019-08-07 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_shop_max_work_hours_7days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecords',
            name='identifier',
        ),
        migrations.AddField(
            model_name='attendancerecords',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserIdentifier',
        ),
    ]
