# Generated by Django 2.0.5 on 2018-08-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('db', '0040_merge_20180805_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='period_demand_log',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='worker_day_change_log',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='worker_day_change_request',
        ),
        migrations.AddField(
            model_name='notifications',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
