# Generated by Django 2.0.5 on 2018-08-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_merge_20180805_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='type',
        ),
    ]
