# Generated by Django 2.2.4 on 2019-08-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_auto_20190807_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecords',
            name='super_shop',
        ),
        migrations.AddField(
            model_name='attendancerecords',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='db.Shop'),
            preserve_default=False,
        ),
    ]
