# Generated by Django 2.0.5 on 2019-08-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_auto_20190807_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerposition',
            name='department',
        ),
    ]
