# Generated by Django 2.0.5 on 2018-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_auto_20180807_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('S', 'success'), ('I', 'info'), ('W', 'warning'), ('E', 'error')], default='S', max_length=1),
        ),
    ]
