# Generated by Django 2.0.5 on 2018-08-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_notifications_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='period_demand_log',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='worker_day_change_log',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='worker_day_change_request',
        ),
    ]
