# Generated by Django 2.0.5 on 2018-08-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_auto_20180807_1634'),
        ('db', '0044_auto_20180807_0932'),
    ]

    operations = [
    ]
