# Generated by Django 2.0.5 on 2018-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_auto_20180815_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='status_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
