# Generated by Django 2.0.5 on 2018-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_merge_20180812_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='workercashboxinfo',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
