# Generated by Django 2.0.5 on 2018-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_merge_20180812_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerday',
            unique_together={('worker', 'dt')},
        ),
        migrations.RemoveField(
            model_name='workerday',
            name='worker_shop',
        ),
    ]
