# Generated by Django 2.0.5 on 2019-08-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_auto_20190829_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtemplate',
            name='value',
            field=models.FloatField(),
        ),
    ]
