# Generated by Django 2.0.5 on 2019-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_auto_20190812_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('r', 'region'), ('s', 'shop')], default='s', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='super_shop',
        ),
    ]
