# Generated by Django 2.0.5 on 2019-08-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_auto_20190813_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesettings',
            name='automatic_worker_select_tree_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='functiongroup',
            name='level_down',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='functiongroup',
            name='level_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='functiongroup',
            name='func',
            field=models.CharField(choices=[('get_cashboxes_open_time', 'get_cashboxes_open_time'), ('get_workers', 'get_workers'), ('get_demand_change_logs', 'get_demand_change_logs'), ('edit_work_type', 'edit_work_type'), ('get_cashboxes_used_resource', 'get_cashboxes_used_resource'), ('get_notifications', 'get_notifications'), ('get_notifications2', 'get_notifications2'), ('get_cashboxes_info', 'get_cashboxes_info'), ('get_department', 'get_department'), ('update_cashbox', 'update_cashbox'), ('delete_work_type', 'delete_work_type'), ('get_outsource_workers', 'get_outsource_workers'), ('add_supershop', 'add_supershop'), ('change_cashier_info', 'change_cashier_info'), ('get_demand_xlsx', 'get_demand_xlsx'), ('get_not_working_cashiers_list', 'get_not_working_cashiers_list'), ('get_table', 'get_table'), ('get_worker_day', 'get_worker_day'), ('create_cashbox', 'create_cashbox'), ('set_worker_day', 'set_worker_day'), ('signout', 'signout'), ('create_timetable', 'create_timetable'), ('get_regions', 'get_regions'), ('get_slots', 'get_slots'), ('get_user_urv', 'get_user_urv'), ('get_cashboxes', 'get_cashboxes'), ('get_cashier_timetable', 'get_cashier_timetable'), ('select_cashiers', 'select_cashiers'), ('request_worker_day', 'request_worker_day'), ('add_outsource_workers', 'add_outsource_workers'), ('get_parameters', 'get_parameters'), ('set_worker_restrictions', 'set_worker_restrictions'), ('create_cashier', 'create_cashier'), ('get_urv_xlsx', 'get_urv_xlsx'), ('get_cashiers_info', 'get_cashiers_info'), ('create_work_type', 'create_work_type'), ('get_visitors_info', 'get_visitors_info'), ('get_time_distribution', 'get_time_distribution'), ('set_queue', 'set_queue'), ('set_notifications_read', 'set_notifications_read'), ('get_status', 'get_status'), ('get_forecast', 'get_forecast'), ('set_parameters', 'set_parameters'), ('get_cashiers_list', 'get_cashiers_list'), ('get_change_request', 'get_change_request'), ('delete_timetable', 'delete_timetable'), ('get_types', 'get_types'), ('get_super_shop', 'get_super_shop'), ('get_supershop_stats', 'get_supershop_stats'), ('get_all_slots', 'get_all_slots'), ('get_cashiers_timetable', 'get_cashiers_timetable'), ('set_demand', 'set_demand'), ('dublicate_cashier_table', 'dublicate_cashier_table'), ('get_month_stat', 'get_month_stat'), ('handle_worker_day_request', 'handle_worker_day_request'), ('get_workers_to_exchange', 'get_workers_to_exchange'), ('get_tabel', 'get_tabel'), ('delete_cashier', 'delete_cashier'), ('get_worker_day_logs', 'get_worker_day_logs'), ('password_edit', 'password_edit'), ('get_cashier_info', 'get_cashier_info'), ('change_cashier_status', 'change_cashier_status'), ('set_selected_cashiers', 'set_selected_cashiers'), ('get_indicators', 'get_indicators'), ('upload_demand', 'upload_demand'), ('upload_timetable', 'upload_timetable'), ('change_user_urv', 'change_user_urv'), ('get_parent', 'get_parent'), ('delete_cashbox', 'delete_cashbox'), ('set_timetable', 'set_timetable'), ('get_super_shop_list', 'get_super_shop_list'), ('delete_worker_day', 'delete_worker_day'), ('create_predbills_request', 'create_predbills_request'), ('get_timetable_xlsx', 'get_timetable_xlsx'), ('process_forecast', 'process_forecast'), ('edit_supershop', 'edit_supershop'), ('get_supershops_stats', 'get_supershops_stats'), ('edit_shop', 'edit_shop'), ('add_shop', 'add_shop'), ('notify_workers_about_vacancy', 'notify_workers_about_vacancy'), ('show_vacancy', 'show_vacancy'), ('cancel_vacancy', 'cancel_vacancy'), ('confirm_vacancy', 'confirm_vacancy'), ('do_notify_action', 'do_notify_action'), ('exchange_workers_day', 'exchange_workers_day')], max_length=128),
        ),
        migrations.AlterField(
            model_name='shop',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='db.Shop'),
        ),
    ]
