# Generated by Django 2.0.5 on 2018-08-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_timetable_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='period_demand_params',
            field=models.CharField(default='{"max_depth":-1,"eta":-1,"min_split_loss":-1,"reg_lambda":-1,"silent":-1,"is_main_type":-1}', max_length=1024),
        ),
    ]
