# Generated by Django 2.0.5 on 2019-09-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0046_auto_20190829_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtemplate',
            options={'verbose_name': 'Шаблон операций', 'verbose_name_plural': 'Шаблоны операций'},
        ),
        migrations.AlterField(
            model_name='operationtemplate',
            name='dt_built_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
