# Generated by Django 2.0.5 on 2018-08-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_cashboxtype_period_demand_params'),
        ('db', '0045_merge_20180812_2012'),
    ]

    operations = [
    ]
