# Generated by Django 2.0.5 on 2018-08-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_auto_20180821_1800'),
        ('db', '0048_merge_20180820_1453'),
    ]

    operations = [
    ]
