# Generated by Django 2.0.5 on 2018-08-30 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_auto_20180830_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerday',
            name='tm_work_end',
        ),
        migrations.RemoveField(
            model_name='workerday',
            name='tm_work_start',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='tm_from',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='tm_to',
        ),
    ]
