# Generated by Django 2.0.5 on 2018-08-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0049_slot_workers_needed'),
        ('db', '0049_merge_20180830_0850'),
    ]

    operations = [
    ]
