# Generated by Django 2.0.5 on 2019-09-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0045_auto_20190903_0926'),
        ('db', '0050_root_shop_create'),
    ]

    operations = [
    ]
