# Generated by Django 2.0.5 on 2019-09-11 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0052_create_access_rights'),
        ('db', '0047_auto_20190902_1218'),
    ]

    operations = [
    ]
