# Generated by Django 2.0.5 on 2018-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0052_auto_20180830_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attachment_group',
            field=models.CharField(choices=[('S', 'staff'), ('O', 'outsource')], default='S', max_length=1),
        ),
    ]
