# Generated by Django 2.0.5 on 2018-10-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_user_attachment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerconstraint',
            name='is_lite',
            field=models.BooleanField(default=False),
        ),
    ]
