# Generated by Django 2.0.5 on 2018-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_user_attachment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxtype',
            name='is_stable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='status',
            field=models.CharField(choices=[('W', 'work period'), ('B', 'rest / break'), ('S', 'study period'), ('Z', 'work in trading floor')], default='W', max_length=1),
        ),
    ]
