# Generated by Django 2.0.5 on 2018-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_user_attachment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashboxtype',
            name='is_trading_floor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashboxtype',
            name='is_stable',
            field=models.BooleanField(default=False),
        ),
    ]
