# Generated by Django 2.0.5 on 2018-10-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_auto_20181002_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shop',
            unique_together={('super_shop', 'title')},
        ),
        migrations.RemoveField(
            model_name='supershop',
            name='hidden_title',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='hidden_title',
        ),
    ]
