# Generated by Django 2.0.5 on 2018-10-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_workerconstraint_is_lite'),
        ('db', '0054_auto_20181002_1711'),
    ]

    operations = [
    ]
