# Generated by Django 2.0.5 on 2019-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_auto_20190918_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
