# Generated by Django 2.0.5 on 2019-10-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0054_auto_20190918_1228'),
        ('db', '0046_auto_20190903_1550'),
    ]

    operations = [
    ]
