# Generated by Django 2.0.5 on 2019-10-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_merge_20191009_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dt_new_week_availability_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functiongroup',
            name='func',
            field=models.CharField(choices=[('get_worker_day_approves', 'get_worker_day_approves'), ('create_worker_day_approve', 'create_worker_day_approve'), ('delete_worker_day_approve', 'delete_worker_day_approve'), ('get_cashboxes_open_time', 'get_cashboxes_open_time'), ('get_workers', 'get_workers'), ('get_demand_change_logs', 'get_demand_change_logs'), ('edit_work_type', 'edit_work_type'), ('get_cashboxes_used_resource', 'get_cashboxes_used_resource'), ('get_notifications', 'get_notifications'), ('get_notifications2', 'get_notifications2'), ('get_cashboxes_info', 'get_cashboxes_info'), ('get_department', 'get_department'), ('update_cashbox', 'update_cashbox'), ('delete_work_type', 'delete_work_type'), ('get_outsource_workers', 'get_outsource_workers'), ('change_cashier_info', 'change_cashier_info'), ('get_not_working_cashiers_list', 'get_not_working_cashiers_list'), ('get_table', 'get_table'), ('get_worker_day', 'get_worker_day'), ('create_cashbox', 'create_cashbox'), ('set_worker_day', 'set_worker_day'), ('signout', 'signout'), ('create_timetable', 'create_timetable'), ('get_regions', 'get_regions'), ('get_slots', 'get_slots'), ('get_user_urv', 'get_user_urv'), ('get_cashboxes', 'get_cashboxes'), ('get_cashier_timetable', 'get_cashier_timetable'), ('select_cashiers', 'select_cashiers'), ('request_worker_day', 'request_worker_day'), ('add_outsource_workers', 'add_outsource_workers'), ('set_worker_restrictions', 'set_worker_restrictions'), ('create_cashier', 'create_cashier'), ('get_cashiers_info', 'get_cashiers_info'), ('create_work_type', 'create_work_type'), ('get_visitors_info', 'get_visitors_info'), ('get_time_distribution', 'get_time_distribution'), ('set_queue', 'set_queue'), ('set_notifications_read', 'set_notifications_read'), ('get_status', 'get_status'), ('get_forecast', 'get_forecast'), ('get_cashiers_list', 'get_cashiers_list'), ('get_change_request', 'get_change_request'), ('delete_timetable', 'delete_timetable'), ('get_types', 'get_types'), ('get_all_slots', 'get_all_slots'), ('get_cashiers_timetable', 'get_cashiers_timetable'), ('set_demand', 'set_demand'), ('dublicate_cashier_table', 'dublicate_cashier_table'), ('get_month_stat', 'get_month_stat'), ('handle_worker_day_request', 'handle_worker_day_request'), ('get_workers_to_exchange', 'get_workers_to_exchange'), ('get_tabel', 'get_tabel'), ('delete_cashier', 'delete_cashier'), ('get_worker_day_logs', 'get_worker_day_logs'), ('password_edit', 'password_edit'), ('get_cashier_info', 'get_cashier_info'), ('change_cashier_status', 'change_cashier_status'), ('set_selected_cashiers', 'set_selected_cashiers'), ('get_indicators', 'get_indicators'), ('upload_demand', 'upload_demand'), ('upload_timetable', 'upload_timetable'), ('change_user_urv', 'change_user_urv'), ('get_parent', 'get_parent'), ('delete_cashbox', 'delete_cashbox'), ('set_timetable', 'set_timetable'), ('delete_worker_day', 'delete_worker_day'), ('create_predbills_request', 'create_predbills_request'), ('process_forecast', 'process_forecast'), ('notify_workers_about_vacancy', 'notify_workers_about_vacancy'), ('show_vacancy', 'show_vacancy'), ('cancel_vacancy', 'cancel_vacancy'), ('confirm_vacancy', 'confirm_vacancy'), ('do_notify_action', 'do_notify_action'), ('exchange_workers_day', 'exchange_workers_day'), ('upload_urv', 'upload_urv'), ('get_operation_templates', 'get_operation_templates'), ('create_operation_template', 'create_operation_template'), ('update_operation_template', 'update_operation_template'), ('delete_operation_template', 'delete_operation_template'), ('set_pred_bills', 'set_pred_bills'), ('get_demand_xlsx', 'get_demand_xlsx'), ('get_department_stats_xlsx', 'get_department_stats_xlsx'), ('get_timetable_xlsx', 'get_timetable_xlsx'), ('get_urv_xlsx', 'get_urv_xlsx'), ('add_department', 'add_department'), ('edit_department', 'edit_department'), ('get_department_list', 'get_department_list'), ('get_department_stats', 'get_department_stats'), ('get_parameters', 'get_parameters'), ('set_parameters', 'set_parameters')], max_length=128),
        ),
    ]
