# Generated by Django 2.0.5 on 2018-10-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_auto_20181020_1043'),
        ('db', '0055_merge_20181020_1516'),
    ]

    operations = [
    ]
