# Generated by Django 2.0.5 on 2019-10-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_workerday_comment'),
        ('db', '0055_merge_20191009_0607'),
    ]

    operations = [
    ]
