# Generated by Django 2.0.5 on 2018-10-30 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_merge_20181022_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerdaychangerequest',
            old_name='worker_day_dt',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='workerdaychangerequest',
            old_name='tm_work_end',
            new_name='dttm_work_end',
        ),
        migrations.RenameField(
            model_name='workerdaychangerequest',
            old_name='tm_work_start',
            new_name='dttm_work_start',
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='worker_day',
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='worker_day_worker',
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
