# Generated by Django 2.0.5 on 2018-11-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_merge_20181022_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerdaychangerequest',
            old_name='worker_day_dt',
            new_name='dt',
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='dttm_work_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='dttm_work_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='status_type',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='wish_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='tm_work_end',
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='tm_work_start',
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='worker_day',
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='worker_day_worker',
        ),
        migrations.AlterUniqueTogether(
            name='workerdaychangerequest',
            unique_together={('worker', 'dt')},
        ),
    ]
