# Generated by Django 2.0.5 on 2019-10-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_auto_20191023_1157'),
        ('db', '0055_workerday_comment'),
    ]

    operations = [
    ]
