# Generated by Django 2.0.5 on 2018-11-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0057_auto_20181030_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='status_type',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='wish_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workerdaychangerequest',
            name='dttm_work_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerdaychangerequest',
            name='dttm_work_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='workerdaychangerequest',
            name='is_approved',
        ),
        migrations.AlterUniqueTogether(
            name='workerdaychangerequest',
            unique_together={('worker', 'dt')},
        ),
    ]
