# Generated by Django 2.0.5 on 2018-10-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0057_auto_20181030_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdaychangerequest',
            name='wish_text',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='workerdaychangerequest',
            unique_together={('worker', 'dt')},
        ),
    ]
