# Generated by Django 2.0.5 on 2019-11-07 14:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0059_employment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_timetable',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dt_fired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dt_hired',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dt_new_week_availability_from',
        ),
        migrations.RemoveField(
            model_name='user',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='function_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_fixed_hours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_ready_for_overworkings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='min_time_btw_shifts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='norm_work_hours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shift_hours_length_max',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shift_hours_length_min',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tabel_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='week_availability',
        ),
        migrations.AlterField(
            model_name='employment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='employments', to='db.Shop'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='employments', to=settings.AUTH_USER_MODEL),
        ),
    ]
