# Generated by Django 2.2.7 on 2019-11-22 12:42

from django.db import migrations, models
from src.db.models import WorkerDay

types = [
    WorkerDay.TYPE_HOLIDAY, 
    WorkerDay.TYPE_WORKDAY,
    WorkerDay.TYPE_VACATION, 
    WorkerDay.TYPE_SICK, 
    WorkerDay.TYPE_QUALIFICATION, 
    WorkerDay.TYPE_ABSENSE,
    WorkerDay.TYPE_MATERNITY, 
    WorkerDay.TYPE_BUSINESS_TRIP, 
    WorkerDay.TYPE_ETC,
    WorkerDay.TYPE_DELETED, 
    WorkerDay.TYPE_EMPTY, 
    WorkerDay.TYPE_HOLIDAY_WORK, 
    WorkerDay.TYPE_REAL_ABSENCE, 
    WorkerDay.TYPE_EXTRA_VACATION,
    WorkerDay.TYPE_TRAIN_VACATION,
    WorkerDay.TYPE_SELF_VACATION,
    WorkerDay.TYPE_SELF_VACATION_TRUE,
    WorkerDay.TYPE_GOVERNMENT,
    WorkerDay.TYPE_HOLIDAY_SPECIAL,
    WorkerDay.TYPE_MATERNITY_CARE,
    WorkerDay.TYPE_DONOR_OR_CARE_FOR_DISABLED_PEOPLE,
]

def change_wroker_days(apps, shema_editor):
        WorkerDay = apps.get_model('db', 'WorkerDay')
        WorkerDayChangeRequest = apps.get_model('db', 'WorkerDayChangeRequest')
        for wd in WorkerDay.objects.all():
            wd.type = types[int(wd.type) - 1]
            wd.save()
        for wd in WorkerDayChangeRequest.objects.all():
            wd.type = types[int(wd.type) - 1]
            wd.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_auto_20191122_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='type',
            field=models.CharField(choices=[('H', 'Выходной'), ('W', 'Рабочий день'), ('V', 'Отпуск'), ('S', 'Больничный лист'), ('Q', 'Квалификация'), ('A', 'Неявка до выяснения обстоятельств'), ('M', 'Б/л по беременноси и родам'), ('T', 'Командировка'), ('O', 'Другое'), ('D', 'Удален'), ('E', 'Пусто'), ('HW', 'Работа в выходной день'), ('RA', 'Прогул на основании акта'), ('EV', 'Доп. отпуск'), ('TV', 'Учебный отпуск'), ('SV', 'Отпуск за свой счёт'), ('ST', 'Отпуск за свой счёт по уважительной причине'), ('G', 'Гос. обязанности'), ('HS', 'Спец. выходной'), ('MC', 'Отпуск по уходу за ребёнком до 3-х лет'), ('C', 'Выходные дни по уходу')], default='E', max_length=2),
        ),
        migrations.AlterField(
            model_name='workerdaychangerequest',
            name='type',
            field=models.CharField(choices=[('H', 'Выходной'), ('W', 'Рабочий день'), ('V', 'Отпуск'), ('S', 'Больничный лист'), ('Q', 'Квалификация'), ('A', 'Неявка до выяснения обстоятельств'), ('M', 'Б/л по беременноси и родам'), ('T', 'Командировка'), ('O', 'Другое'), ('D', 'Удален'), ('E', 'Пусто'), ('HW', 'Работа в выходной день'), ('RA', 'Прогул на основании акта'), ('EV', 'Доп. отпуск'), ('TV', 'Учебный отпуск'), ('SV', 'Отпуск за свой счёт'), ('ST', 'Отпуск за свой счёт по уважительной причине'), ('G', 'Гос. обязанности'), ('HS', 'Спец. выходной'), ('MC', 'Отпуск по уходу за ребёнком до 3-х лет'), ('C', 'Выходные дни по уходу')], default='E', max_length=2),
        ),
        migrations.RunPython(change_wroker_days),
    ]
