# Generated by Django 2.0.5 on 2019-11-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0060_auto_20191107_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='attachment_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attachment_group',
        ),
    ]
