# Generated by Django 2.2.7 on 2019-11-25 12:33

from django.db import migrations, models
from src.base.models import Timetable

statuses = [
    Timetable.READY,
    Timetable.PROCESSING,
    Timetable.ERROR,
]

def change_time_table(apps, shema_editor):
        Timetable = apps.get_model('db', 'Timetable')
        for tt in Timetable.objects.all():
            tt.status = statuses[int(tt.status) - 1]
            tt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_auto_20191122_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=models.CharField(choices=[('R', 'Готово'), ('P', 'В процессе'), ('E', 'Ошибка')], default='P', max_length=1),
        ),
        migrations.RunPython(change_time_table),
    ]
