# Generated by Django 2.0.5 on 2019-11-18 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_auto_20191113_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to='db.Shop'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerconstraint',
            name='employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Employment'),
        ),
    ]
