# Generated by Django 2.2.7 on 2019-11-22 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_auto_20191118_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workermonthstat',
            options={'verbose_name': 'Статистика по работе сотрудника за месяц'},
        ),
        migrations.AddField(
            model_name='workermonthstat',
            name='employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Employment'),
        ),
        migrations.AddField(
            model_name='workermonthstat',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Shop'),
        ),
        migrations.RunSQL([
            "update db_workermonthstat as w set shop_id=e.shop_id, employment_id=e.id from db_employment e where w.worker_id=e.user_id",])
    ]
