# Generated by Django 2.2.7 on 2019-11-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_auto_20191122_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweekdayslot',
            name='employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Employment'),
        ),
        migrations.AddField(
            model_name='userweekdayslot',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.Shop'),
        ),
        migrations.RunSQL([
            "update db_userweekdayslot as w set shop_id=e.shop_id, employment_id=e.id from db_employment e where w.worker_id=e.user_id", ])
    ]
