# Generated by Django 2.2.7 on 2019-11-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_auto_20191125_0846'),
        ('db', '0059_auto_20191120_1548'),
    ]

    operations = [
    ]
