# Generated by Django 2.2.7 on 2019-11-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0067_auto_20191127_1230'),
        ('db', '0067_auto_20191126_1210'),
    ]

    operations = [
    ]
