# Generated by Django 2.2.7 on 2019-11-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_auto_20191125_1233'),
        ('db', '0068_merge_20191129_1043'),
    ]

    operations = [
    ]
