# Generated by Django 2.2.7 on 2019-12-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0070_auto_20191204_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermonthstat',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='workermonthstat',
            name='month',
        ),
        migrations.RemoveField(
            model_name='workermonthstat',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='workermonthstat',
            name='worker',
        ),
        migrations.DeleteModel(
            name='ProductionMonth',
        ),
        migrations.DeleteModel(
            name='WorkerMonthStat',
        ),
    ]
