# Generated by Django 2.2.7 on 2019-12-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0072_auto_20191209_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionday',
            name='dt',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='productionday',
            unique_together={('dt', 'region')},
        ),
    ]
