# Generated by Django 2.2.7 on 2019-12-16 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0073_auto_20191209_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workercashboxinfo',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Employment'),
        ),
#        migrations.AlterUniqueTogether(
#            name='workercashboxinfo',
#            unique_together={('employment', 'work_type')},
#        ),
    ]
