# Generated by Django 2.2.7 on 2019-12-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0074_auto_20191216_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workercashboxinfo',
            unique_together={('employment', 'work_type')},
        ),
    ]
