# Generated by Django 2.2.7 on 2019-12-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0075_auto_20191217_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='functiongroup',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=6),
        ),
    ]
