# Generated by Django 2.2.3 on 2019-07-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '__first__'),
        ('recognition', '0002_auto_20190726_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceTick',
            new_name='TickPoint',
        ),
        migrations.RenameField(
            model_name='tick',
            old_name='place_tick',
            new_name='tick_point',
        ),
    ]
