# Generated by Django 2.2.3 on 2019-07-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_auto_20190726_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='photo',
            field=models.ImageField(default=1, upload_to='user_photo/%Y/%m'),
            preserve_default=False,
        ),
    ]
