# Generated by Django 2.2.3 on 2019-07-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_auto_20190726_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tick',
            old_name='photo',
            new_name='image',
        ),
    ]
