# Generated by Django 2.2.3 on 2019-07-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '__first__'),
        ('recognition', '0005_auto_20190726_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='worker_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='ticks', to='timetable.WorkerDay'),
        ),
    ]
