# Generated by Django 2.2.3 on 2019-07-30 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_auto_20190727_1809'),
    ]

    operations = [
       migrations.AddField(
            model_name='tickpoint',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
