# Generated by Django 2.2.3 on 2019-07-30 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0009_auto_20190730_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.User'),
        ),
        migrations.AlterField(
            model_name='tickpoint',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='userconnecter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='base.User'),
        ),
    ]
