# Generated by Django 2.2.3 on 2019-08-02 10:04

from django.db import migrations, models
import django.db.models.deletion
import src.recognition.models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0011_tickpoint_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='image',
            field=models.ImageField(upload_to=src.recognition.models.user_directory_path),
        ),
        migrations.CreateModel(
            name='TickPointToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='recognition.TickPoint')),
            ],
        ),
    ]
