# Generated by Django 2.2.3 on 2019-08-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0012_auto_20190802_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='liveness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tick',
            name='dttm',
            field=models.DateTimeField(),
        ),
    ]
