# Generated by Django 2.2.3 on 2019-10-04 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.recognition.models

def move_photos(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.
    Tick = apps.get_model("recognition", "Tick")
    TickPhoto = apps.get_model("recognition", "TickPhoto")
    for tick in Tick.objects.all():
        TickPhoto.objects.create(
            image=tick.image,
            liveness=tick.liveness,
            verified_score=tick.verified_score,
            tick=tick,
            dttm=tick.dttm,
            type=src.recognition.models.TickPhoto.TYPE_SELF
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0015_tick_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickPhoto',
            fields=[
                ('dttm_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dttm', models.DateTimeField()),
                ('verified_score', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to=src.recognition.models.user_directory_path)),
                ('type', models.CharField(choices=[('S', 'self'), ('F', 'first'), ('L', 'last')], max_length=1)),
                ('lateness', models.DurationField(null=True)),
                ('liveness', models.FloatField(null=True)),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recognition.Tick')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(move_photos),
    ]
