# Generated by Django 2.2.3 on 2019-10-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0016_tickphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tick',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tick',
            name='liveness',
        ),
        migrations.RemoveField(
            model_name='tick',
            name='verified_score',
        ),
    ]
