# Generated by Django 2.2.3 on 2019-10-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0018_auto_20191014_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='is_front',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickphoto',
            name='is_front',
            field=models.BooleanField(default=False),
        ),
    ]
