# Generated by Django 2.2.3 on 2019-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0019_auto_20191014_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='type',
            field=models.CharField(choices=[('C', 'coming'), ('L', 'leaving'), ('S', 'break start'), ('E', 'break_end')], max_length=1),
        ),
    ]
