# Generated by Django 2.2.7 on 2020-11-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0063_auto_20201110_0952'),
        ('recognition', '0022_auto_20201001_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tick',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='tickphoto',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='tickpoint',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='userconnecter',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='tick',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tickphoto',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tickpoint',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tickpoint',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tickpoint',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tickpoint',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network'),
        ),
        migrations.AddField(
            model_name='userconnecter',
            name='dttm_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
