# Generated by Django 2.2.16 on 2021-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0026_auto_20201207_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='type',
            field=models.CharField(choices=[('C', 'coming'), ('L', 'leaving'), ('S', 'break start'), ('E', 'break_end'), ('N', 'no_type')], max_length=1),
        ),
    ]
