# Generated by Django 3.2.9 on 2022-10-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0030_alter_tickpoint_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='type',
            field=models.CharField(choices=[('C', 'Coming'), ('L', 'Leaving'), ('S', 'Break start'), ('E', 'Break end'), ('N', 'No type')], max_length=1),
        ),
    ]
