# Generated by Django 2.2.16 on 2021-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='count_of_periods',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='include_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='period',
            field=models.CharField(choices=[('D', 'Day'), ('M', 'Month'), ('Q', 'Quarter'), ('H', 'Half a year'), ('Y', 'Year')], default='D', max_length=1),
        ),
    ]
