# Generated by Django 2.2.16 on 2021-07-21 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20210719_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='email_addresses',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='E-mail адреса получателей, через запятую'),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='email_text',
            field=models.TextField(blank=True, null=True, verbose_name='E-mail текст'),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='_reportconfig_groups_+', to='base.Group', verbose_name='Оповещать пользователей определенных групп'),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='send_by_group_employments_shops',
            field=models.BooleanField(default=False, verbose_name='Фильтровать рассылку по магазинам трудоустройств групп'),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='shops_to_notify',
            field=models.ManyToManyField(blank=True, related_name='_reportconfig_shops_to_notify_+', to='base.Shop', verbose_name='Оповещать по почте магазина'),
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='subject',
            field=models.CharField(default=1, max_length=256, verbose_name='Тема письма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Оповещать конкретных пользователей'),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='count_of_periods',
            field=models.IntegerField(default=1, verbose_name='Количество периодов'),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='include_today',
            field=models.BooleanField(default=False, verbose_name='Включать сегодняшний день'),
        ),
        migrations.AlterField(
            model_name='reportconfig',
            name='period',
            field=models.CharField(choices=[('D', 'Day'), ('M', 'Month'), ('Q', 'Quarter'), ('H', 'Half a year'), ('Y', 'Year')], default='D', max_length=1, verbose_name='Период'),
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('dttm_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('code', models.CharField(max_length=64, verbose_name='Код')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network')),
            ],
            options={
                'verbose_name': 'Тип отчета',
                'verbose_name_plural': 'Типы отчетов',
                'unique_together': {('code', 'network')},
            },
        ),
        migrations.AddField(
            model_name='reportconfig',
            name='report_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.ReportType', verbose_name='Тип отчета'),
        ),
    ]
