# Generated by Django 3.2.9 on 2022-02-25 10:18

from django.db import migrations, models
import django.db.models.deletion

def set_network_for_empty_values(apps, schema_editor):
    Network = apps.get_model('base', 'Network')
    network = Network.objects.order_by('id').first()
    models_to_update = [
        'reporttype'
    ]

    for model in models_to_update:
        model = apps.get_model('reports', model)
        model.objects.filter(network_id__isnull=True).update(network=network)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0170_auto_20220225_1018'),
        ('reports', '0013_employmentstats'),
    ]

    operations = [
        migrations.RunPython(set_network_for_empty_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reporttype',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.network'),
        ),
    ]
