# Generated by Django 2.2.7 on 2020-02-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20200206_0648'),
    ]

    operations = [
        migrations.RenameModel('Timetable', 'ShopMonthStat'),
        migrations.AlterModelOptions(
            name='shopmonthstat',
            options={'verbose_name': 'Статистика по магазину за месяц', 'verbose_name_plural': 'Статистики по магазинам за месяц'},
        ),
        migrations.AlterField(
            model_name='shopmonthstat',
            name='status',
            field=models.CharField(choices=[('R', 'Готово'), ('P', 'В процессе'), ('E', 'Ошибка'), ('N', 'График не составлен')], default='N', max_length=1),
        ),
    ]
