# Generated by Django 2.2.7 on 2020-03-13 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20200312_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='work_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
