# Generated by Django 2.2.7 on 2020-03-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_auto_20200316_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkerCashboxInfo',
            new_name='WorkerWorkType',
        ),
    ]
