# Generated by Django 2.2.7 on 2020-03-30 10:59

from django.db import migrations, models
import django.db.models.deletion


def approve_worker_days(apps, schema_editor):
    WorkerDay = apps.get_model('timetable', 'WorkerDay')
    WorkerDay.objects.all().update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20200318_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerday',
            name='worker_day_approve',
        ),
        migrations.AddField(
            model_name='workerday',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workerconstraint',
            name='employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_constraints', to='base.Employment'),
        ),
        migrations.AlterField(
            model_name='employmentworktype',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_types', to='base.Employment'),
        ),
        migrations.DeleteModel(
            name='WorkerDayApprove',
        ),
    ]
