# Generated by Django 2.2.7 on 2020-03-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20200323_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerdaycashboxdetails',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_day_details', to='base.Event'),
        ),
    ]
