# Generated by Django 2.2.7 on 2020-04-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_merge_20200406_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerday',
            name='dttm_deleted',
        ),
    ]
