# Generated by Django 2.2.7 on 2020-04-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20200402_0851'),
        ('timetable', '0014_auto_20200327_1143'),
    ]

    operations = [
    ]
