# Generated by Django 2.2.7 on 2020-04-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_remove_workerday_dttm_deleted'),
        ('timetable', '0015_merge_20200407_0819'),
    ]

    operations = [
    ]
