# Generated by Django 2.2.7 on 2020-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_auto_20200410_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='is_vacancy',
            field=models.BooleanField(default=False),
        ),
    ]
