# Generated by Django 2.2.7 on 2020-04-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20200220_0727'),
        ('timetable', '0018_auto_20200410_1130'),
    ]

    operations = [
    ]
