# Generated by Django 2.2.7 on 2020-04-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_merge_20200417_1013'),
        ('timetable', '0020_auto_20200429_0942'),
    ]

    operations = [
    ]
