# Generated by Django 2.2.7 on 2020-04-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20200220_0727'),
        ('timetable', '0020_auto_20200424_1526'),
    ]

    operations = [
    ]
