# Generated by Django 2.2.7 on 2020-05-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_merge_20200417_1013'),
        ('timetable', '0021_merge_20200427_1030'),
    ]

    operations = [
    ]
