# Generated by Django 2.2.7 on 2020-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_merge_20200427_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmonthstat',
            options={'verbose_name': 'Статистика по мгазину за месяц', 'verbose_name_plural': 'Статистики по мгазинам за месяц'},
        ),
    ]
