# Generated by Django 2.2.7 on 2020-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0021_merge_20200427_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmonthstat',
            options={'verbose_name': 'Статистика по мгазину за месяц', 'verbose_name_plural': 'Статистики по мгазинам за месяц'},
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='dttm_from',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='dttm_to',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='event',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='is_tablet',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='is_vacancy',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='on_cashbox',
        ),
        migrations.RemoveField(
            model_name='workerdaycashboxdetails',
            name='status',
        ),
        migrations.AddField(
            model_name='workerday',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerdaycashboxdetails',
            name='work_part',
            field=models.FloatField(default=1.0),
        ),
    ]
