# Generated by Django 2.2.7 on 2020-05-13 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_auto_20200512_0956'),
    ]

    operations = [

    ]
