# Generated by Django 2.2.7 on 2020-05-13 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_merge_20200511_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopmonthstat',
            options={'verbose_name': 'Статистика по мгазину за месяц', 'verbose_name_plural': 'Статистики по мгазинам за месяц'},
        ),
        migrations.AlterField(
            model_name='workerday',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='worker_day', related_query_name='worker_day', to=settings.AUTH_USER_MODEL),
        ),
    ]
