# Generated by Django 2.2.7 on 2020-05-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_auto_20200513_0900'),
        ('timetable', '0023_merge_20200511_1239'),
    ]

    operations = [
    ]
