# Generated by Django 2.2.7 on 2020-06-29 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20200629_0902'),
        ('timetable', '0026_merge_20200608_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='is_outsource',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VacancyBlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=128)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Shop')),
            ],
            options={
                'unique_together': {('shop', 'symbol')},
            },
        ),
    ]
