# Generated by Django 2.2.7 on 2020-08-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20200813_1407'),
        ('timetable', '0029_merge_20200811_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network'),
        ),
        migrations.AddField(
            model_name='slot',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worktypename',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cashbox',
            unique_together={('code', 'network')},
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('code', 'network')},
        ),
        migrations.AlterUniqueTogether(
            name='worktypename',
            unique_together={('code', 'network')},
        ),
    ]
