# Generated by Django 2.2.7 on 2020-08-13 14:07

from django.db import migrations, models
import django.db.models.deletion

def set_network(apps, schema_editor):
    network = apps.get_model('base', 'Network').objects.get(name='Base network')
    apps.get_model('timetable', 'WorkTypeName').objects.filter(network__isnull=True).update(network=network)
    apps.get_model('timetable', 'Slot').objects.filter(network__isnull=True).update(network=network)
    apps.get_model('timetable', 'Cashbox').objects.filter(network__isnull=True).update(network=network)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20200831_0617'),
        ('timetable', '0029_merge_20200811_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network'),
        ),
        migrations.AddField(
            model_name='slot',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worktypename',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cashbox',
            unique_together={('code', 'network')},
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('code', 'network')},
        ),
        migrations.AlterUniqueTogether(
            name='worktypename',
            unique_together={('code', 'network')},
        ),
        migrations.RunPython(set_network)
    ]
