# Generated by Django 2.2.7 on 2020-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0030_merge_20200813_1105'),
        ('timetable', '0030_auto_20200813_1407'),
    ]

    operations = [
    ]
