# Generated by Django 2.2.7 on 2020-11-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0040_workerday_crop_work_hours_by_shop_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ['name'], 'verbose_name': 'Рабочее место ', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['name'], 'verbose_name': 'Слот', 'verbose_name_plural': 'Слоты'},
        ),
        migrations.AlterModelOptions(
            name='worktypename',
            options={'ordering': ['name'], 'verbose_name': 'Название типа работ', 'verbose_name_plural': 'Названия типов работ'},
        ),
    ]
