# Generated by Django 2.2.7 on 2020-12-01 20:00

from django.conf import settings
from django.db import migrations

from django.db.models import OuterRef, Subquery


def remove_worker_day_duplicates(apps, schema_editor):
    # TODO: продумать логику удаления
    WorkerDay = apps.get_model('timetable', 'WorkerDay')
    pc_subq = WorkerDay.objects.filter(
        dt=OuterRef('dt'),
        worker=OuterRef('worker'),
        is_fact=OuterRef('is_fact'),
        is_approved=OuterRef('is_approved'),
    ).order_by('-id').values_list('id', flat=True)[1:]
    WorkerDay.objects.filter(id__in=Subquery(pc_subq)).delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0041_auto_20201127_1315'),
    ]

    operations = [
        migrations.RunPython(remove_worker_day_duplicates, migrations.RunPython.noop)
    ]
