# Generated by Django 2.2.7 on 2020-12-01 20:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0042_auto_20201201_2000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workerday',
            unique_together={('dt', 'worker', 'is_fact', 'is_approved')},
        ),
        migrations.AlterIndexTogether(
            name='workerday',
            index_together=set(),
        ),
    ]
