# Generated by Django 2.2.7 on 2021-01-20 09:47

from django.db import migrations


def add_timetable_plan_and_fact_hours(apps, schema_editor):
    schema_editor.execute(
        """
        create or replace view timetable_plan_and_fact_hours as
        select string_agg(wd.id::text, '-'::text order by wd.is_fact) as id,
               wd.dt AS dt,
               wd.shop_id AS shop_id,
               s.name AS shop_name,
               s.code AS shop_code,
               wd.worker_id AS worker_id,
               wd.type as wd_type,
               concat(u.last_name, ' ', u.first_name, ' ', u.middle_name) AS worker_fio,
               coalesce(round((sum(date_part('epoch'::text, GREATEST(wd.work_hours, '00:00:00'::interval)) / 3600::double precision) FILTER (WHERE wd.is_fact is True))::numeric, 2), 0::double precision) AS fact_work_hours,
               coalesce(round((sum(date_part('epoch'::text, GREATEST(wd.work_hours, '00:00:00'::interval)) / 3600::double precision) FILTER (WHERE wd.is_fact is False))::numeric, 2), 0::double precision) AS plan_work_hours,
               (min(dttm_work_start) filter (where wd.is_fact is True) > min(dttm_work_start) filter (where wd.is_fact is False))::int AS late_arrival,
               (max(dttm_work_end) filter (where wd.is_fact is True) < max(dttm_work_end) filter (where wd.is_fact is False))::int AS early_departure,
               CASE WHEN (count(*) FILTER (WHERE wd.is_fact is False and wd.is_vacancy is True)) = 1 THEN True ELSE False END as is_vacancy,
               (count(*) FILTER (WHERE wd.is_fact is True and wd.dttm_work_start is not null) + count(*) FILTER (WHERE wd.is_fact is True and wd.dttm_work_end is not null))::int as ticks_fact_count,
               (coalesce(count(*) FILTER (WHERE wd.is_fact is False and wd.type='W'), 0) * 2)::int as ticks_plan_count,
               u.username as worker_username,
               coalesce(wd_details_wt_name.name, '') as work_type_name,
               DATE_TRUNC('minute', min(dttm_work_start) filter (where wd.is_fact is False)) AS dttm_work_start_plan,
               DATE_TRUNC('minute', max(dttm_work_end) filter (where wd.is_fact is False)) AS dttm_work_end_plan,
               DATE_TRUNC('minute', min(dttm_work_start) filter (where wd.is_fact is True)) AS dttm_work_start_fact,
               DATE_TRUNC('minute', max(dttm_work_end) filter (where wd.is_fact is True)) AS dttm_work_end_fact
        from timetable_workerday wd
                 inner join base_shop s on wd.shop_id = s.id
                 inner join base_user u on wd.worker_id = u.id
                 left join timetable_workerdaycashboxdetails wd_details on wd.id = wd_details.worker_day_id
                 left join timetable_worktype wd_details_wt on wd_details.work_type_id = wd_details_wt.id
                 left join timetable_worktypename wd_details_wt_name on wd_details_wt.work_type_name_id = wd_details_wt_name.id
        where wd.is_approved is True
            and NOT (wd.employment_id IS NULL AND wd.type = 'W' AND wd.worker_id IS NOT NULL)
        group by wd.dt,
                 wd.worker_id,
                 wd.type,
                 u.username,
                 concat(u.last_name, ' ', u.first_name, ' ', u.middle_name),
                 wd.shop_id,
                 s.name,
                 s.code,
                 coalesce(wd_details_wt_name.name, '')
        ;
        """
    )


def drop_timetable_plan_and_fact_hours(apps, schema_editor):
    schema_editor.execute("drop view if exists timetable_plan_and_fact_hours;")


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0044_merge_20201209_1450'),
    ]

    operations = [
        migrations.RunPython(add_timetable_plan_and_fact_hours, drop_timetable_plan_and_fact_hours)
    ]
