# Generated by Django 2.2.7 on 2021-01-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0046_planandfacthours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='dttm_work_start_tabel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerday',
            name='dttm_work_end_tabel',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
