# Generated by Django 2.2.7 on 2021-02-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0048_auto_20210210_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdCal',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('dt', models.DateField()),
                ('norm_hours', models.FloatField()),
            ],
            options={
                'db_table': 'prod_cal',
                'managed': False,
            },
        ),
    ]
