# Generated by Django 2.2.16 on 2021-03-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0050_merge_20210226_0436'),
        ('timetable', '0050_attendancerecords_dt'),
    ]

    operations = [
    ]
