# Generated by Django 2.2.16 on 2021-03-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0051_auto_20210304_1525'),
        ('timetable', '0050_attendancerecords_dt'),
    ]

    operations = [
    ]
