# Generated by Django 2.2.16 on 2021-03-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0052_merge_20210304_1559'),
        ('timetable', '0052_merge_20210304_1533'),
    ]

    operations = [
    ]
