# Generated by Django 2.2.16 on 2021-03-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0053_merge_20210305_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Доступен для изменения/подтверждения только определенным группам доступа (настраивается)', verbose_name='Защищенный день'),
        ),
    ]
