# Generated by Django 2.2.16 on 2021-03-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0058_merge_20210324_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentworktype',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_types', to='base.Employment'),
        ),
        migrations.AlterField(
            model_name='workerday',
            name='employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Employment'),
        ),
    ]
