# Generated by Django 2.2.16 on 2021-04-15 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0090_merge_20210405_0558'),
        ('timetable', '0060_auto_20210412_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerday',
            name='tabel_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterUniqueTogether(
            name='workerday',
            unique_together={('dt', 'worker', 'employment', 'is_fact', 'is_approved')},
        ),
        # TODO: заполнить employment_id (если есть активный) у всех дней, где не заполнен
    ]
