# Generated by Django 2.2.16 on 2021-04-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0062_fill_employee_and_update_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerday',
            name='worker',
        ),
    ]
