# Generated by Django 2.2.16 on 2021-04-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0063_remove_workerday_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerconstraint',
            name='worker',
        ),
    ]
