# Generated by Django 2.2.16 on 2021-05-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0066_workerday_outsources'),
        ('timetable', '0067_auto_20210503_1851'),
    ]

    operations = [
    ]
