# Generated by Django 2.2.16 on 2021-05-13 09:20

from django.db import migrations


def update_plan_and_fact_hours(apps, schema_editor):
    schema_editor.execute("""\
        create or replace view plan_and_fact_hours as
        select pc.dt                                                      AS "Дата",
               pc.shop_id                                                 AS "ID Магазина",
               tt_pf.shop_name                                            AS "Магазин",
               tt_pf.shop_code                                            AS "Код магазина",
               pc.employee_id::bigint                                     AS "ID Сотрудника",
               tt_pf.worker_fio                                           AS "Сотрудник",
               round(tt_pf.fact_work_hours::numeric, 2)::double precision AS "Фактические часы работы",
               round(tt_pf.plan_work_hours::numeric, 2)::double precision AS "Плановые часы работы",
               tt_pf.late_arrival                                         AS "Опоздания",
               tt_pf.early_departure                                      AS "Ранний уход",
               tt_pf.is_vacancy::int                                      as "Вакансия",
               tt_pf.is_vacancy                                           as "is_vacancy",
               tt_pf.ticks_fact_count                                     as "К-во отметок факт",
               tt_pf.ticks_plan_count                                     as "К-во отметок план",
               tt_pf.worker_username                                      as "Табельный номер",
               tt_pf.work_type_name                                       as "Тип работ",
               tt_pf.auto_created_plan                                    as "Авт-ки созданный план",
               tt_pf.auto_created_fact                                    as "Авт-ки созданный факт",
               tt_pf.tabel_code                                           AS "Табельный номер трудоустройства",
               tt_pf.worker_id                                            AS "ID Пользователя",
               tt_pf.shop_network                                         AS "Сеть Подразделения",
               tt_pf.user_network                                         AS "Сеть Сотрудника",
               tt_pf.is_outsource::int                                    as "Аутсорс",
               ((select sum(pc2.norm_hours) / COALESCE(NULLIF(count(pc2.id), 0), 1)
                 from prod_cal pc2
                 where True
                   and date_trunc('month', pc2.dt) = date_trunc('month', pc.dt)
                   and pc2.employee_id = pc.employee_id
                   and pc2.shop_id = pc.shop_id
                ) / COALESCE(NULLIF((select count(*)
                     from timetable_plan_and_fact_hours tt_pf2
                     where True
                       and tt_pf2.dt = pc.dt
                       and tt_pf2.employee_id = pc.employee_id
                       and tt_pf2.shop_id = pc.shop_id), 0), 1)
                   )                                                      as "Норма часов (для суммы)"
        from prod_cal pc
                 left join timetable_plan_and_fact_hours tt_pf
                           on tt_pf.dt = pc.dt and tt_pf.employee_id = pc.employee_id and tt_pf.shop_id = pc.shop_id 
                           and tt_pf.wd_type = 'W'
        where True
            and pc.dt >= '2020-01-01'
            and pc.dt < (now() + interval '1 years')
        order by pc.dt;
""")


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0068_merge_20210505_0623'),
    ]

    operations = [
        migrations.RunPython(update_plan_and_fact_hours, migrations.RunPython.noop),
    ]
