# Generated by Django 2.2.16 on 2021-05-14 14:10

from django.db import migrations

def update_plan_and_fact_hours(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0069_auto_20210513_0920'),
    ]

    operations = [
        migrations.RunPython(update_plan_and_fact_hours, migrations.RunPython.noop),
    ]
