# Generated by Django 2.2.16 on 2021-05-14 14:10

from django.db import migrations

def update_plan_and_fact_hours(apps, schema_editor):
    schema_editor.execute("""\
        CREATE OR REPLACE VIEW plan_and_fact_hours as
        SELECT pc.dt AS "Дата",
            pc.shop_id AS "ID Магазина",
            tt_pf.shop_name AS "Магазин",
            pc.code AS "Код магазина",
            pc.employee_id::bigint AS "ID Сотрудника",
            tt_pf.worker_fio AS "Сотрудник",
            round(tt_pf.fact_work_hours::numeric, 2)::double precision AS "Фактические часы работы",
            round(tt_pf.plan_work_hours::numeric, 2)::double precision AS "Плановые часы работы",
            tt_pf.late_arrival AS "Опоздания",
            tt_pf.early_departure AS "Ранний уход",
            tt_pf.is_vacancy::integer AS "Вакансия",
            tt_pf.is_vacancy,
            tt_pf.ticks_fact_count AS "К-во отметок факт",
            tt_pf.ticks_plan_count AS "К-во отметок план",
            tt_pf.worker_username AS "Табельный номер",
            tt_pf.work_type_name AS "Тип работ",
            tt_pf.auto_created_plan AS "Авт-ки созданный план",
            tt_pf.auto_created_fact AS "Авт-ки созданный факт",
            tt_pf.tabel_code AS "Табельный номер трудоустройства",
            tt_pf.worker_id AS "ID Пользователя",
            tt_pf.shop_network AS "Сеть Подразделения",
            tt_pf.user_network AS "Сеть Сотрудника",
            tt_pf.is_outsource::integer AS "Аутсорс",
            (( SELECT sum(pc2.norm_hours) / COALESCE(NULLIF(count(pc2.id), 0), 1::bigint)::double precision
                   FROM prod_cal pc2
                  WHERE true AND date_trunc('month'::text, pc2.dt::timestamp with time zone) = date_trunc('month'::text, pc.dt::timestamp with time zone) AND pc2.employee_id = pc.employee_id AND pc2.shop_id = pc.shop_id)) / COALESCE(NULLIF(( SELECT count(*) AS count
                   FROM timetable_plan_and_fact_hours tt_pf2
                  WHERE true AND tt_pf2.dt = pc.dt AND tt_pf2.employee_id = pc.employee_id AND tt_pf2.shop_id = pc.shop_id), 0), 1::bigint)::double precision AS "Норма часов (для суммы)"
           FROM prod_cal pc
             LEFT JOIN timetable_plan_and_fact_hours tt_pf ON tt_pf.dt = pc.dt AND tt_pf.employee_id = pc.employee_id AND tt_pf.shop_id = pc.shop_id AND tt_pf.wd_type::text = 'W'::text
          WHERE true AND pc.dt >= '2020-01-01'::date AND pc.dt < (now() + '1 year'::interval);
""")

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0069_auto_20210513_0920'),
    ]

    operations = [
        migrations.RunPython(update_plan_and_fact_hours, migrations.RunPython.noop),
    ]
