# Generated by Django 2.2.16 on 2021-05-17 20:43

from django.db import migrations


def update_plan_and_fact_hours(apps, schema_editor):
    schema_editor.execute("""\
        CREATE OR REPLACE VIEW plan_and_fact_hours as
        SELECT tt_pf.dt                                                   AS "Дата",
               tt_pf.shop_id                                              AS "ID Магазина",
               tt_pf.shop_name                                            AS "Магазин",
               tt_pf.shop_code                                            AS "Код магазина",
               tt_pf.employee_id::bigint                                  AS "ID Сотрудника",
               tt_pf.worker_fio                                           AS "Сотрудник",
               round(tt_pf.fact_work_hours::numeric, 2)::double precision AS "Фактические часы работы",
               round(tt_pf.plan_work_hours::numeric, 2)::double precision AS "Плановые часы работы",
               tt_pf.late_arrival                                         AS "Опоздания",
               tt_pf.early_departure                                      AS "Ранний уход",
               tt_pf.is_vacancy::integer                                  AS "Вакансия",
               tt_pf.is_vacancy,
               tt_pf.ticks_fact_count                                     AS "К-во отметок факт",
               tt_pf.ticks_plan_count                                     AS "К-во отметок план",
               tt_pf.worker_username                                      AS "Табельный номер",
               tt_pf.work_type_name                                       AS "Тип работ",
               tt_pf.auto_created_plan                                    AS "Авт-ки созданный план",
               tt_pf.auto_created_fact                                    AS "Авт-ки созданный факт",
               tt_pf.tabel_code                                           AS "Табельный номер трудоустройства",
               tt_pf.worker_id                                            AS "ID Пользователя",
               tt_pf.shop_network                                         AS "Сеть Подразделения",
               tt_pf.user_network                                         AS "Сеть Сотрудника",
               tt_pf.is_outsource::integer                                AS "Аутсорс",
               null                                                       as "Норма часов (для суммы)"
        from timetable_plan_and_fact_hours tt_pf
        where tt_pf.wd_type::text = 'W'::text
        UNION ALL
        SELECT pc.dt                                                                                 AS "Дата",
               pc.shop_id                                                                            AS "ID Магазина",
               null::character varying(128)                                                          AS "Магазин",
               pc.code                                                                               AS "Код магазина",
               pc.employee_id::bigint                                                                AS "ID Сотрудника",
               null                                                                                  AS "Сотрудник",
               null                                                                                  AS "Фактические часы работы",
               null                                                                                  AS "Плановые часы работы",
               null                                                                                  AS "Опоздания",
               null                                                                                  AS "Ранний уход",
               null                                                                                  AS "Вакансия",
               null                                                                                  AS is_vacancy,
               null                                                                                  AS "К-во отметок факт",
               null                                                                                  AS "К-во отметок план",
               null::character varying(150)                                                          AS "Табельный номер",
               null                                                                                  AS "Тип работ",
               null                                                                                  AS "Авт-ки созданный план",
               null                                                                                  AS "Авт-ки созданный факт",
               null::character varying(64)                                                           AS "Табельный номер трудоустройства",
               pc.user_id                                                                            AS "ID Пользователя",
               null::character varying(128)                                                          AS "Сеть Подразделения",
               null::character varying(128)                                                          AS "Сеть Сотрудника",
               null::integer                                                                         AS "Аутсорс",
               (SELECT sum(pc2.norm_hours) / COALESCE(NULLIF(count(pc2.id), 0), 1::bigint)::double precision
                FROM prod_cal pc2
                WHERE pc.employee_id = pc2.employee_id
                  and date_trunc('month'::text, pc.dt::timestamp with time zone) =
                      date_trunc('month'::text, pc2.dt::timestamp with time zone))::double precision AS "Норма часов (для суммы)"
        from prod_cal pc
        WHERE pc.dt >= '2020-01-01'::date
          AND pc.dt < (now() + '2 months'::interval);
""")


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0070_auto_20210514_1410'),
    ]

    operations = [
        migrations.RunPython(update_plan_and_fact_hours, migrations.RunPython.noop),
    ]
