# Generated by Django 2.2.16 on 2021-05-17 20:43

from django.db import migrations


def update_plan_and_fact_hours(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0070_auto_20210514_1410'),
    ]

    operations = [
        migrations.RunPython(update_plan_and_fact_hours, migrations.RunPython.noop),
    ]
