# Generated by Django 2.2.16 on 2021-08-11 17:59

from django.db import migrations, models
import django.db.models.deletion
import src.util.mixins.bulk_update_or_create


def fill_new_outsources_table(apps, schema_editor):
    WorkerDayOutsourceNetwork = apps.get_model('timetable', 'WorkerDayOutsourceNetwork')
    WorkerDay = apps.get_model('timetable', 'WorkerDay')

    WorkerDayOutsourceNetwork.objects.bulk_create(
        [
            WorkerDayOutsourceNetwork(workerday_id=o.workerday_id, network_id=o.network_id)
            for o in WorkerDay.outsources.through.objects.all()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0121_auto_20210811_1753'),
        ('timetable', '0078_auto_20210803_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDayOutsourceNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Network')),
                ('workerday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.WorkerDay')),
            ],
            options={
                'abstract': False,
            },
            bases=(src.util.mixins.bulk_update_or_create.BatchUpdateOrCreateModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='workerday',
            name='allowed_outsource_networks',
            field=models.ManyToManyField(blank=True, help_text='Аутсорс сети, которые могут откликнуться на данную вакансию', through='timetable.WorkerDayOutsourceNetwork', to='base.Network'),
        ),
        migrations.RunPython(fill_new_outsources_table, migrations.RunPython.noop),
    ]
