# Generated by Django 2.2.16 on 2021-08-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0078_auto_20210803_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerday',
            name='closest_plan_approved',
            field=models.ForeignKey(blank=True, help_text='Используется в факте подтвержденном (созданном на основе отметок) для связи с планом подтвержденным', null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.WorkerDay'),
        ),
    ]
