# Generated by Django 2.2.16 on 2021-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0085_auto_20210822_1242'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workerday',
            name='unique_dt_employee_is_fact_is_approved_if_not_workday',
        ),
        migrations.AddConstraint(
            model_name='workerday',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, type_id__in=['W', 'Q', 'T', 'SD', 'R']), fields=('dt', 'employee', 'is_fact', 'is_approved'), name='unique_dt_employee_is_fact_is_approved_if_not_workday'),
        ),
    ]
