# Generated by Django 2.2.16 on 2021-09-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0086_auto_20210822_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workerdaytype',
            options={'ordering': ['-ordering', 'name'], 'verbose_name': 'Тип дня сотрудника', 'verbose_name_plural': 'Типы дней сотрудников'},
        ),
        migrations.AlterField(
            model_name='workerday',
            name='closest_plan_approved',
            field=models.ForeignKey(blank=True, help_text='Используется в факте (и в черновике и подтв. версии) для связи с планом подтвержденным', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_facts', to='timetable.WorkerDay'),
        ),
        migrations.AlterField(
            model_name='workerdaytype',
            name='is_system',
            field=models.BooleanField(default=False, editable=False, verbose_name='Системный (нельзя удалять)'),
        ),
    ]
