# Generated by Django 2.2.24 on 2021-10-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0093_auto_20211019_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timesheet',
        ),
    ]
