# Generated by Django 2.2.24 on 2021-10-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0094_delete_timesheet'),
        ('timetable', '0092_auto_20211018_0510'),
    ]

    operations = [
    ]
