# Generated by Django 2.2.24 on 2021-10-22 16:39

from django.db import migrations
from django.db.models import Q, OuterRef, Subquery, F

from src.base.models import Employment


def fix_wd_employments(apps, schema_editor):
    WorkerDay = apps.get_model('timetable', 'WorkerDay')
    WorkerDay.objects.filter(
        Q(employee__isnull=False),
        Q(employment__isnull=True) |
        Q(Q(dt__lt=F('employment__dt_hired')) | Q(dt__gt=F('employment__dt_fired'))),
    ).exclude(
        type_id='E',
    ).update(
        employment_id=Subquery(Employment.objects.filter(
            Q(dt_hired__isnull=True) | Q(dt_hired__lte=OuterRef('dt')),
            Q(dt_fired__isnull=True) | Q(dt_fired__gte=OuterRef('dt')),
            employee_id=OuterRef('employee_id'),
        ).order_by('-is_visible', '-norm_work_hours').values('id')[:1]),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0097_auto_20211021_2126'),
    ]

    operations = [
        migrations.RunPython(fix_wd_employments, migrations.RunPython.noop)
    ]
