# Generated by Django 2.2.24 on 2021-10-22 08:27

from django.db import migrations
from django.db.models import Q, OuterRef, Subquery

from src.base.models import Employment


def fill_timesheet_items_position_and_shop(apps, schema_editor):
    TimesheetItem = apps.get_model('timetable', 'TimesheetItem')
    TimesheetItem.objects.filter(
        shop__isnull=True,
    ).update(
        shop_id=Subquery(Employment.objects.filter(
            Q(dt_hired__isnull=True) | Q(dt_hired__lte=OuterRef('dt')),
            Q(dt_fired__isnull=True) | Q(dt_fired__gte=OuterRef('dt')),
            employee_id=OuterRef('employee_id'),
        ).order_by('-is_visible', '-norm_work_hours').values('shop_id')[:1]),
    )
    TimesheetItem.objects.filter(
        position__isnull=True,
    ).update(
        position_id=Subquery(Employment.objects.filter(
            Q(dt_hired__isnull=True) | Q(dt_hired__lte=OuterRef('dt')),
            Q(dt_fired__isnull=True) | Q(dt_fired__gte=OuterRef('dt')),
            employee_id=OuterRef('employee_id'),
        ).order_by('-is_visible', '-norm_work_hours').values('position_id')[:1]),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0098_auto_20211022_1639'),
    ]

    operations = [
        migrations.RunPython(fill_timesheet_items_position_and_shop, migrations.RunPython.noop)
    ]
