# Generated by Django 2.2.24 on 2021-10-29 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0094_workerday_source'),
        ('timetable', '0100_auto_20211026_2049'),
    ]

    operations = [
    ]
