# Generated by Django 3.2.9 on 2021-11-12 08:38

from django.db import migrations


def fill_has_detail_for_workday(apps, schema_editor):
    WorkerDayType = apps.get_model('timetable', 'WorkerDayType')
    WorkerDayType.objects.filter(
        code='W',
    ).update(
        has_details=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0105_auto_20211111_0002'),
    ]

    operations = [
        migrations.RunPython(fill_has_detail_for_workday, migrations.RunPython.noop)
    ]
