# Generated by Django 3.2.9 on 2021-11-23 05:43

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0106_auto_20211112_0838'),
        ('base', '0147_auto_20211122_0437'),
    ]

    operations = []
