# Generated by Django 3.2.9 on 2021-11-23 05:43

from django.db import migrations, models
from datetime import timedelta
from django.db.models import functions

def fix_attendance_records(apps, schema_editor):
    from src.timetable.models import AttendanceRecords
    WorkerDay = apps.get_model('timetable', 'WorkerDay')
    WorkerDay.objects.annotate(
        delta=functions.Cast(
            models.F('dttm_work_end') - models.F('dttm_work_start'), 
            models.DurationField(),
        )
    ).filter(
        type_id='W', 
        delta__gte=timedelta(days=2),
    ).update(
        dttm_work_end=None,
        dttm_work_end_tabel=None,
        work_hours=timedelta(0),
    )
    records_to_fix = AttendanceRecords.objects.annotate(
        delta=functions.Cast(
            models.F('dttm') - models.F('dt'), 
            models.DurationField(),
        ),
    ).filter(delta__gte=timedelta(days=2))
    for record in records_to_fix:
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0108_auto_20211126_0857'),
    ]

    operations = [
        migrations.RunPython(fix_attendance_records, migrations.RunPython.noop)
    ]
