# Generated by Django 3.2.9 on 2021-12-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0109_auto_20211201_0516'),
        ('timetable', '0109_merge_0108_auto_20211126_0857_0108_auto_20211201_1312'),
    ]

    operations = [
    ]
