# Generated by Django 3.2.9 on 2022-01-12 18:01

from django.db import migrations, models

CREATE = 'C'
UPDATE = 'U'


def fill_wd_perms(apps, schema_editor):
    WorkerDayPermission = apps.get_model('timetable', 'WorkerDayPermission')
    GroupWorkerDayPermission = apps.get_model('timetable', 'GroupWorkerDayPermission')
    for wdp in WorkerDayPermission.objects.filter(action='CU'):
        group_worker_day_permissions = list(wdp.groupworkerdaypermission_set.values('group_id', 'limit_days_in_past', 'limit_days_in_future'))
        old_id = wdp.id
        for action in [CREATE, UPDATE]:
            wdp.action = action
            wdp.id = None
            wdp.save()
            GroupWorkerDayPermission.objects.bulk_create(
                GroupWorkerDayPermission(
                    worker_day_permission=wdp,
                    **group_worker_day_permission_dict
                ) for group_worker_day_permission_dict in group_worker_day_permissions
            )

        wdp.id = old_id
        wdp.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0164_auto_20211223_1107'),
        ('timetable', '0111_auto_20211216_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupworkerdaypermission',
            name='employee_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Любые сотрудники моих магазинов'), (2, 'Подчиненные сотрудники'), (3, 'Сотрудники аутсорс компании')], default=2, verbose_name='Тип сотрудника'),
        ),
        migrations.AddField(
            model_name='groupworkerdaypermission',
            name='shop_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Мои магазины'), (2, 'Любые магазин моей сети'), (3, 'Магазины аутсорс сетей'), (4, 'Магазины сети аутсорс-клиента')], default=2, help_text='Актуально только для рабочих типов дней', verbose_name='Тип магазина'),
        ),
        migrations.AddField(
            model_name='groupworkerdaypermission',
            name='allow_actions_on_vacancies',
            field=models.BooleanField(default=True, help_text='Вакансией в данном случае является день, если он был явно создан как вакансия, либо если магазин в трудоустройстве не совпадает с магазином выхода (актуально для рабочий типов дней)', verbose_name='Разрешить действия над вакансиями'),
        ),
        migrations.AlterField(
            model_name='workerdaypermission',
            name='action',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Remove'), ('A', 'Approve')], max_length=2, verbose_name='Действие'),
        ),
        migrations.AlterUniqueTogether(
            name='groupworkerdaypermission',
            unique_together={('group', 'worker_day_permission', 'employee_type', 'shop_type')},
        ),
        migrations.RunPython(fill_wd_perms, migrations.RunPython.noop),
    ]
