# Generated by Django 3.2.9 on 2022-02-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0112_auto_20220112_1801'),
        ('timetable', '0112_auto_20220203_1319'),
    ]

    operations = [
    ]
