# Generated by Django 3.2.9 on 2022-02-17 07:41

from django.db import migrations

def delete_worker_day_details_for_non_workday_types(apps, schema_editor):
    WorkerDayCashboxDetails = apps.get_model('timetable', 'WorkerDayCashboxDetails')
    print('delete_worker_day_details_for_non_workday_types', WorkerDayCashboxDetails.objects.exclude(
        worker_day__type__has_details=True,
    ).delete())


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0115_auto_20220211_1326'),
    ]

    operations = [
        migrations.RunPython(delete_worker_day_details_for_non_workday_types, migrations.RunPython.noop),
    ]
