# Generated by Django 3.2.9 on 2022-03-29 08:47

from django.db import migrations, models
import django.db.models.deletion
import src.util.mixins.bulk_update_or_create


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0171_merge_20220222_1219'),
        ('timetable', '0117_auto_20220321_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('dt_max_hours', models.DurationField(blank=True, null=True)),
                ('restriction_type', models.PositiveSmallIntegerField(choices=[(1, 'Максимальное количество часов на одну дату у сотрудника')], default=1)),
                ('is_vacancy', models.BooleanField(blank=True, default=None, null=None, verbose_name='None -- для любой смены (осн. или доп.), True -- только для доп. смен, False -- только для осн. смен')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.workerposition')),
                ('worker_day_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.workerdaytype')),
            ],
            options={
                'verbose_name': 'Ограничение',
                'verbose_name_plural': 'Ограничения',
            },
            bases=(src.util.mixins.bulk_update_or_create.BatchUpdateOrCreateModelMixin, models.Model),
        ),
    ]
