# Generated by Django 3.2.9 on 2022-09-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0119_merge_20220330_1321'),
        ('timetable', '0120_manual_20220829'),
    ]

    operations = [
    ]
