# Generated by Django 3.2.9 on 2022-09-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0121_merge_0119_merge_20220330_1321_0120_manual_20220829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='restriction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Максимальное количество часов на одну дату у сотрудника'), (2, 'Настройки нормы не установлены (через должность, либо через трудоустройство)')], default=1),
        ),
        migrations.AlterField(
            model_name='workerdaytype',
            name='get_work_hours_method',
            field=models.CharField(blank=True, choices=[('average_sawh_hours', 'Расчет часов на основе среднемесячного значения рекомендуемой нормы'), ('norm_hours', 'Расчет часов на основе нормы по производственному календарю'), ('manual', 'Ручное проставление часов'), ('manual_or_average_sawh_hours', 'Ручное проставление часов или среднемесячное значение рекомендуемой нормы')], help_text='Актуально для нерабочих типов дней. Для рабочих типов кол-во часов считается на основе времени начала и окончания.', max_length=32, verbose_name='Способ получения рабочих часов'),
        ),
    ]
