# Generated by Django 3.2.9 on 2022-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0122_auto_20220916_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='restriction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Maximum number of hours for one date for employee'), (2, 'Norm settings are not configured (through position or employment)')], default=1),
        ),
        migrations.AlterField(
            model_name='workerdaytype',
            name='get_work_hours_method',
            field=models.CharField(blank=True, choices=[('average_sawh_hours', 'Hours calculation based on average monthly value of the recommended norm'), ('norm_hours', 'Hours calculation based on production calendar norm'), ('manual', 'Manual setting of hours'), ('manual_or_average_sawh_hours', 'Manual setting of hours or average monthly value of the recommended norm')], help_text='Актуально для нерабочих типов дней. Для рабочих типов кол-во часов считается на основе времени начала и окончания.', max_length=32, verbose_name='Способ получения рабочих часов'),
        ),
    ]
