# Generated by Django 3.2.9 on 2022-12-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0128_auto_20221205_0833'),
        ('timetable', '0128_auto_20221206_2216'),
    ]

    operations = [
    ]
