# Generated by Django 3.2.9 on 2023-01-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0130_alter_workerday_code'),
        ('timetable', '0130_merge_20221213_1224'),
    ]

    operations = [
    ]
