version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - ../../:/code
    ports:
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - db
      - redis
    links:
      - db:postgres
      - redis:redis

  redis:
    image: redis:5.0.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'