# Generated by Django 2.2.16 on 2021-05-26 23:31

from django.db import migrations


def add_task_perms(apps, schema_editor):
    Group = apps.get_model('base', 'Group')
    FunctionGroup = apps.get_model('base', 'FunctionGroup')
    for group in Group.objects.all():
        if group:
            FunctionGroup.objects.get_or_create(
                group=group,
                func='Task',
                method='GET',
                access_type='A',
            )


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_task_perms, migrations.RunPython.noop),
    ]
