# Generated by Django 3.2.9 on 2022-02-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpermission',
            name='use_rls',
            field=models.BooleanField(default=False),
        ),
    ]
