# Generated by Django 3.2.9 on 2022-02-22 09:10

from django.db import migrations, models
import django.db.models.deletion
import src.util.mixins.bulk_update_or_create


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0169_auto_20220214_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('code', models.CharField(blank=True, max_length=64, null=True, verbose_name='Код')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('dt_from', models.DateField()),
                ('dt_to', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='base.employee')),
                ('medical_document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='med_docs.medicaldocumenttype')),
            ],
            options={
                'abstract': False,
            },
            bases=(src.util.mixins.bulk_update_or_create.BatchUpdateOrCreateModelMixin, models.Model),
        ),
    ]
