# Generated by Django 3.2.9 on 2022-02-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0169_auto_20220214_1146'),
        ('med_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'verbose_name': 'Период актуальности медицинского документа', 'verbose_name_plural': 'Периоды актуальности медицинского документа'},
        ),
        migrations.AlterModelOptions(
            name='medicaldocumenttype',
            options={'verbose_name': 'Тип медицинского документа', 'verbose_name_plural': 'Типы медицинских документов'},
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='dt_from',
            field=models.DateField(verbose_name='Дата "с" (включительно)'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='dt_to',
            field=models.DateField(verbose_name='Дата "по" (включительно)'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='base.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='medical_document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='med_docs.medicaldocumenttype', verbose_name='Тип медицинского документа'),
        ),
    ]
