# Generated by Django 2.2.7 on 2020-12-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20201209_1209'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhistory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Shop'),
        ),
    ]
