# Generated by Django 3.2.9 on 2021-11-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhistory',
            name='context',
            field=models.JSONField(default=dict),
        ),
    ]
