# Generated by Django 3.2.9 on 2022-09-16 13:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventtype_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhistory',
            name='context',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
