# Generated by Django 2.2.7 on 2020-12-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventhistory_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventhistory',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Network'),
        ),
    ]
