# Generated by Django 3.2.9 on 2022-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi', '0002_reportpermission_use_rls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpermission',
            name='use_rls',
        ),
        migrations.AddField(
            model_name='report',
            name='use_rls',
            field=models.BooleanField(default=False),
        ),
    ]
