# Generated by Django 2.2.3 on 2019-07-26 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTick',
            fields=[
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConnecter',
            fields=[
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dttm', models.DateTimeField(auto_now_add=True)),
                ('verified_score', models.FloatField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photo/%Y/%m')),
                ('place_tick', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='recognition.PlaceTick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
