# Generated by Django 2.2.3 on 2019-07-26 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetick',
            name='dttm_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tick',
            name='dttm_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userconnecter',
            name='dttm_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
