# Generated by Django 2.2.3 on 2019-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0006_tick_worker_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='lateness',
            field=models.DurationField(null=True),
        ),
    ]
