# Generated by Django 2.2.3 on 2019-08-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0014_tick_ext_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='type',
            field=models.CharField(choices=[('C', 'coming'), ('L', 'leaving'), ('S', 'break start'), ('E', 'break_end')], default='c', max_length=1),
            preserve_default=False,
        ),
    ]
