# Generated by Django 2.2.3 on 2019-10-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0017_auto_20191004_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tick',
            options={'verbose_name': 'Отметка', 'verbose_name_plural': 'Отметки'},
        ),
        migrations.AlterModelOptions(
            name='tickphoto',
            options={'verbose_name': 'Фотографии отметок', 'verbose_name_plural': 'Фотографии отметок'},
        ),
        migrations.AlterModelOptions(
            name='tickpoint',
            options={'verbose_name': 'Точка отметки', 'verbose_name_plural': 'Точки отметок'},
        ),
        migrations.AlterModelOptions(
            name='userconnecter',
            options={'verbose_name': 'Сопоставление пользователей', 'verbose_name_plural': 'Сопоставления пользователей'},
        ),
        migrations.AddField(
            model_name='tick',
            name='verified_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tick',
            name='tick_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='ticks', to='recognition.TickPoint'),
        ),
        migrations.AlterField(
            model_name='tick',
            name='type',
            field=models.CharField(blank=True, choices=[('C', 'coming'), ('L', 'leaving'), ('S', 'break start'), ('E', 'break_end')], max_length=1, null=True),
        ),
    ]
