# Generated by Django 2.2.3 on 2020-10-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0021_auto_20200515_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tick',
            name='ext_id',
        ),
        migrations.RemoveField(
            model_name='tick',
            name='worker_day',
        ),
    ]
