# Generated by Django 2.2.7 on 2020-11-13 13:34

from django.db import migrations


def set_tick_point_network(apps, schema_editor):
    TickPoint = apps.get_model('recognition', 'TickPoint')
    for tick_point in TickPoint.objects.all().select_related('shop'):
        if tick_point.shop:
            tick_point.network_id = tick_point.shop.network_id
            tick_point.save(update_fields=('network_id',))


class Migration(migrations.Migration):
    dependencies = [
        ('recognition', '0023_auto_20201113_1304'),
    ]

    operations = [
        migrations.RunPython(set_tick_point_network, migrations.RunPython.noop),
    ]
