# Generated by Django 2.2.7 on 2020-11-26 08:35

from django.db import migrations, models

def set_name(apps, schema_editor):
    TickPoint = apps.get_model('recognition', 'TickPoint')
    TickPoint.objects.all().update(
        name=models.F('title'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0024_auto_20201113_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickpoint',
            name='is_active',
        ),
        migrations.RunPython(set_name),
        migrations.RemoveField(
            model_name='tickpoint',
            name='title',
        ),
        migrations.AlterField(
            model_name='tickpoint',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
