# Generated by Django 3.2.9 on 2022-01-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0165_alter_network_download_tabel_template'),
        ('recognition', '0028_tick_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopIpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.shop')),
                ('tick_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.tickpoint')),
            ],
        ),
    ]
