# Generated by Django 3.2.9 on 2022-12-22 08:23

from django.db import migrations, models

def one_time_biometricks_check_field_default(apps, schema_editor):
    Tick = apps.get_model('recognition', 'Tick')
    TickPhoto = apps.get_model('recognition', 'TickPhoto')
    Tick.objects.all().update(biometrics_check=True)
    TickPhoto.objects.all().update(biometrics_check=True)


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0031_alter_tick_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='biometrics_check',
            field=models.BooleanField(default=False, help_text='Was the biometrics service available', verbose_name='biometrics_check'),
        ),
        migrations.AddField(
            model_name='tickphoto',
            name='biometrics_check',
            field=models.BooleanField(default=False, help_text='Was the biometrics service available', verbose_name='biometrics_check'),
        ),
        migrations.RunPython(one_time_biometricks_check_field_default)
    ]
