# Generated by Django 2.2.16 on 2020-12-28 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0071_workerposition_hours_in_a_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('dttm_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('dttm_deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Network')),
            ],
            options={
                'verbose_name': 'Связь с внешними системами',
                'verbose_name_plural': 'Связи с внешними системами',
            },
        ),
        migrations.CreateModel(
            name='UserExternalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integration.ExternalSystem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopExternalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='integration.ExternalSystem')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
