# Generated by Django 2.2.16 on 2021-01-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsystem',
            name='dttm_added',
        ),
        migrations.RemoveField(
            model_name='externalsystem',
            name='dttm_deleted',
        ),
        migrations.RemoveField(
            model_name='externalsystem',
            name='dttm_modified',
        ),
        migrations.RemoveField(
            model_name='externalsystem',
            name='network',
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
    ]
