# Generated by Django 2.2.16 on 2021-06-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_auto_20210609_1900'),
        ('integration', '0005_auto_20210531_0920'),
    ]

    operations = [
    ]
