# Generated by Django 2.2.24 on 2021-09-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('integration', '0007_auto_20210809_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericExternalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64)),
                ('object_id', models.PositiveIntegerField()),
                ('external_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.ExternalSystem')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'unique_together': {('code', 'external_system', 'object_type', 'object_id')},
            },
        ),
    ]
