# Generated by Django 2.2.24 on 2021-09-28 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210928_1208'),
        ('exchange', '0003_auto_20210927_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemexportstrategy',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Period'),
        ),
        migrations.AlterField(
            model_name='systemimportstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('pobeda_import_shop_mapping', 'Импорт сопоставления кодов магазинов (Победа)'), ('pobeda_import_purchases', 'Импорт чеков (Победа)'), ('pobeda_import_brak', 'Импорт списаний (Победа)'), ('pobeda_import_delivery', 'Импорт поставок (Победа)')], max_length=128),
        ),
    ]
