# Generated by Django 2.2.24 on 2021-09-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20210928_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemexportstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('work_hours_pivot_table', 'Сводная таблица по отработанным часам по всем магазинам'), ('plan_and_fact_hours_table', 'Таблица по плановым и факт часам')], max_length=128),
        ),
    ]
