# Generated by Django 2.2.24 on 2021-10-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20210928_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefilesystemconnector',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='exportstrategy',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='importstrategy',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
