# Generated by Django 3.2.9 on 2022-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_auto_20220216_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='importshopmappingstrategy',
            name='csv_delimiter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='csv delimiter'),
        ),
        migrations.AlterField(
            model_name='importhistdatastrategy',
            name='csv_delimiter',
            field=models.CharField(default=';', max_length=1, verbose_name='csv delimiter'),
        ),
    ]
