# Generated by Django 3.2.9 on 2022-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_merge_20221121_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistdatastrategy',
            name='use_total_discounted_price',
            field=models.BooleanField(default=False, verbose_name='Брать ли элементы с учетом финальной суммы со скидкой'),
        ),
    ]