# Generated by Django 3.2.9 on 2022-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_importhistdatastrategy_use_total_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistdatastrategy',
            name='dt_or_dttm_column_name',
            field=models.CharField(max_length=128, verbose_name='Наименование колонки дата или дата+время'),
        ),
        migrations.AlterField(
            model_name='importhistdatastrategy',
            name='shop_num_column_name',
            field=models.CharField(max_length=128, verbose_name='Наименование колонки с номером магазина'),
        ),
    ]
