# Generated by Django 2.2.7 on 2020-02-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200205_0924'),
        ('forecast', '0006_auto_20200205_0739'),
    ]

    operations = [
        migrations.RunSQL("update forecast_operationtypename set code=null where code=''"),
        migrations.AlterField(
            model_name='operationtypename',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
