# Generated by Django 2.2.7 on 2020-03-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtemplate',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
