# Generated by Django 2.2.7 on 2020-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_auto_20200317_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtypename',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
