# Generated by Django 2.2.7 on 2020-05-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_auto_20200427_1438'),
        ('forecast', '0010_auto_20200427_1146'),
    ]

    operations = [
    ]
