# Generated by Django 2.2.7 on 2020-05-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0012_auto_20200512_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationtyperelation',
            options={'verbose_name': 'Отношение типов операций', 'verbose_name_plural': 'Отношения типов операций'},
        ),
    ]
