# Generated by Django 2.2.7 on 2020-07-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0014_merge_20200608_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodclients',
            name='dttm_forecast',
            field=models.DateTimeField(db_index=True),
        ),
    ]
