# Generated by Django 2.2.7 on 2020-07-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20200730_1447'),
        ('forecast', '0014_merge_20200608_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.UUIDField()),
                ('dttm', models.DateTimeField()),
                ('dttm_added', models.DateTimeField(auto_now_add=True)),
                ('dttm_modified', models.DateTimeField(auto_now=True)),
                ('info', models.TextField()),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Shop')),
            ],
            options={
                'verbose_name': 'Чеки',
            },
        ),
    ]
