# Generated by Django 2.2.7 on 2020-08-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0015_auto_20200730_0816'),
        ('forecast', '0017_auto_20200731_1445'),
    ]

    operations = [
    ]
