# Generated by Django 2.2.7 on 2020-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0017_auto_20200731_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='is_aggregated',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
