# Generated by Django 2.2.7 on 2020-08-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0018_merge_20200804_1043'),
        ('forecast', '0016_auto_20200813_1407'),
    ]

    operations = [
    ]
