# Generated by Django 2.2.7 on 2020-09-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0021_auto_20200904_0447'),
        ('forecast', '0022_remove_loadtemplate_status'),
    ]

    operations = [
    ]
