# Generated by Django 2.2.7 on 2020-10-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0028_auto_20201008_0850'),
        ('forecast', '0027_loadtemplate_forecast_params'),
    ]

    operations = [
    ]
