# Generated by Django 2.2.7 on 2020-11-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0028_auto_20201008_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Версия объекта'),
        ),
    ]
