# Generated by Django 2.2.7 on 2020-11-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0029_receipt_version'),
        ('forecast', '0029_auto_20201123_1418'),
    ]

    operations = [
    ]
