# Generated by Django 2.2.16 on 2020-12-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0029_merge_20201020_0815'),
        ('forecast', '0031_auto_20201127_1315'),
    ]

    operations = [
    ]
