# Generated by Django 2.2.16 on 2020-12-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0032_merge_20201209_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtypetemplate',
            name='const_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
