# Generated by Django 2.2.16 on 2020-12-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0032_auto_20201207_2248'),
        ('forecast', '0035_loadtemplate_round_delta'),
    ]

    operations = [
    ]
