# Generated by Django 2.2.16 on 2021-04-23 08:41

from django.db import migrations


def create_daily_earnings_per_user(appsapp, schema_editor):
    schema_editor.execute(
    """
    create or replace view daily_earnings_per_user as
    select
           s.id as shop_id,
           sum(value) FILTER (WHERE otn.code::text = 'income'::text) as income,
           sum(value) FILTER (WHERE otn.code::text = 'clients'::text) as clients,
           pc.dttm_forecast::date as dt,
           s.code as shop_code
    from forecast_periodclients pc
        inner join forecast_operationtype ot on pc.operation_type_id = ot.id
        inner join forecast_operationtypename otn on ot.operation_type_name_id = otn.id
        inner join base_shop s on ot.shop_id = s.id
    where pc.type::text = 'F'::text and otn.code in ('income', 'clients')
    group by s.id, s.code, pc.dttm_forecast::date
    """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0037_auto_20210331_0713'),
        ('timetable', '0062_fill_employee_and_update_views'),
    ]

    operations = [
        migrations.RunPython(create_daily_earnings_per_user, migrations.RunPython.noop)
    ]
