# Generated by Django 2.2.16 on 2021-05-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0038_auto_20210423_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtyperelation',
            name='formula',
            field=models.CharField(max_length=1024),
        ),
    ]
