# Generated by Django 2.2.16 on 2021-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0039_auto_20210528_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtyperelation',
            name='days_of_week',
            field=models.CharField(blank=True, default='[0, 1, 2, 3, 4, 5, 6]', max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='operationtyperelation',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationtyperelation',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationtyperelation',
            name='formula',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
