# Generated by Django 3.2.9 on 2022-02-02 10:05

from django.db import migrations

def update_metabase_to_view(apps, schema_editor):
    schema_editor.execute(
        '''CREATE OR REPLACE VIEW public.metabase_to AS
        SELECT DISTINCT ot.shop_id,
            (timeserie.dttm_forecast)::date AS dt,
            coalesce(sum(timeserie.value) FILTER (WHERE (timeserie.type)::text = 'L'::text), 0) AS plan,
            coalesce(sum(timeserie.value) FILTER (WHERE (timeserie.type)::text = 'F'::text), 0) AS fact
        FROM public.forecast_operationtypename otn
            JOIN public.forecast_operationtype ot ON otn.id = ot.operation_type_name_id
            JOIN public.forecast_periodclients timeserie ON timeserie.operation_type_id = ot.id
        WHERE otn.is_special
        GROUP BY ot.shop_id, ((timeserie.dttm_forecast)::date);
        '''
    )

class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0049_auto_20220112_0646'),
    ]

    operations = [
        migrations.RunPython(update_metabase_to_view, migrations.RunPython.noop),
    ]
