# Generated by Django 3.2.9 on 2022-01-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0049_auto_20220112_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtyperelation',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationtypename',
            name='do_forecast',
            field=models.CharField(choices=[('H', 'Forecast'), ('F', 'Formula'), ('FS', 'Feature serie')], default='H', max_length=2),
        ),
        migrations.AlterField(
            model_name='operationtyperelation',
            name='type',
            field=models.CharField(choices=[('F', 'Формула'), ('P', 'Прогнозирование'), ('C', 'Перекидывание нагрузки между типами работ')], default='F', max_length=1),
        ),
    ]
