# Generated by Django 3.2.9 on 2022-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0054_auto_20220916_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodclients',
            name='dt_report',
            field=models.DateField(verbose_name='report (data file) date'),
        ),
        migrations.AlterField(
            model_name='periodclients',
            name='dttm_forecast',
            field=models.DateTimeField(verbose_name='aggregation date and time'),
        ),
    ]
