# Generated by Django 3.2.9 on 2022-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0057_alter_operationtypetemplate_duplicate_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationtypetemplate',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationtypetemplate',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
