QOS_DEV_STATIC_ENABLED = False
QOS_DEV_CSRF_DISABLED = False
QOS_DEV_AUTOLOGIN_ENABLED = False
QOS_DEV_AUTOLOGIN_USERNAME = None
QOS_DEV_AUTOLOGIN_PASSWORD = None

QOS_SET_TIMETABLE_KEY = None
HOST_IP = '62.109.30.224:8000' # dev
TIMETABLE_IP = "149.154.64.204"
