QOS_DEV_STATIC_ENABLED = False
QOS_DEV_CSRF_DISABLED = False
QOS_DEV_AUTOLOGIN_ENABLED = False
QOS_DEV_AUTOLOGIN_USERNAME = None
QOS_DEV_AUTOLOGIN_PASSWORD = None

QOS_CAMERA_KEY='1'


HOST_IP = '127.0.0.1:8000' # dev
TIMETABLE_IP = "127.0.0.1:5000"

