name: Tests

on:
  pull_request:
    branches: [ "master" ]
  release:
    types: [published]
#  workflow_dispatch:

jobs:
  tests:
    runs-on: self-hosted
    concurrency: tests
    env:
      COMPOSE_FILE: sample.docker-compose.yml
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1

    steps:
    - uses: actions/checkout@v3

    - name: Initiate containers
      run: docker-compose up -d

    - name: Run tests
      run: docker-compose exec -T web ./manage.py test --noinput --parallel 6

    - name: Stop containers
      if: always()
      run: docker-compose stop
